/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { FullPageDto } from '../models/index'
import { FullPageDtoFromJSON, FullPageDtoToJSON } from '../models/index'

export interface PageRequest {
  xwikiPageId: string
  domainLanguage: PageDomainLanguageEnum
}

/**
 *
 */
export class ContentApi extends runtime.BaseAPI {
  /**
   * Return the rendered XWiki page along with metadata.
   * Get XWiki page
   */
  async pageRaw(
    requestParameters: PageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    if (requestParameters['xwikiPageId'] == null) {
      throw new runtime.RequiredError(
        'xwikiPageId',
        'Required parameter "xwikiPageId" was null or undefined when calling page().'
      )
    }

    if (requestParameters['domainLanguage'] == null) {
      throw new runtime.RequiredError(
        'domainLanguage',
        'Required parameter "domainLanguage" was null or undefined when calling page().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['domainLanguage'] != null) {
      queryParameters['domainLanguage'] = requestParameters['domainLanguage']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password)
    }
    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/pages/{xwikiPageId}`
    urlPath = urlPath.replace(
      `{${'xwikiPageId'}}`,
      encodeURIComponent(String(requestParameters['xwikiPageId']))
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<{ [key: string]: any }>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Return the rendered XWiki page along with metadata.
   * Get XWiki page
   */
  async page(
    requestParameters: PageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<{ [key: string]: any }> {
    const response = await this.pageRaw(requestParameters, initOverrides)
    return await response.value()
  }
}

/**
 * @export
 */
export const PageDomainLanguageEnum = {
  Fr: 'fr',
  En: 'en',
} as const
export type PageDomainLanguageEnum =
  (typeof PageDomainLanguageEnum)[keyof typeof PageDomainLanguageEnum]
