/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExposedDocsContentDto,
  ExposedDocsOverviewDto,
  ExposedDocsSearchResultDto,
  ExposedDocsTreeNodeDto,
} from '../models/index';
import {
    ExposedDocsContentDtoFromJSON,
    ExposedDocsContentDtoToJSON,
    ExposedDocsOverviewDtoFromJSON,
    ExposedDocsOverviewDtoToJSON,
    ExposedDocsSearchResultDtoFromJSON,
    ExposedDocsSearchResultDtoToJSON,
    ExposedDocsTreeNodeDtoFromJSON,
    ExposedDocsTreeNodeDtoToJSON,
} from '../models/index';

export interface GetContentRequest {
    categoryId: string;
    path: string;
    domainLanguage: GetContentDomainLanguageEnum;
}

export interface GetOverviewRequest {
    domainLanguage: GetOverviewDomainLanguageEnum;
}

export interface GetTreeRequest {
    categoryId: string;
    domainLanguage: GetTreeDomainLanguageEnum;
}

export interface SearchRequest {
    domainLanguage: SearchDomainLanguageEnum;
    query?: string;
    categories?: Array<string>;
    pathPrefix?: string;
    searchContent?: boolean;
    includeContent?: boolean;
}

/**
 * 
 */
export class ExposedDocsApi extends runtime.BaseAPI {

    /**
     * Returns the raw content of a documentation resource.
     * Get exposed resource content
     */
    async getContentRaw(requestParameters: GetContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExposedDocsContentDto>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling getContent().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getContent().'
            );
        }

        if (requestParameters['domainLanguage'] == null) {
            throw new runtime.RequiredError(
                'domainLanguage',
                'Required parameter "domainLanguage" was null or undefined when calling getContent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['domainLanguage'] != null) {
            queryParameters['domainLanguage'] = requestParameters['domainLanguage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/exposed/{categoryId}/content`;
        urlPath = urlPath.replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExposedDocsContentDtoFromJSON(jsonValue));
    }

    /**
     * Returns the raw content of a documentation resource.
     * Get exposed resource content
     */
    async getContent(requestParameters: GetContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExposedDocsContentDto> {
        const response = await this.getContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the categories of embedded resources exposed by the documentation service.
     * List exposed documentation categories
     */
    async getOverviewRaw(requestParameters: GetOverviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExposedDocsOverviewDto>> {
        if (requestParameters['domainLanguage'] == null) {
            throw new runtime.RequiredError(
                'domainLanguage',
                'Required parameter "domainLanguage" was null or undefined when calling getOverview().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['domainLanguage'] != null) {
            queryParameters['domainLanguage'] = requestParameters['domainLanguage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/exposed`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExposedDocsOverviewDtoFromJSON(jsonValue));
    }

    /**
     * Returns the categories of embedded resources exposed by the documentation service.
     * List exposed documentation categories
     */
    async getOverview(requestParameters: GetOverviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExposedDocsOverviewDto> {
        const response = await this.getOverviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the directory tree for a specific exposed resource category.
     * Get exposed resource tree
     */
    async getTreeRaw(requestParameters: GetTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExposedDocsTreeNodeDto>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling getTree().'
            );
        }

        if (requestParameters['domainLanguage'] == null) {
            throw new runtime.RequiredError(
                'domainLanguage',
                'Required parameter "domainLanguage" was null or undefined when calling getTree().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['domainLanguage'] != null) {
            queryParameters['domainLanguage'] = requestParameters['domainLanguage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/exposed/{categoryId}`;
        urlPath = urlPath.replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExposedDocsTreeNodeDtoFromJSON(jsonValue));
    }

    /**
     * Returns the directory tree for a specific exposed resource category.
     * Get exposed resource tree
     */
    async getTree(requestParameters: GetTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExposedDocsTreeNodeDto> {
        const response = await this.getTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Searches exposed documentation and prompt resources by path or content.
     * Search exposed resources
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExposedDocsSearchResultDto<any>>> {
        if (requestParameters['domainLanguage'] == null) {
            throw new runtime.RequiredError(
                'domainLanguage',
                'Required parameter "domainLanguage" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories'] = requestParameters['categories'];
        }

        if (requestParameters['pathPrefix'] != null) {
            queryParameters['pathPrefix'] = requestParameters['pathPrefix'];
        }

        if (requestParameters['searchContent'] != null) {
            queryParameters['searchContent'] = requestParameters['searchContent'];
        }

        if (requestParameters['includeContent'] != null) {
            queryParameters['includeContent'] = requestParameters['includeContent'];
        }

        if (requestParameters['domainLanguage'] != null) {
            queryParameters['domainLanguage'] = requestParameters['domainLanguage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/exposed/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Searches exposed documentation and prompt resources by path or content.
     * Search exposed resources
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExposedDocsSearchResultDto<any>> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetContentDomainLanguageEnum = {
    Fr: 'fr',
    En: 'en'
} as const;
export type GetContentDomainLanguageEnum = typeof GetContentDomainLanguageEnum[keyof typeof GetContentDomainLanguageEnum];
/**
 * @export
 */
export const GetOverviewDomainLanguageEnum = {
    Fr: 'fr',
    En: 'en'
} as const;
export type GetOverviewDomainLanguageEnum = typeof GetOverviewDomainLanguageEnum[keyof typeof GetOverviewDomainLanguageEnum];
/**
 * @export
 */
export const GetTreeDomainLanguageEnum = {
    Fr: 'fr',
    En: 'en'
} as const;
export type GetTreeDomainLanguageEnum = typeof GetTreeDomainLanguageEnum[keyof typeof GetTreeDomainLanguageEnum];
/**
 * @export
 */
export const SearchDomainLanguageEnum = {
    Fr: 'fr',
    En: 'en'
} as const;
export type SearchDomainLanguageEnum = typeof SearchDomainLanguageEnum[keyof typeof SearchDomainLanguageEnum];
