/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GoogleIndexationMetricsDto,
} from '../models/index';
import {
    GoogleIndexationMetricsDtoFromJSON,
    GoogleIndexationMetricsDtoToJSON,
} from '../models/index';

export interface MetricsRequest {
    domainLanguage: MetricsDomainLanguageEnum;
}

/**
 * 
 */
export class IndexationApi extends runtime.BaseAPI {

    /**
     * Expose queue metrics and recent dispatch status for Google Indexation.
     * Get Google Indexation metrics
     */
    async metricsRaw(requestParameters: MetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoogleIndexationMetricsDto>> {
        if (requestParameters['domainLanguage'] == null) {
            throw new runtime.RequiredError(
                'domainLanguage',
                'Required parameter "domainLanguage" was null or undefined when calling metrics().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['domainLanguage'] != null) {
            queryParameters['domainLanguage'] = requestParameters['domainLanguage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/indexation/metrics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoogleIndexationMetricsDtoFromJSON(jsonValue));
    }

    /**
     * Expose queue metrics and recent dispatch status for Google Indexation.
     * Get Google Indexation metrics
     */
    async metrics(requestParameters: MetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoogleIndexationMetricsDto> {
        const response = await this.metricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const MetricsDomainLanguageEnum = {
    Fr: 'fr',
    En: 'en'
} as const;
export type MetricsDomainLanguageEnum = typeof MetricsDomainLanguageEnum[keyof typeof MetricsDomainLanguageEnum];
