/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IpQuotaCategory,
  IpQuotaStatusDto,
} from '../models/index';
import {
    IpQuotaCategoryFromJSON,
    IpQuotaCategoryToJSON,
    IpQuotaStatusDtoFromJSON,
    IpQuotaStatusDtoToJSON,
} from '../models/index';

export interface GetQuotaStatusRequest {
    category: IpQuotaCategory;
    domainLanguage: GetQuotaStatusDomainLanguageEnum;
}

/**
 * 
 */
export class QuotaApi extends runtime.BaseAPI {

    /**
     * Return the quota usage and remaining tokens for the requested category.
     * Get IP quota status
     */
    async getQuotaStatusRaw(requestParameters: GetQuotaStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IpQuotaStatusDto>> {
        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling getQuotaStatus().'
            );
        }

        if (requestParameters['domainLanguage'] == null) {
            throw new runtime.RequiredError(
                'domainLanguage',
                'Required parameter "domainLanguage" was null or undefined when calling getQuotaStatus().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['domainLanguage'] != null) {
            queryParameters['domainLanguage'] = requestParameters['domainLanguage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/quota/{category}`;
        urlPath = urlPath.replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IpQuotaStatusDtoFromJSON(jsonValue));
    }

    /**
     * Return the quota usage and remaining tokens for the requested category.
     * Get IP quota status
     */
    async getQuotaStatus(requestParameters: GetQuotaStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IpQuotaStatusDto> {
        const response = await this.getQuotaStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetQuotaStatusDomainLanguageEnum = {
    Fr: 'fr',
    En: 'en'
} as const;
export type GetQuotaStatusDomainLanguageEnum = typeof GetQuotaStatusDomainLanguageEnum[keyof typeof GetQuotaStatusDomainLanguageEnum];
