/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { CategoriesStatsDto } from '../models/index'
import {
  CategoriesStatsDtoFromJSON,
  CategoriesStatsDtoToJSON,
} from '../models/index'

export interface CategoriesRequest {
  domainLanguage: CategoriesDomainLanguageEnum
}

/**
 *
 */
export class StatsApi extends runtime.BaseAPI {
  /**
   * Return aggregated statistics about vertical category mappings and affiliation partners.
   * Get categories statistics
   */
  async categoriesRaw(
    requestParameters: CategoriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<CategoriesStatsDto>> {
    if (requestParameters['domainLanguage'] == null) {
      throw new runtime.RequiredError(
        'domainLanguage',
        'Required parameter "domainLanguage" was null or undefined when calling categories().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['domainLanguage'] != null) {
      queryParameters['domainLanguage'] = requestParameters['domainLanguage']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('bearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/stats/categories`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, jsonValue =>
      CategoriesStatsDtoFromJSON(jsonValue)
    )
  }

  /**
   * Return aggregated statistics about vertical category mappings and affiliation partners.
   * Get categories statistics
   */
  async categories(
    requestParameters: CategoriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<CategoriesStatsDto> {
    const response = await this.categoriesRaw(requestParameters, initOverrides)
    return await response.value()
  }
}

/**
 * @export
 */
export const CategoriesDomainLanguageEnum = {
  Fr: 'fr',
  En: 'en',
} as const
export type CategoriesDomainLanguageEnum =
  (typeof CategoriesDomainLanguageEnum)[keyof typeof CategoriesDomainLanguageEnum]
