/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserGeoloc,
} from '../models/index';
import {
    UserGeolocFromJSON,
    UserGeolocToJSON,
} from '../models/index';

export interface Geoloc1Request {
    domainLanguage: Geoloc1DomainLanguageEnum;
    ip?: string;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Resolve the requesting user IP address using the MaxMind GeoIP database.
     * Get user geolocation
     */
    async geoloc1Raw(requestParameters: Geoloc1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserGeoloc>> {
        if (requestParameters['domainLanguage'] == null) {
            throw new runtime.RequiredError(
                'domainLanguage',
                'Required parameter "domainLanguage" was null or undefined when calling geoloc1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['domainLanguage'] != null) {
            queryParameters['domainLanguage'] = requestParameters['domainLanguage'];
        }

        if (requestParameters['ip'] != null) {
            queryParameters['ip'] = requestParameters['ip'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/geoloc`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserGeolocFromJSON(jsonValue));
    }

    /**
     * Resolve the requesting user IP address using the MaxMind GeoIP database.
     * Get user geolocation
     */
    async geoloc1(requestParameters: Geoloc1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserGeoloc> {
        const response = await this.geoloc1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const Geoloc1DomainLanguageEnum = {
    Fr: 'fr',
    En: 'en'
} as const;
export type Geoloc1DomainLanguageEnum = typeof Geoloc1DomainLanguageEnum[keyof typeof Geoloc1DomainLanguageEnum];
