#!/usr/bin/env python3
"""Generate project MCP client files from ops/mcp/servers.yml."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = Path("ops/mcp/servers.yml")
TARGETS = {
    "claude": Path(".mcp.json"),
    "codex": Path(".codex/config.toml"),
    "gemini": Path(".gemini/settings.json"),
    "vscode": Path(".vscode/mcp.json"),
}


def selected(server: dict, client: str) -> bool:
    """Return whether a server is projected for one client."""
    return client in (server.get("clients") or list(TARGETS))


def json_server(server: dict, client: str) -> dict:
    """Render a server in the JSON shape accepted by the selected client."""
    transport = server["transport"]
    if transport == "sse":
        result = {"url": server["url"]}
        if client in {"claude", "vscode"}:
            result["type"] = "sse"
        return result
    result = {"command": server["command"], "args": [str(value) for value in server.get("args", [])]}
    if client in {"claude", "vscode"}:
        result["type"] = "stdio"
    environment = dict(server.get("env") or {})
    environment.update({name: f"${{{name}}}" for name in server.get("passEnv") or []})
    if environment:
        result["env"] = environment
    return result


def render_json(manifest: dict, client: str) -> str:
    key = "servers" if client == "vscode" else "mcpServers"
    servers = {
        name: json_server(server, client)
        for name, server in manifest["servers"].items()
        if selected(server, client)
    }
    payload = {key: servers}
    if client == "vscode":
        payload["inputs"] = []
    return json.dumps(payload, indent=2) + "\n"


def quote(value: str) -> str:
    """JSON strings are valid TOML basic strings."""
    return json.dumps(value)


def render_codex(manifest: dict) -> str:
    lines = ["# Generated by scripts/generate/generate_mcp_configs.py; do not edit."]
    for name, server in manifest["servers"].items():
        if not selected(server, "codex"):
            continue
        lines += ["", f"[mcp_servers.{name}]"]
        if server["transport"] == "sse":
            lines.append(f"url = {quote(server['url'])}")
            continue
        lines.append(f"command = {quote(server['command'])}")
        arguments = ", ".join(quote(str(value)) for value in server.get("args") or [])
        lines.append(f"args = [{arguments}]")
        passed = server.get("passEnv") or []
        if passed:
            lines.append(f"env_vars = [{', '.join(quote(value) for value in passed)}]")
        environment = server.get("env") or {}
        if environment:
            lines += ["", f"[mcp_servers.{name}.env]"]
            lines.extend(f"{key} = {quote(str(value))}" for key, value in environment.items())
    return "\n".join(lines) + "\n"


def render_all(root: Path) -> dict[Path, str]:
    manifest = yaml.safe_load((root / MANIFEST).read_text(encoding="utf-8"))
    if manifest.get("version") != 1 or not isinstance(manifest.get("servers"), dict):
        raise ValueError("unsupported MCP manifest")
    return {
        TARGETS["claude"]: render_json(manifest, "claude"),
        TARGETS["codex"]: render_codex(manifest),
        TARGETS["gemini"]: render_json(manifest, "gemini"),
        TARGETS["vscode"]: render_json(manifest, "vscode"),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for relative, content in render_all(args.root).items():
        target = args.root / relative
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                stale.append(str(relative))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            print(f"Wrote {relative}")
    if stale:
        print(f"stale MCP projections: {', '.join(stale)}", file=sys.stderr)
        return 1
    if args.check:
        print("OK: MCP client projections match ops/mcp/servers.yml.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
