# .pre-commit-config.yaml
minimum_pre_commit_version: "3.5.0"

# Exclure ce répertoire de tous les hooks
exclude: ^api/src/main/resources/templates/

repos:
  # Hooks de base (rapides)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Règles YAML (style + bonnes pratiques)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
