package org.open4goods.model.resource;

public enum ResourceStatus {
	MD5_CHECKSUM_FAIL, PROTOCOL_EXCEPTION, IO_EXCEPTION, NO_MIME_TYPE, MD5_EXCLUSION, MD5_DUPLICATE, TOO_SMALL, CANNOT_ANALYSE, PERCEPTIV_HASH_FAIL

}
