package org.open4goods.nudgerfrontapi.service.auth;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.List;

import org.open4goods.nudgerfrontapi.config.properties.GoogleSsoProperties;
import org.open4goods.nudgerfrontapi.service.exception.GoogleIdentityVerificationException;
import org.open4goods.nudgerfrontapi.service.exception.GoogleSsoDisabledException;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtException;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

/**
 * Verifies Google OIDC ID tokens forwarded by the Nuxt BFF and resolves the
 * caller's roles from the environment email allowlist.
 * <p>
 * Trust boundary: nothing from the raw ID token payload is used before the
 * signature, issuer, audience, expiry and nonce have all been checked. The
 * allowlist is deny-by-default - an unverified or unlisted email never
 * receives a role.
 * </p>
 */
@Service
public class GoogleIdentityService {

    private final GoogleSsoProperties properties;
    private volatile NimbusJwtDecoder decoder;
    private volatile String decoderJwksUri;

    public GoogleIdentityService(GoogleSsoProperties properties) {
        this.properties = properties;
    }

    /**
     * Verify a Google ID token and resolve the caller's allowlisted roles.
     *
     * @param idToken       raw Google-issued ID token
     * @param expectedNonce nonce generated by the BFF for this authorization request
     * @return the resolved identity, never with an empty role list
     * @throws GoogleSsoDisabledException          when the feature flag is off
     * @throws GoogleIdentityVerificationException when the token is invalid, unverified,
     *                                              replayed with a mismatched nonce, or the
     *                                              email is absent from the allowlist
     */
    public GoogleIdentity verify(String idToken, String expectedNonce) {
        if (!properties.isEnabled()) {
            throw new GoogleSsoDisabledException();
        }
        if (!StringUtils.hasText(idToken)) {
            throw new GoogleIdentityVerificationException("Missing Google ID token");
        }
        if (!StringUtils.hasText(properties.getClientId())) {
            throw new GoogleIdentityVerificationException("Google SSO client id is not configured");
        }

        Jwt jwt;
        try {
            jwt = decoder().decode(idToken);
        } catch (JwtException | IllegalArgumentException ex) {
            throw new GoogleIdentityVerificationException("Google ID token verification failed", ex);
        }

        if (jwt.getIssuer() == null || !properties.getIssuer().equals(jwt.getIssuer().toString())) {
            throw new GoogleIdentityVerificationException("Google ID token issuer mismatch");
        }
        List<String> audience = jwt.getAudience();
        if (audience == null || !audience.contains(properties.getClientId())) {
            throw new GoogleIdentityVerificationException("Google ID token audience mismatch");
        }
        if (jwt.getExpiresAt() == null) {
            throw new GoogleIdentityVerificationException("Google ID token is missing an expiry");
        }
        if (!nonceMatches(expectedNonce, jwt.getClaimAsString("nonce"))) {
            throw new GoogleIdentityVerificationException("Google ID token nonce mismatch");
        }
        if (!Boolean.TRUE.equals(jwt.getClaim("email_verified"))) {
            throw new GoogleIdentityVerificationException("Google account email is not verified");
        }
        String email = jwt.getClaimAsString("email");
        if (!StringUtils.hasText(email)) {
            throw new GoogleIdentityVerificationException("Google ID token is missing an email");
        }

        List<String> roles = properties.rolesFor(email);
        if (roles.isEmpty()) {
            throw new GoogleIdentityVerificationException("Email is not present in the environment role allowlist");
        }
        return new GoogleIdentity(email, roles);
    }

    /**
     * Constant-time, Unicode-safe nonce comparison. Comparing raw
     * {@code String#equals} (or lengths) leaks timing information and can
     * desynchronize on multi-byte UTF-16 surrogate pairs; comparing UTF-8 byte
     * arrays with {@link MessageDigest#isEqual} avoids both.
     */
    private boolean nonceMatches(String expected, String actual) {
        if (expected == null || actual == null) {
            return false;
        }
        byte[] expectedBytes = expected.getBytes(StandardCharsets.UTF_8);
        byte[] actualBytes = actual.getBytes(StandardCharsets.UTF_8);
        return MessageDigest.isEqual(expectedBytes, actualBytes);
    }

    private NimbusJwtDecoder decoder() {
        String jwksUri = properties.getJwksUri();
        NimbusJwtDecoder current = decoder;
        if (current == null || !jwksUri.equals(decoderJwksUri)) {
            synchronized (this) {
                if (decoder == null || !jwksUri.equals(decoderJwksUri)) {
                    decoder = NimbusJwtDecoder.withJwkSetUri(jwksUri).build();
                    decoderJwksUri = jwksUri;
                }
            }
        }
        return decoder;
    }
}
