package org.open4goods.model.eprel;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import org.open4goods.model.helper.IdHelper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;
import org.springframework.data.elasticsearch.annotations.Setting;
import org.springframework.data.elasticsearch.annotations.WriteTypeHint;

import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * Elasticsearch document representing a single EPREL product entry.
 */
@Document(indexName = "eprel-products",  writeTypeHint = WriteTypeHint.FALSE)
@Setting(settingPath = "settings/eprel-product-settings.json")
@JsonIgnoreProperties(ignoreUnknown = false)
public class EprelProduct implements Serializable
{

	private static final Logger LOGGER = LoggerFactory.getLogger(EprelProduct.class);


    @Serial
    private static final long serialVersionUID = -2835057113980761650L;

    /**
     * Unique registration number assigned by EPREL.
     */
    @Id
    @Field(type = FieldType.Keyword, index = false)
    private String eprelRegistrationNumber;

    /**
     * Product group code as defined by EPREL.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String productGroup;

    /**
     * Delegated act defining the product requirements.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String implementingAct;

    /**
     * Internal trademark identifier managed by EPREL.
     */
    @Field(type = FieldType.Long, index = false)
    private Long trademarkId;

    /**
     * Supplier's name or trademark.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String supplierOrTrademark;

    /**
     * Manufacturer model identifier.
     */
    @Field(type = FieldType.Keyword, normalizer = "lowercase")
    private String modelIdentifier;

    /**
     * Identifier of the model version in EPREL systems.
     */
    @Field(type = FieldType.Long, index = false)
    private Long versionId;

    /**
     * Version number of the model.
     */
    @Field(type = FieldType.Double, index = false)
    private BigDecimal versionNumber;

    /**
     * Flag indicating whether the current version is the latest one.
     */
    @Field(type = FieldType.Boolean, index = false)
    private Boolean lastVersion;

    /**
     * Supplier acceptance of labels generated by EPREL.
     */
    @Field(type = FieldType.Boolean, index = false)
    private Boolean allowEprelLabelGeneration;

    /**
     * Internal identifier of the product model core.
     */
    @Field(type = FieldType.Long, index = false)
    private Long productModelCoreId;

    /**
     * On-market start date represented as epoch seconds.
     */
    @Field(type = FieldType.Long, index = false)
    private Long onMarketStartDate;

    /**
     * On-market start timestamp provided by EPREL.
     */
    @Field(type = FieldType.Long, index = false)
    private Long onMarketStartDateTs;

    /**
     * On-market end date represented as epoch seconds.
     */
    @Field(type = FieldType.Long, index = false)
    private Long onMarketEndDate;

    /**
     * On-market end timestamp provided by EPREL.
     */
    @Field(type = FieldType.Long, index = false)
    private Long onMarketEndDateTs;

    /**
     * First on-market date for the model represented as epoch seconds.
     */
    @Field(type = FieldType.Long, index = false)
    private Long onMarketFirstStartDate;

    /**
     * First on-market date timestamp.
     */
    @Field(type = FieldType.Long, index = false)
    private Long onMarketFirstStartDateTs;

    /**
     * First publication date represented as epoch seconds.
     */
    @Field(type = FieldType.Long, index = false)
    private Long firstPublicationDate;

    /**
     * First publication timestamp provided by EPREL.
     */
    @Field(type = FieldType.Long, index = false)
    private Long firstPublicationDateTs;

    /**
     * Last publication date represented as epoch seconds.
     */
    @Field(type = FieldType.Long, index = false)
    private Long publishedOnDate;

    /**
     * Last publication timestamp provided by EPREL.
     */
    @Field(type = FieldType.Long, index = false)
    private Long publishedOnDateTs;

    /**
     * Registration nature of the organisation (manufacturer, importer, etc.).
     */
    @Field(type = FieldType.Keyword, index = false)
    private String registrantNature;


    @Field(type = FieldType.Keyword, index = false)
    private String constructedEUID;





    /**
     * Identifier of the generated energy label.
     */
    @Field(type = FieldType.Long, index = false)
    private Long energyLabelId;

    /**
     * Publication status of the model.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String status;

    /**
     * Indicates whether scale validation was skipped.
     */
    @Field(type = FieldType.Boolean, index = false)
    private Boolean skipScaleValidation;

    /**
     * Energy efficiency class.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String energyClass;

    /**
     * Associated energy class image filename.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String energyClassImage;

    /**
     * Form type used to capture the model details.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String formType;

    /**
     * Flag controlling visibility of compliance data to the UK MSA.
     */
    @Field(type = FieldType.Boolean, index = false)
    private Boolean visibleToUkMsa;

    /**
     * Export timestamp recorded by EPREL.
     */
    @Field(type = FieldType.Long, index = false)
    private Long exportDateTs;

    /**
     * Import timestamp recorded by EPREL.
     */
    @Field(type = FieldType.Long, index = false)
    private Long importedOn;

    /**
     * Verification status of the organisation.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String orgVerificationStatus;

    /**
     * Verification status of the trademark.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String trademarkVerificationStatus;

    /**
     * Indicates whether the product is blocked in EPREL.
     */
    @Field(type = FieldType.Boolean, index = false)
    private Boolean blocked;

    /**
     * Supplier provided labels associated with the product.
     */
    @Field(type = FieldType.Object, enabled = false)
    private List<UploadedLabel> uploadedLabels = new ArrayList<>();

    /**
     * Public contact details provided for the product.
     */
    @Field(type = FieldType.Object, enabled = false)
    private ContactDetails contactDetails;

    /**
     * Countries where the product is placed on the market.
     */
    @Field(type = FieldType.Object, enabled = false)
    private List<PlacementCountry> placementCountries = new ArrayList<>();

    /**
     * Organisation responsible for the product.
     */
    @Field(type = FieldType.Object, enabled = false)
    private Organisation organisation;

    /**
     * Main GTIN identifier exposed at the root level.
     */
    @Field(type = FieldType.Keyword, index = false)
    private String gtinIdentifier;

    /**
     * Numeric representation of the GTIN used for exact queries.
     */
    @Field(type = FieldType.Long)
    private Long numericGtin;

    /**
     * Additional details section provided by EPREL.
     */
    @Field(type = FieldType.Object, enabled = false)
    private AdditionalDetails additionalDetails;

    /**
     * EPREL categories associated with the product.
     */
    @Field(type = FieldType.Keyword, name = "eprelCategory")
    private List<String> eprelCategories = new ArrayList<>();

    /**
     * @deprecated kept for backward compatibility with legacy single-value payloads.
     */
    @Deprecated
    private String eprelCategory;

    /**
     * Attributes not part of the common specification, specific to each category.
     */
    @Field(type = FieldType.Object, enabled = false)
    private Map<String, Object> categorySpecificAttributes = new HashMap<>();

    public void setOnMarketStartDate(Long onMarketStartDate) {
		this.onMarketStartDate = onMarketStartDate;
	}

	public void setOnMarketEndDate(Long onMarketEndDate) {
		this.onMarketEndDate = onMarketEndDate;
	}

	public void setOnMarketFirstStartDate(Long onMarketFirstStartDate) {
		this.onMarketFirstStartDate = onMarketFirstStartDate;
	}

	public void setFirstPublicationDate(Long firstPublicationDate) {
		this.firstPublicationDate = firstPublicationDate;
	}

	public void setPublishedOnDate(Long publishedOnDate) {
		this.publishedOnDate = publishedOnDate;
	}

	public void setNumericGtin(Long numericGtin) {
		this.numericGtin = numericGtin;
	}

	public void setCategorySpecificAttributes(Map<String, Object> categorySpecificAttributes) {
		this.categorySpecificAttributes = categorySpecificAttributes;
	}

	public String getConstructedEUID() {
		return constructedEUID;
	}

	public void setConstructedEUID(String constructedEUID) {
		this.constructedEUID = constructedEUID;
	}

	/**
     * Populates the map with unknown attributes during deserialisation.
     *
     * @param name  attribute name
     * @param value attribute value
     */
    @JsonAnySetter
    public void putAdditionalAttribute(String name, Object value)
    {
        categorySpecificAttributes.put(name, value);
    }

    public String getEprelRegistrationNumber()
    {
        return eprelRegistrationNumber;
    }

    public void setEprelRegistrationNumber(String eprelRegistrationNumber)
    {
        this.eprelRegistrationNumber = eprelRegistrationNumber;
    }

    public String getProductGroup()
    {
        return productGroup;
    }

    public void setProductGroup(String productGroup)
    {
        this.productGroup = productGroup;
    }

    public String getImplementingAct()
    {
        return implementingAct;
    }

    public void setImplementingAct(String implementingAct)
    {
        this.implementingAct = implementingAct;
    }

    public Long getTrademarkId()
    {
        return trademarkId;
    }

    public void setTrademarkId(Long trademarkId)
    {
        this.trademarkId = trademarkId;
    }

    public String getSupplierOrTrademark()
    {
        return supplierOrTrademark;
    }

    public void setSupplierOrTrademark(String supplierOrTrademark)
    {
        this.supplierOrTrademark = supplierOrTrademark;
    }

    public String getModelIdentifier()
    {
        return modelIdentifier;
    }

    public void setModelIdentifier(String modelIdentifier)
    {
        this.modelIdentifier = modelIdentifier;
    }

    public Long getVersionId()
    {
        return versionId;
    }

    public void setVersionId(Long versionId)
    {
        this.versionId = versionId;
    }

    public BigDecimal getVersionNumber()
    {
        return versionNumber;
    }

    public void setVersionNumber(BigDecimal versionNumber)
    {
        this.versionNumber = versionNumber;
    }

    public Boolean getLastVersion()
    {
        return lastVersion;
    }

    public void setLastVersion(Boolean lastVersion)
    {
        this.lastVersion = lastVersion;
    }

    public Boolean getAllowEprelLabelGeneration()
    {
        return allowEprelLabelGeneration;
    }

    public void setAllowEprelLabelGeneration(Boolean allowEprelLabelGeneration)
    {
        this.allowEprelLabelGeneration = allowEprelLabelGeneration;
    }

    public Long getProductModelCoreId()
    {
        return productModelCoreId;
    }

    public void setProductModelCoreId(Long productModelCoreId)
    {
        this.productModelCoreId = productModelCoreId;
    }

    public Long getOnMarketStartDate()
    {
        return onMarketStartDate;
    }

    @JsonSetter("onMarketStartDate")
    public void setOnMarketStartDate(Object dateParts)
    {
        this.onMarketStartDate = toEpochFromObject(dateParts);
    }

    public Long getOnMarketStartDateTs()
    {
        return onMarketStartDateTs;
    }

    @JsonSetter("onMarketStartDateTS")
    public void setOnMarketStartDateTs(Long onMarketStartDateTs)
    {
        this.onMarketStartDateTs = onMarketStartDateTs;
    }

    public Long getOnMarketEndDate()
    {
        return onMarketEndDate;
    }

    @JsonSetter("onMarketEndDate")
    public void setOnMarketEndDate(Object dateParts)
    {
        this.onMarketEndDate = toEpochFromObject(dateParts);
    }

    public Long getOnMarketEndDateTs()
    {
        return onMarketEndDateTs;
    }

    @JsonSetter("onMarketEndDateTS")
    public void setOnMarketEndDateTs(Long onMarketEndDateTs)
    {
        this.onMarketEndDateTs = onMarketEndDateTs;
    }

    public Long getOnMarketFirstStartDate()
    {
        return onMarketFirstStartDate;
    }

    @JsonSetter("onMarketFirstStartDate")
    public void setOnMarketFirstStartDate(Object dateParts)
    {
        this.onMarketFirstStartDate = toEpochFromObject(dateParts);
    }

    public Long getOnMarketFirstStartDateTs()
    {
        return onMarketFirstStartDateTs;
    }

    @JsonSetter("onMarketFirstStartDateTS")
    public void setOnMarketFirstStartDateTs(Long onMarketFirstStartDateTs)
    {
        this.onMarketFirstStartDateTs = onMarketFirstStartDateTs;
    }

    public Long getFirstPublicationDate()
    {
        return firstPublicationDate;
    }

    @JsonSetter("firstPublicationDate")
    public void setFirstPublicationDate(Object dateParts)
    {
        this.firstPublicationDate = toEpochFromObject(dateParts);
    }

    public Long getFirstPublicationDateTs()
    {
        return firstPublicationDateTs;
    }

    @JsonSetter("firstPublicationDateTS")
    public void setFirstPublicationDateTs(Long firstPublicationDateTs)
    {
        this.firstPublicationDateTs = firstPublicationDateTs;
    }

    public Long getPublishedOnDate()
    {
        return publishedOnDate;
    }

    @JsonSetter("publishedOnDate")
    public void setPublishedOnDate(Object dateParts)
    {
        this.publishedOnDate = toEpochFromObject(dateParts);
    }

    public Long getPublishedOnDateTs()
    {
        return publishedOnDateTs;
    }

    @JsonSetter("publishedOnDateTS")
    public void setPublishedOnDateTs(Long publishedOnDateTs)
    {
        this.publishedOnDateTs = publishedOnDateTs;
    }

    public String getRegistrantNature()
    {
        return registrantNature;
    }

    public void setRegistrantNature(String registrantNature)
    {
        this.registrantNature = registrantNature;
    }

    public Long getEnergyLabelId()
    {
        return energyLabelId;
    }

    public void setEnergyLabelId(Long energyLabelId)
    {
        this.energyLabelId = energyLabelId;
    }

    public String getStatus()
    {
        return status;
    }

    public void setStatus(String status)
    {
        this.status = status;
    }

    public Boolean getSkipScaleValidation()
    {
        return skipScaleValidation;
    }

    public void setSkipScaleValidation(Boolean skipScaleValidation)
    {
        this.skipScaleValidation = skipScaleValidation;
    }

    public String getEnergyClass()
    {
        return energyClass;
    }

    public void setEnergyClass(String energyClass)
    {
        this.energyClass = energyClass;
    }

    public String getEnergyClassImage()
    {
        return energyClassImage;
    }

    public void setEnergyClassImage(String energyClassImage)
    {
        this.energyClassImage = energyClassImage;
    }

    public String getFormType()
    {
        return formType;
    }

    public void setFormType(String formType)
    {
        this.formType = formType;
    }

    public Boolean getVisibleToUkMsa()
    {
        return visibleToUkMsa;
    }

    public void setVisibleToUkMsa(Boolean visibleToUkMsa)
    {
        this.visibleToUkMsa = visibleToUkMsa;
    }

    public Long getExportDateTs()
    {
        return exportDateTs;
    }

    public void setExportDateTs(Long exportDateTs)
    {
        this.exportDateTs = exportDateTs;
    }

    public Long getImportedOn()
    {
        return importedOn;
    }

    public void setImportedOn(Long importedOn)
    {
        this.importedOn = importedOn;
    }

    public String getOrgVerificationStatus()
    {
        return orgVerificationStatus;
    }

    public void setOrgVerificationStatus(String orgVerificationStatus)
    {
        this.orgVerificationStatus = orgVerificationStatus;
    }

    public String getTrademarkVerificationStatus()
    {
        return trademarkVerificationStatus;
    }

    public void setTrademarkVerificationStatus(String trademarkVerificationStatus)
    {
        this.trademarkVerificationStatus = trademarkVerificationStatus;
    }

    public Boolean getBlocked()
    {
        return blocked;
    }

    public void setBlocked(Boolean blocked)
    {
        this.blocked = blocked;
    }

    public List<UploadedLabel> getUploadedLabels()
    {
        return uploadedLabels;
    }

    public void setUploadedLabels(List<UploadedLabel> uploadedLabels)
    {
        this.uploadedLabels = Optional.ofNullable(uploadedLabels).map(ArrayList::new).orElseGet(ArrayList::new);
    }

    public ContactDetails getContactDetails()
    {
        return contactDetails;
    }

    public void setContactDetails(ContactDetails contactDetails)
    {
        this.contactDetails = contactDetails;
    }

    public List<PlacementCountry> getPlacementCountries()
    {
        return placementCountries;
    }

    public void setPlacementCountries(List<PlacementCountry> placementCountries)
    {
        this.placementCountries = Optional.ofNullable(placementCountries).map(ArrayList::new).orElseGet(ArrayList::new);
    }

    public Organisation getOrganisation()
    {
        return organisation;
    }

    public void setOrganisation(Organisation organisation)
    {
        this.organisation = organisation;
    }

    public String getGtinIdentifier()
    {
        return gtinIdentifier;
    }

    @JsonSetter("gtinIdentifier")
    public void setGtinIdentifier(String gtinIdentifier)
    {

    	if (null != gtinIdentifier) {
	        this.gtinIdentifier = gtinIdentifier;
	        try {
				this.numericGtin = Long.valueOf(gtinIdentifier.trim());
			} catch (NumberFormatException e) {
				LOGGER.warn("Non numeric gtinIdentifier {}",gtinIdentifier);
			}
    	}
    }

    public Long getNumericGtin()
    {
        return numericGtin;
    }

    public AdditionalDetails getAdditionalDetails()
    {
        return additionalDetails;
    }

    @JsonSetter("additionalDetails")
    public void setAdditionalDetails(AdditionalDetails additionalDetails)
    {
        this.additionalDetails = additionalDetails;
        if (this.gtinIdentifier == null && additionalDetails != null && additionalDetails.getGtinIdentifier() != null)
        {
            setGtinIdentifier(additionalDetails.getGtinIdentifier());
        }
    }

    public List<String> getEprelCategories()
    {
        return eprelCategories;
    }

    public void setEprelCategories(List<String> eprelCategories)
    {
        this.eprelCategories = sanitizeCategories(eprelCategories);
        this.eprelCategory = this.eprelCategories.isEmpty() ? null : this.eprelCategories.getFirst();
    }

    /**
     * @deprecated prefer {@link #getEprelCategories()}.
     */
    @Deprecated
    public String getEprelCategory()
    {
        if (eprelCategory != null)
        {
            return eprelCategory;
        }
        return eprelCategories.isEmpty() ? null : eprelCategories.getFirst();
    }

    /**
     * @deprecated prefer {@link #setEprelCategories(List)}.
     */
    @Deprecated
    public void setEprelCategory(String eprelCategory)
    {
        setEprelCategories(eprelCategory == null ? null : List.of(eprelCategory));
    }

    @JsonSetter("category")
    public void setEprelCategoriesFromPayload(Object categoryPayload)
    {
        if (categoryPayload == null)
        {
            setEprelCategories(null);
            return;
        }

        if (categoryPayload instanceof List<?> listPayload)
        {
            List<String> categories = listPayload.stream()
                .filter(Objects::nonNull)
                .map(Object::toString)
                .toList();
            setEprelCategories(categories);
            return;
        }

        setEprelCategories(List.of(categoryPayload.toString()));
    }

    public Map<String, Object> getCategorySpecificAttributes()
    {
        return categorySpecificAttributes;
    }

    private List<String> sanitizeCategories(List<String> categories)
    {
        if (categories == null)
        {
            return new ArrayList<>();
        }

        return categories.stream()
            .filter(Objects::nonNull)
            .map(String::trim)
            .filter(value -> !value.isEmpty())
            .distinct()
            .toList();
    }

    private Long toEpochFromObject(Object datePayload)
    {
        if (datePayload instanceof List<?> list)
        {
            return toEpoch(list);
        }
        else if (datePayload instanceof Number number)
        {
            long val = number.longValue();
            // Heuristic: If value is small (< 3000), treat as Year
            if (val < 3000) {
                return LocalDate.of((int) val, 1, 1).atStartOfDay().toEpochSecond(ZoneOffset.UTC);
            }
            // Else treat as epoch seconds (or millis if very large, but starting with seconds for now as per other fields)
            // EPREL usually sends year or array.
            return val;
        }
        return null;
    }

    private Long toEpoch(List<?> dateParts)
    {
        if (dateParts == null || dateParts.isEmpty())
        {
            return null;
        }
        Integer yearValue = valueAt(dateParts, 0);
        if (yearValue == null)
        {
            return null;
        }
        Integer monthValue = valueAt(dateParts, 1);
        Integer dayValue = valueAt(dateParts, 2);
        int month = monthValue == null || monthValue < 1 ? 1 : monthValue;
        int day = dayValue == null || dayValue < 1 ? 1 : dayValue;
        try
        {
            LocalDate date = LocalDate.of(yearValue, month, day);
            return date.atStartOfDay().toEpochSecond(ZoneOffset.UTC);
        }
        catch (Exception e)
        {
            return null;
        }
    }

    private Integer valueAt(List<?> parts, int index)
    {
        if (index >= parts.size())
        {
            return null;
        }
        Object value = parts.get(index);
        if (value instanceof Number number)
        {
            return number.intValue();
        }
        return null;
    }

    /**
     * Representation of contact details.
     */
    public static class ContactDetails implements Serializable
    {
        @Serial
        private static final long serialVersionUID = -2373560316348546888L;



        public ContactDetails() {
			super();
		}

		/** Identifier of the contact entry. */
        @JsonProperty("id")
        @Field(type = FieldType.Long, index = false)
        private Long id;

        @JsonProperty("countOfPublishedVersionsUsing")
        @Field(type = FieldType.Long, index = false)
        private Long countOfPublishedVersionsUsing;


        /** Order of the contact entry. */
        @JsonProperty("orderNumber")
        @Field(type = FieldType.Integer, index = false)
        private Integer orderNumber;

        /** Optional reference identifier. */
        @JsonProperty("contactByReferenceId")
        @Field(type = FieldType.Long, index = false)
        private Long contactByReferenceId;

        /** Human readable reference. */
        @JsonProperty("contactReference")
        @Field(type = FieldType.Keyword, index = false)
        private String contactReference;

        /** Service name exposed to end users. */
        @JsonProperty("serviceName")
        @Field(type = FieldType.Keyword, index = false)
        private String serviceName;

        /** Contact phone number. */
        @JsonProperty("phone")
        @Field(type = FieldType.Keyword, index = false)
        private String phone;

        /** Contact email address. */
        @JsonProperty("email")
        @Field(type = FieldType.Keyword, index = false)
        private String email;

        /** Contact website URL. */
        @JsonProperty("webSiteURL")
        @Field(type = FieldType.Keyword, index = false)
        private String webSiteUrl;

        /** Street information. */
        @JsonProperty("street")
        @Field(type = FieldType.Keyword, index = false)
        private String street;

        /** Street number information. */
        @JsonProperty("streetNumber")
        @Field(type = FieldType.Keyword, index = false)
        private String streetNumber;

        /** Postal code. */
        @JsonProperty("postalCode")
        @Field(type = FieldType.Keyword, index = false)
        private String postalCode;

        /** City name. */
        @JsonProperty("city")
        @Field(type = FieldType.Keyword, index = false)
        private String city;

        /** Province name. */
        @JsonProperty("province")
        @Field(type = FieldType.Keyword, index = false)
        private String province;

        /** Municipality name. */
        @JsonProperty("municipality")
        @Field(type = FieldType.Keyword, index = false)
        private String municipality;

        /** ISO country code. */
        @JsonProperty("country")
        @Field(type = FieldType.Keyword, index = false)
        private String country;

        /** Free text address block. */
        @JsonProperty("addressBloc")
        @Field(type = FieldType.Text, index = false)
        private String addressBloc;

        /** Whether the contact is the default entry. */
        @JsonProperty("defaultContact")
        @Field(type = FieldType.Boolean, index = false)
        private Boolean defaultContact;

        /** Number of models using the contact. */
        @JsonProperty("countOfModelsUsed")
        @Field(type = FieldType.Integer, index = false)
        private Integer countOfModelsUsed;

        /** Number of published models using the contact. */
        @JsonProperty("countOfPublishedModelsUsed")
        @Field(type = FieldType.Integer, index = false)
        private Integer countOfPublishedModelsUsed;

        /** Lifecycle status of the contact. */
        @JsonProperty("status")
        @Field(type = FieldType.Keyword, index = false)
        private String status;

        public Long getId()
        {
            return id;
        }

        public void setId(Long id)
        {
            this.id = id;
        }

        public Integer getOrderNumber()
        {
            return orderNumber;
        }

        public void setOrderNumber(Integer orderNumber)
        {
            this.orderNumber = orderNumber;
        }

        public Long getContactByReferenceId()
        {
            return contactByReferenceId;
        }

        public void setContactByReferenceId(Long contactByReferenceId)
        {
            this.contactByReferenceId = contactByReferenceId;
        }

        public String getContactReference()
        {
            return contactReference;
        }

        public void setContactReference(String contactReference)
        {
            this.contactReference = contactReference;
        }

        public String getServiceName()
        {
            return serviceName;
        }

        public void setServiceName(String serviceName)
        {
            this.serviceName = serviceName;
        }

        public String getPhone()
        {
            return phone;
        }

        public void setPhone(String phone)
        {
            this.phone = phone;
        }

        public String getEmail()
        {
            return email;
        }

        public void setEmail(String email)
        {
            this.email = email;
        }

        public String getWebSiteUrl()
        {
            return webSiteUrl;
        }

        public void setWebSiteUrl(String webSiteUrl)
        {
            this.webSiteUrl = webSiteUrl;
        }

        public String getStreet()
        {
            return street;
        }

        public void setStreet(String street)
        {
            this.street = street;
        }

        public String getStreetNumber()
        {
            return streetNumber;
        }

        public void setStreetNumber(String streetNumber)
        {
            this.streetNumber = streetNumber;
        }

        public String getPostalCode()
        {
            return postalCode;
        }

        public void setPostalCode(String postalCode)
        {
            this.postalCode = postalCode;
        }

        public String getCity()
        {
            return city;
        }

        public void setCity(String city)
        {
            this.city = city;
        }

        public String getProvince()
        {
            return province;
        }

        public void setProvince(String province)
        {
            this.province = province;
        }

        public String getMunicipality()
        {
            return municipality;
        }

        public void setMunicipality(String municipality)
        {
            this.municipality = municipality;
        }

        public String getCountry()
        {
            return country;
        }

        public void setCountry(String country)
        {
            this.country = country;
        }

        public String getAddressBloc()
        {
            return addressBloc;
        }

        public void setAddressBloc(String addressBloc)
        {
            this.addressBloc = addressBloc;
        }

        public Boolean getDefaultContact()
        {
            return defaultContact;
        }

        public void setDefaultContact(Boolean defaultContact)
        {
            this.defaultContact = defaultContact;
        }

        public Integer getCountOfModelsUsed()
        {
            return countOfModelsUsed;
        }

        public void setCountOfModelsUsed(Integer countOfModelsUsed)
        {
            this.countOfModelsUsed = countOfModelsUsed;
        }

        public Integer getCountOfPublishedModelsUsed()
        {
            return countOfPublishedModelsUsed;
        }

        public void setCountOfPublishedModelsUsed(Integer countOfPublishedModelsUsed)
        {
            this.countOfPublishedModelsUsed = countOfPublishedModelsUsed;
        }

        public String getStatus()
        {
            return status;
        }

        public void setStatus(String status)
        {
            this.status = status;
        }
    }

    /**
     * Representation of an uploaded label entry.
     */
    public static class UploadedLabel implements Serializable
    {
        @Serial
        private static final long serialVersionUID = -7273050835204053007L;

        public UploadedLabel() {
			super();
		}

        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        public UploadedLabel(String value) {
            this.fileName = value;         // orderNumber stays null unless you set it later
        }

		/** Position of the label in the list. */
        @JsonProperty("orderNumber")
        @Field(type = FieldType.Integer, index = false)
        private Integer orderNumber;

        /** File name of the uploaded label. */
        @JsonProperty("value")
        @Field(type = FieldType.Keyword, index = false)
        private String fileName;

        public Integer getOrderNumber()
        {
            return orderNumber;
        }

        public void setOrderNumber(Integer orderNumber)
        {
            this.orderNumber = orderNumber;
        }

        public String getFileName()
        {
            return fileName;
        }

        public void setFileName(String fileName)
        {
            this.fileName = fileName;
        }
    }

    /**
     * Representation of placement country entries.
     */
    public static class PlacementCountry implements Serializable
    {
        @Serial
        private static final long serialVersionUID = 8307787449924203331L;

        public PlacementCountry() {
			super();
		}

		/** Order number within the placement countries list. */
        @JsonProperty("orderNumber")
        @Field(type = FieldType.Integer, index = false)
        private Integer orderNumber;

        /** ISO country code. */
        @JsonProperty("country")
        @Field(type = FieldType.Keyword, index = false)
        private String country;

        public Integer getOrderNumber()
        {
            return orderNumber;
        }

        public void setOrderNumber(Integer orderNumber)
        {
            this.orderNumber = orderNumber;
        }

        public String getCountry()
        {
            return country;
        }

        public void setCountry(String country)
        {
            this.country = country;
        }
    }

    /**
     * Representation of the organisation associated with the product.
     */
    public static class Organisation implements Serializable
    {
        @Serial
        private static final long serialVersionUID = 2269515760849171758L;

        public Organisation() {
			super();
		}

		/** Organisation title shown publicly. */
        @JsonProperty("organisationTitle")
        @Field(type = FieldType.Keyword, index = false)
        private String organisationTitle;

        /** Organisation name. */
        @JsonProperty("organisationName")
        @Field(type = FieldType.Keyword, index = false)
        private String organisationName;

        @JsonProperty("eprelSuggestedOrgIdentifier")
        @Field(type = FieldType.Keyword, index = false)
        private String eprelSuggestedOrgIdentifier;

        @JsonProperty("modelTransferActive")
        @Field(type = FieldType.Keyword, index = false)
        private String modelTransferActive;

        /** First name of the representative when relevant. */
        @JsonProperty("firstName")
        @Field(type = FieldType.Keyword, index = false)
        private String firstName;

        /** Last name of the representative when relevant. */
        @JsonProperty("lastName")
        @Field(type = FieldType.Keyword, index = false)
        private String lastName;

        /** Organisation website URL. */
        @JsonProperty("website")
        @Field(type = FieldType.Keyword, index = false)
        private String website;

        /** Closing date if the organisation is no longer active. */
        @Field(type = FieldType.Long, index = false)
        private Long closeDate;

        /** Closing status indicator. */
        @JsonProperty("closeStatus")
        @Field(type = FieldType.Keyword, index = false)
        private String closeStatus;

        /** Whether the organisation is closed. */
        @JsonProperty("isClosed")
        @Field(type = FieldType.Boolean, index = false)
        private Boolean isClosed;

        /** Unique organisation GUID. */
        @JsonProperty("guid")
        @Field(type = FieldType.Keyword, index = false)
        private String guid;

        /** Type of person (legal or natural). */
        @JsonProperty("personType")
        @Field(type = FieldType.Keyword, index = false)
        private String personType;

        /** Collection of supplier types. */
        @JsonProperty("supplierTypes")
        @Field(type = FieldType.Keyword, index = false)
        private List<String> supplierTypes = new ArrayList<>();

        /** Identity type reference. */
        @JsonProperty("identityTypeReference")
        @Field(type = FieldType.Keyword, index = false)
        private String identityTypeReference;

        /** Business register identifier. */
        @JsonProperty("businessRegisterId")
        @Field(type = FieldType.Keyword, index = false)
        private String businessRegisterId;

        /** Organisation identifier. */
        @JsonProperty("organisationIdentifier")
        @Field(type = FieldType.Keyword, index = false)
        private String organisationIdentifier;


        @JsonProperty("blocked")
        @Field(type = FieldType.Keyword, index = false)
        private String blocked;



        public String getOrganisationTitle()
        {
            return organisationTitle;
        }

        public void setOrganisationTitle(String organisationTitle)
        {
            this.organisationTitle = organisationTitle;
        }

        public String getOrganisationName()
        {
            return organisationName;
        }

        public void setOrganisationName(String organisationName)
        {
            this.organisationName = organisationName;
        }

        public String getFirstName()
        {
            return firstName;
        }

        public void setFirstName(String firstName)
        {
            this.firstName = firstName;
        }

        public String getLastName()
        {
            return lastName;
        }

        public void setLastName(String lastName)
        {
            this.lastName = lastName;
        }

        public String getWebsite()
        {
            return website;
        }

        public void setWebsite(String website)
        {
            this.website = website;
        }

        public Long getCloseDate()
        {
            return closeDate;
        }

        @JsonSetter("closeDate")
        public void setCloseDate(Object closeDate)
        {
            if (closeDate instanceof List<?> list)
            {
                this.closeDate = toEpochList(list);
            }
            else if (closeDate instanceof Number number)
            {
                this.closeDate = number.longValue();
            }
            else
            {
                this.closeDate = null;
            }
        }

        private Long toEpochList(List<?> dateParts)
        {
            if (dateParts == null || dateParts.isEmpty())
            {
                return null;
            }
            Integer yearValue = valueAt(dateParts, 0);
            if (yearValue == null)
            {
                return null;
            }
            int month = Optional.ofNullable(valueAt(dateParts, 1)).filter(value -> value > 0).orElse(1);
            int day = Optional.ofNullable(valueAt(dateParts, 2)).filter(value -> value > 0).orElse(1);
            try
            {
                return LocalDate.of(yearValue, month, day).atStartOfDay().toEpochSecond(ZoneOffset.UTC);
            }
            catch (Exception e)
            {
                return null;
            }
        }

        private Integer valueAt(List<?> parts, int index)
        {
            if (index >= parts.size())
            {
                return null;
            }
            Object value = parts.get(index);
            if (value instanceof Number number)
            {
                return number.intValue();
            }
            return null;
        }

        public String getCloseStatus()
        {
            return closeStatus;
        }

        public void setCloseStatus(String closeStatus)
        {
            this.closeStatus = closeStatus;
        }

        public Boolean getIsClosed()
        {
            return isClosed;
        }

        public void setIsClosed(Boolean isClosed)
        {
            this.isClosed = isClosed;
        }

        public String getGuid()
        {
            return guid;
        }

        public void setGuid(String guid)
        {
            this.guid = guid;
        }

        public String getPersonType()
        {
            return personType;
        }

        public void setPersonType(String personType)
        {
            this.personType = personType;
        }

        public List<String> getSupplierTypes()
        {
            return supplierTypes;
        }

        public void setSupplierTypes(List<String> supplierTypes)
        {
            this.supplierTypes = Optional.ofNullable(supplierTypes).map(ArrayList::new).orElseGet(ArrayList::new);
        }

        public String getIdentityTypeReference()
        {
            return identityTypeReference;
        }

        public void setIdentityTypeReference(String identityTypeReference)
        {
            this.identityTypeReference = identityTypeReference;
        }

        public String getBusinessRegisterId()
        {
            return businessRegisterId;
        }

        public void setBusinessRegisterId(String businessRegisterId)
        {
            this.businessRegisterId = businessRegisterId;
        }

        public String getOrganisationIdentifier()
        {
            return organisationIdentifier;
        }

        public void setOrganisationIdentifier(String organisationIdentifier)
        {
            this.organisationIdentifier = organisationIdentifier;
        }
    }

    /**
     * Representation of the additional details section.
     */
    public static class AdditionalDetails implements Serializable
    {
        @Serial
        private static final long serialVersionUID = -5701075728511738931L;


        public AdditionalDetails() {
			super();
		}

		/** GTIN identifier present in additional details. */
        @Field(type = FieldType.Keyword, index = false)
        private String gtinIdentifier;

        /** Other entries contained within the additional details section. */
        @Field(type = FieldType.Object, enabled = false)
        private  Map<String, Object> attributes = new HashMap<>();

        public String getGtinIdentifier()
        {
            return gtinIdentifier;
        }

        public void setGtinIdentifier(String gtinIdentifier)
        {
            this.gtinIdentifier = gtinIdentifier;
        }

        public Map<String, Object> getAttributes()
        {
            return attributes;
        }

        @JsonAnySetter
        public void addAttribute(String name, Object value)
        {
            if ("gtinIdentifier".equals(name))
            {
                setGtinIdentifier(Objects.toString(value, null));
            }
            else
            {
                attributes.put(name, value);
            }
        }
    }
}
