
server:
  port: 8081


logging:
    level:
      ROOT: warn
      org.open4goods: warn
      GENERIC_LOGGER: warn

# The key to provide to get ADMIN_ROLE
adminKey: open4goods

  
crawlerKeys:
  - open4goods

verticalsFolder: "/home/goulven/git/open4goods-config/verticals/"
datasourcesfolder: "/home/goulven/git/open4goods-config/datasources/"
dedicatedLoggerToConsole: true

langchain4j:
  open-ai:
    chat-model:
      api-key: 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
      model-name: gpt-4
      temperature: 0.0
      timeout: PT60S
      log-requests: false
      log-responses: false
      
      

spring:

  elasticsearch:
      uris: nudger.fr:9200
      username: elastic
      password: xZRi69qwiv6u5M

  data:
    redis:
      database: 0
      host: nudger.fr
      port: 6379  
        
  thymeleaf:
      cache: false

#rootFolder: /opt/open4goods/      


######################################
# The locally embeded crawler node
#####################################        
fetcherProperties:
  feedConfigs:

    awin:
      catalogUrl: https://productdata.awin.com/datafeed/list/apikey/f3fe5d60a3668a0256f1dcdf9956ac03
      # To map catalog key and datasource name 
      datasourceKeyAttribute: "Advertiser Name"
      datasourceFeedNameAttribute: "Feed Name"
      datasourceUrlAttribute: "URL"
      datasourceRegionAttribute: "Primary Region"   
      datasourceLanguageAttribute: "Language"   
      filterAttributes:
         '[Membership Status]': "active"            
      defaultCsvSeparator: ","
      defaultCsvQuoteDelimiter: "\""
      defaultCsvProperties:
        csvSeparator: ','
        csvQuoteChar: '"'
        currency: EUR
        gzip: true
        referentiel:
          BRAND: 
           - brand_name
           - brand
          MODEL: 
           - mpn
          GTIN: 
           - ean
           - gtin
           - product_GTIN
           - codebarre
    
        name: product_name
        affiliatedUrl: aw_deep_link
        url: aw_deep_link
        description:
          - description
          - short_description
        productState: 
          - condition
        productTags:
          - merchant_product_category_path
        price: 
         - search_price
         - price
        inStock: 
          - in_stock
          - stock_status 
          - availability
           
      
    effiliation:
      catalogUrl: https://docs.google.com/spreadsheets/d/e/2PACX-1vS1oLLCJFCJyo-zJ5c4YT0g7E5SOcnKbBwchndKCRU_jbpXZOKasNEjh4po-qr8_E9TaDi4BCXnuOxF/pub?gid=0&single=true&output=csv
      # To map catalog key and datasource name 
      datasourceKeyAttribute: "Programme"
      datasourceUrlAttribute: "URL"      
      datasourceFeedNameAttribute: "Feed Name"
      excludeFeedKeyContains: 
        -"standby"
        -"stand by"
      defaultCsvSeparator: ","
#      defaultCsvQuoteDelimiter: "\""      
      defaultCsvProperties:
        csvSeparator: ';'
#        csvQuoteChar: '"'
        currency: EUR
        gzip: false
        referentiel:
          BRAND: 
           - brand_name
           - brand
          MODEL: 
           - mpn
          GTIN: 
           - ean
           - gtin
           - product_GTIN
           - codebarre
    
        name: title
        affiliatedUrl: link
        url: link
        description:
          - description
          - short_description
        productState: 
          - condition
        price: 
         - price
         - search_price
        inStock: 
          - in_stock
          - stock_status
          - availability 
  

  apiKey: open4goods
  concurrentFetcherTask: 4
  apiSynchConfig:
    nodeName: localNode
#    TODO : Review the incode shortcut (no http calls) work
    nodeUrl: http://localhost:8081  
#  alertingConfig:
##    mailTo: 
#    mailSubject: api@capsule





             