spring:
  datasource:
    url: jdbc:h2:mem:nudgerapidb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  docker:
    compose:
      enabled: false
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 8081

open4goods:
  scheduling:
    enabled: false

# Folder where work data will be store
rootFolder: ./
datasourcesfolder: "./datasources/"

api:
  backup:
    xwiki-backup-file: ${XWIKI_XAR_PATH:./.local/backup/xwiki-backup.xar}
    data-backup-folder: ${PRODUCT_BACKUP_SOURCE_URI:./.local/backup}
    import-product-path: ${O4G_LOCAL_DATA_ROOT:./.local/data}/import
    copy-page-size: 5000
    copy-bulk-size: 500
    copy-threads: 2
    copy-queue-size: 25

# The key to provide to get ADMIN_ROLE
adminKey: open4goods


xwiki:
  baseUrl: http://localhost:8080/xwiki
  password: mock
  username: mock
