# Folder where work data will be store
rootFolder: ./
datasourcesfolder: "./datasources/"

# Port the server will be running on
server:
  port: 8081

# Logging configuration
logging:
    level:
      ROOT: info
      org.open4goods: info
      GENERIC_LOGGER: info

# The key to provide to get ADMIN_ROLE
adminKey: open4goods

  
crawlerKeys:
  - open4goods


spring:
  thymeleaf:
      cache: false


######################################
# The locally embeded crawler node
#####################################        
fetcherProperties:
  apiKey: open4goods
  concurrentFetcherTask: 2
  apiSynchConfig:
    nodeName: localNode
    nodeUrl: http://localhost:8081  


elasticsearch.username: 
elasticsearch.password:  
elasticsearch.host: 127.0.0.1
             
