/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XwikiContentBlocDto
 */
export interface XwikiContentBlocDto {
    /**
     *
     * @type {string}
     * @memberof XwikiContentBlocDto
     */
    blocId?: string;
    /**
     *
     * @type {string}
     * @memberof XwikiContentBlocDto
     */
    htmlContent?: string;
    /**
     *
     * @type {string}
     * @memberof XwikiContentBlocDto
     */
    editLink?: string;
    /**
     *
     * @type {string}
     * @memberof XwikiContentBlocDto
     */
    resolvedLanguage?: string;
}

/**
 * Check if a given object implements the XwikiContentBlocDto interface.
 */
export function instanceOfXwikiContentBlocDto(value: object): value is XwikiContentBlocDto {
    return true;
}

export function XwikiContentBlocDtoFromJSON(json: any): XwikiContentBlocDto {
    return XwikiContentBlocDtoFromJSONTyped(json, false);
}

export function XwikiContentBlocDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): XwikiContentBlocDto {
    if (json == null) {
        return json;
    }
    return {
        
        'blocId': json['blocId'] == null ? undefined : json['blocId'],
        'htmlContent': json['htmlContent'] == null ? undefined : json['htmlContent'],
        'editLink': json['editLink'] == null ? undefined : json['editLink'],
        'resolvedLanguage': json['resolvedLanguage'] == null ? undefined : json['resolvedLanguage'],
    };
}

export function XwikiContentBlocDtoToJSON(json: any): XwikiContentBlocDto {
    return XwikiContentBlocDtoToJSONTyped(json, false);
}

export function XwikiContentBlocDtoToJSONTyped(value?: XwikiContentBlocDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blocId': value['blocId'],
        'htmlContent': value['htmlContent'],
        'editLink': value['editLink'],
        'resolvedLanguage': value['resolvedLanguage'],
    };
}

