import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const APP_DIR = path.resolve(__dirname, '../app')
const OUTPUT_FILE = path.resolve(__dirname, '../app/config/icons.ts')

// Recursive file search
function getFiles(dir) {
  let results = []
  const list = fs.readdirSync(dir)
  list.forEach(file => {
    file = path.join(dir, file)
    const stat = fs.statSync(file)
    if (stat && stat.isDirectory()) {
      results = results.concat(getFiles(file))
    } else {
      if (
        file.endsWith('.vue') ||
        file.endsWith('.ts') ||
        file.endsWith('.js')
      ) {
        results.push(file)
      }
    }
  })
  return results
}

const files = getFiles(APP_DIR)
const iconSet = new Set()
const iconRegex = /mdi-[a-z0-9-]+/g

console.log(`Scanning ${files.length} files for mdi- icons...`)

files.forEach(file => {
  const content = fs.readFileSync(file, 'utf-8')
  const matches = content.match(iconRegex)
  if (matches) {
    matches.forEach(m => iconSet.add(m))
  }
})

// Add some defaults that might be used internally by Vuetify or common fallbacks
iconSet.add('mdi-checkbox-marked')
iconSet.add('mdi-checkbox-blank-outline')
iconSet.add('mdi-radiobox-marked')
iconSet.add('mdi-radiobox-blank')
iconSet.add('mdi-menu-down')
iconSet.add('mdi-menu-up')
iconSet.add('mdi-chevron-left')
iconSet.add('mdi-chevron-right')
// Close/delete/clear icons often used in inputs
iconSet.add('mdi-close')
iconSet.add('mdi-close-circle')
iconSet.add('mdi-close-circle-outline')
iconSet.add('mdi-star')
iconSet.add('mdi-star-half')
iconSet.add('mdi-star-outline')

const sortedIcons = Array.from(iconSet).sort()
console.log(`Found ${sortedIcons.length} unique icons.`)

// Convert kebab-case to camelCase and prefix with 'mdi' if not already (logic check: inputs are mdi-foo)
// Actually inputs are 'mdi-foo-bar'.
// Helper: mdi-foo-bar -> mdiFooBar
function toCamel(s) {
  return s.replace(/-([a-z0-9])/g, g => g[1].toUpperCase())
}

// Generate file content
const imports = []
const internalMap = []

sortedIcons.forEach(iconName => {
  const varName = toCamel(iconName)
  imports.push(varName)
  internalMap.push(`  '${iconName}': ${varName},`)
})

const fileContent = `// This file is auto-generated by scripts/generate-icons.js
// Do not edit manually if you plan to re-run the script.
// Add manual icons to the 'manualIcons' array if strictly necessary.

import {
  ${imports.join(',\n  ')}
} from '@mdi/js'

export const icons: Record<string, string> = {
${internalMap.join('\n')}
}

// Helper to get icon by string name (useful for dynamic icons from API)
export function getIcon(name: string): string | undefined {
  return icons[name]
}
`

fs.writeFileSync(OUTPUT_FILE, fileContent)
console.log(`Generated ${OUTPUT_FILE}`)
