server:
  port: 8085
  
xwiki:
    username: nudger
    password: nudger 
    baseUrl: https://wiki.nudger.fr

spring:
    application:
      name: nudger-admin

    mail:
      host: smtp.gmail.com
      port: 587
      username: "web.equitable@gmail.com"
      password: "hcmc zcyd xypo kalb"
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

management:
    security:
      enabled: false		
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS