server:
  port: 8086
spring:
  elasticsearch:
    uris: http://localhost:${O4G_PORT_ELASTICSEARCH:9200}
open4goods:
  scheduling:
    enabled: false
feedback:
  github:
    enabled: false
front:
  cache:
    path: ${O4G_LOCAL_DATA_ROOT:./.local/data}/cache/front-api
  resource-root-path: http://localhost:${O4G_PORT_UI:8082}
  security:
    cors-allowed-hosts: http://localhost:${O4G_PORT_FRONTEND:3000},http://localhost:${O4G_PORT_B2B_FRONTEND:3001}
  exposed-docs:
    base-url: http://localhost:${O4G_PORT_EXPOSED_DOCS:8088}
  geocode:
    base-url: http://localhost:${O4G_PORT_GEOCODE:8089}
  google-indexation:
    enabled: false
open-data-config:
  generation-enabled: false
