package org.open4goods.nudgerfrontapi.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.data.elasticsearch.repository.config.EnableElasticsearchRepositories;

/**
 * Configuration enabling Elasticsearch repositories required to persist contribution votes
 * generated by affiliation redirects.
 */
@Configuration
@Profile("!local")
@EnableElasticsearchRepositories(basePackages = "org.open4goods.services.contribution.repository")
public class ContributionRepositoryConfig {
}
