/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AffiliationPartnerDto
 */
export interface AffiliationPartnerDto {
    /**
     * Stable identifier of the partner.
     * @type {string}
     * @memberof AffiliationPartnerDto
     */
    id?: string;
    /**
     * Human readable partner name.
     * @type {string}
     * @memberof AffiliationPartnerDto
     */
    name?: string;
    /**
     * Landing page URL used for affiliation redirection.
     * @type {string}
     * @memberof AffiliationPartnerDto
     */
    affiliationLink?: string;
    /**
     * Public portal URL of the partner.
     * @type {string}
     * @memberof AffiliationPartnerDto
     */
    portalUrl?: string;
    /**
     * Computed logo URL served by the front API.
     * @type {string}
     * @memberof AffiliationPartnerDto
     */
    logoUrl?: string;
    /**
     * Computed favicon URL served by the front API.
     * @type {string}
     * @memberof AffiliationPartnerDto
     */
    faviconUrl?: string;
    /**
     * ISO 3166-1 alpha-2 country codes where the partner operates.
     * @type {Array<string>}
     * @memberof AffiliationPartnerDto
     */
    countryCodes?: Array<string>;
}

/**
 * Check if a given object implements the AffiliationPartnerDto interface.
 */
export function instanceOfAffiliationPartnerDto(value: object): value is AffiliationPartnerDto {
    return true;
}

export function AffiliationPartnerDtoFromJSON(json: any): AffiliationPartnerDto {
    return AffiliationPartnerDtoFromJSONTyped(json, false);
}

export function AffiliationPartnerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffiliationPartnerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'affiliationLink': json['affiliationLink'] == null ? undefined : json['affiliationLink'],
        'portalUrl': json['portalUrl'] == null ? undefined : json['portalUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'faviconUrl': json['faviconUrl'] == null ? undefined : json['faviconUrl'],
        'countryCodes': json['countryCodes'] == null ? undefined : json['countryCodes'],
    };
}

export function AffiliationPartnerDtoToJSON(json: any): AffiliationPartnerDto {
    return AffiliationPartnerDtoToJSONTyped(json, false);
}

export function AffiliationPartnerDtoToJSONTyped(value?: AffiliationPartnerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'affiliationLink': value['affiliationLink'],
        'portalUrl': value['portalUrl'],
        'logoUrl': value['logoUrl'],
        'faviconUrl': value['faviconUrl'],
        'countryCodes': value['countryCodes'],
    };
}

