/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response after submitting an agent request
 * @export
 * @interface AgentRequestResponseDto
 */
export interface AgentRequestResponseDto {
    /**
     * ID of the created issue
     * @type {string}
     * @memberof AgentRequestResponseDto
     */
    issueId?: string;
    /**
     * Number of the created issue
     * @type {number}
     * @memberof AgentRequestResponseDto
     */
    issueNumber?: number;
    /**
     * URL of the created issue
     * @type {string}
     * @memberof AgentRequestResponseDto
     */
    issueUrl?: string;
    /**
     * Current workflow state
     * @type {string}
     * @memberof AgentRequestResponseDto
     */
    workflowState?: string;
    /**
     * Preview URL (if available)
     * @type {string}
     * @memberof AgentRequestResponseDto
     */
    previewUrl?: string;
    /**
     * Visibility of the prompt
     * @type {string}
     * @memberof AgentRequestResponseDto
     */
    promptVisibility?: AgentRequestResponseDtoPromptVisibilityEnum;
    /**
     * Agent template identifier
     * @type {string}
     * @memberof AgentRequestResponseDto
     */
    promptTemplateId?: string;
    /**
     * Prompt variant identifier
     * @type {string}
     * @memberof AgentRequestResponseDto
     */
    promptVariantId?: string;
}


/**
 * @export
 */
export const AgentRequestResponseDtoPromptVisibilityEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type AgentRequestResponseDtoPromptVisibilityEnum = typeof AgentRequestResponseDtoPromptVisibilityEnum[keyof typeof AgentRequestResponseDtoPromptVisibilityEnum];


/**
 * Check if a given object implements the AgentRequestResponseDto interface.
 */
export function instanceOfAgentRequestResponseDto(value: object): value is AgentRequestResponseDto {
    return true;
}

export function AgentRequestResponseDtoFromJSON(json: any): AgentRequestResponseDto {
    return AgentRequestResponseDtoFromJSONTyped(json, false);
}

export function AgentRequestResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentRequestResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'issueId': json['issueId'] == null ? undefined : json['issueId'],
        'issueNumber': json['issueNumber'] == null ? undefined : json['issueNumber'],
        'issueUrl': json['issueUrl'] == null ? undefined : json['issueUrl'],
        'workflowState': json['workflowState'] == null ? undefined : json['workflowState'],
        'previewUrl': json['previewUrl'] == null ? undefined : json['previewUrl'],
        'promptVisibility': json['promptVisibility'] == null ? undefined : json['promptVisibility'],
        'promptTemplateId': json['promptTemplateId'] == null ? undefined : json['promptTemplateId'],
        'promptVariantId': json['promptVariantId'] == null ? undefined : json['promptVariantId'],
    };
}

export function AgentRequestResponseDtoToJSON(json: any): AgentRequestResponseDto {
    return AgentRequestResponseDtoToJSONTyped(json, false);
}

export function AgentRequestResponseDtoToJSONTyped(value?: AgentRequestResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issueId': value['issueId'],
        'issueNumber': value['issueNumber'],
        'issueUrl': value['issueUrl'],
        'workflowState': value['workflowState'],
        'previewUrl': value['previewUrl'],
        'promptVisibility': value['promptVisibility'],
        'promptTemplateId': value['promptTemplateId'],
        'promptVariantId': value['promptVariantId'],
    };
}

