/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { MailTemplateDto } from './MailTemplateDto'
import {
  MailTemplateDtoFromJSON,
  MailTemplateDtoFromJSONTyped,
  MailTemplateDtoToJSON,
  MailTemplateDtoToJSONTyped,
} from './MailTemplateDto'
import type { PromptTemplateDto } from './PromptTemplateDto'
import {
  PromptTemplateDtoFromJSON,
  PromptTemplateDtoFromJSONTyped,
  PromptTemplateDtoToJSON,
  PromptTemplateDtoToJSONTyped,
} from './PromptTemplateDto'
import type { AgentAttributeDto } from './AgentAttributeDto'
import {
  AgentAttributeDtoFromJSON,
  AgentAttributeDtoFromJSONTyped,
  AgentAttributeDtoToJSON,
  AgentAttributeDtoToJSONTyped,
} from './AgentAttributeDto'

/**
 * Configuration template for an agent
 * @export
 * @interface AgentTemplateDto
 */
export interface AgentTemplateDto {
  /**
   * Unique identifier of the agent
   * @type {string}
   * @memberof AgentTemplateDto
   */
  id?: string
  /**
   * Localized name of the agent
   * @type {string}
   * @memberof AgentTemplateDto
   */
  name?: string
  /**
   * Localized description
   * @type {string}
   * @memberof AgentTemplateDto
   */
  description?: string
  /**
   * Icon identifier (MDI)
   * @type {string}
   * @memberof AgentTemplateDto
   */
  icon?: string
  /**
   * Prompt template text
   * @type {string}
   * @memberof AgentTemplateDto
   */
  promptTemplates?: Array<PromptTemplateDto>
  /**
   * Associated tags
   * @type {Array<string>}
   * @memberof AgentTemplateDto
   */
  tags?: Array<string>
  /**
   * Allowed roles to access this agent
   * @type {Array<string>}
   * @memberof AgentTemplateDto
   */
  allowedRoles?: Array<string>
  /**
   * Whether the prompt history is public
   * @type {boolean}
   * @memberof AgentTemplateDto
   */
  publicPromptHistory?: boolean
  /**
   * Whether user can edit the selected prompt template
   * @type {boolean}
   * @memberof AgentTemplateDto
   */
  allowTemplateEditing?: boolean
  /**
   * Mailto template configuration
   * @type {MailTemplateDto}
   * @memberof AgentTemplateDto
   */
  mailTemplate?: MailTemplateDto
  /**
   * Custom attributes for the agent
   * @type {Array<AgentAttributeDto>}
   * @memberof AgentTemplateDto
   */
  attributes?: Array<AgentAttributeDto>
}

/**
 * Check if a given object implements the AgentTemplateDto interface.
 */
export function instanceOfAgentTemplateDto(
  value: object
): value is AgentTemplateDto {
  return true
}

export function AgentTemplateDtoFromJSON(json: any): AgentTemplateDto {
  return AgentTemplateDtoFromJSONTyped(json, false)
}

export function AgentTemplateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AgentTemplateDto {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    icon: json['icon'] == null ? undefined : json['icon'],
    promptTemplates:
      json['promptTemplates'] == null
        ? undefined
        : (json['promptTemplates'] as Array<any>).map(
            PromptTemplateDtoFromJSON
          ),
    tags: json['tags'] == null ? undefined : json['tags'],
    allowedRoles:
      json['allowedRoles'] == null ? undefined : json['allowedRoles'],
    publicPromptHistory:
      json['publicPromptHistory'] == null
        ? undefined
        : json['publicPromptHistory'],
    allowTemplateEditing:
      json['allowTemplateEditing'] == null
        ? undefined
        : json['allowTemplateEditing'],
    mailTemplate:
      json['mailTemplate'] == null
        ? undefined
        : MailTemplateDtoFromJSON(json['mailTemplate']),
    attributes:
      json['attributes'] == null
        ? undefined
        : (json['attributes'] as Array<any>).map(AgentAttributeDtoFromJSON),
  }
}

export function AgentTemplateDtoToJSON(json: any): AgentTemplateDto {
  return AgentTemplateDtoToJSONTyped(json, false)
}

export function AgentTemplateDtoToJSONTyped(
  value?: AgentTemplateDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    name: value['name'],
    description: value['description'],
    icon: value['icon'],
    promptTemplates:
      value['promptTemplates'] == null
        ? undefined
        : (value['promptTemplates'] as Array<any>).map(PromptTemplateDtoToJSON),
    tags: value['tags'],
    allowedRoles: value['allowedRoles'],
    publicPromptHistory: value['publicPromptHistory'],
    allowTemplateEditing: value['allowTemplateEditing'],
    mailTemplate: MailTemplateDtoToJSON(value['mailTemplate']),
    attributes:
      value['attributes'] == null
        ? undefined
        : (value['attributes'] as Array<any>).map(AgentAttributeDtoToJSON),
  }
}
