/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AggregationMetadata
 */
export interface AggregationMetadata {
    /**
     * Preferred number of buckets when building histogram aggregations.
     * @type {number}
     * @memberof AggregationMetadata
     */
    buckets?: number;
    /**
     * Preferred interval size for numeric range aggregations.
     * @type {number}
     * @memberof AggregationMetadata
     */
    interval?: number;
}

/**
 * Check if a given object implements the AggregationMetadata interface.
 */
export function instanceOfAggregationMetadata(value: object): value is AggregationMetadata {
    return true;
}

export function AggregationMetadataFromJSON(json: any): AggregationMetadata {
    return AggregationMetadataFromJSONTyped(json, false);
}

export function AggregationMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregationMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'buckets': json['buckets'] == null ? undefined : json['buckets'],
        'interval': json['interval'] == null ? undefined : json['interval'],
    };
}

export function AggregationMetadataToJSON(json: any): AggregationMetadata {
    return AggregationMetadataToJSONTyped(json, false);
}

export function AggregationMetadataToJSONTyped(value?: AggregationMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buckets': value['buckets'],
        'interval': value['interval'],
    };
}

