/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiAttribute
 */
export interface AiAttribute {
    /**
     * 
     * @type {string}
     * @memberof AiAttribute
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AiAttribute
     */
    value: string;
    /**
     * 
     * @type {number}
     * @memberof AiAttribute
     */
    number: number;
}

/**
 * Check if a given object implements the AiAttribute interface.
 */
export function instanceOfAiAttribute(value: object): value is AiAttribute {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    return true;
}

export function AiAttributeFromJSON(json: any): AiAttribute {
    return AiAttributeFromJSONTyped(json, false);
}

export function AiAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiAttribute {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
        'number': json['number'],
    };
}

export function AiAttributeToJSON(json: any): AiAttribute {
    return AiAttributeToJSONTyped(json, false);
}

export function AiAttributeToJSONTyped(value?: AiAttribute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'number': value['number'],
    };
}

