/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiReviewSourceDto } from './AiReviewSourceDto';
import {
    AiReviewSourceDtoFromJSON,
    AiReviewSourceDtoFromJSONTyped,
    AiReviewSourceDtoToJSON,
    AiReviewSourceDtoToJSONTyped,
} from './AiReviewSourceDto';
import type { AiReviewAttributeDto } from './AiReviewAttributeDto';
import {
    AiReviewAttributeDtoFromJSON,
    AiReviewAttributeDtoFromJSONTyped,
    AiReviewAttributeDtoToJSON,
    AiReviewAttributeDtoToJSONTyped,
} from './AiReviewAttributeDto';

/**
 * 
 * @export
 * @interface AiReviewDto
 */
export interface AiReviewDto {
    /**
     * Detailed description of the product generated by AI
     * @type {string}
     * @memberof AiReviewDto
     */
    description?: string;
    /**
     * Short teaser presenting the product
     * @type {string}
     * @memberof AiReviewDto
     */
    shortDescription?: string;
    /**
     * Medium length title summarising the review
     * @type {string}
     * @memberof AiReviewDto
     */
    mediumTitle?: string;
    /**
     * Short title highlighting the product
     * @type {string}
     * @memberof AiReviewDto
     */
    shortTitle?: string;
    /**
     * Technical analysis extracted from trustworthy sources (Legacy - equivalent to Intermediate)
     * @type {string}
     * @memberof AiReviewDto
     */
    technicalReview?: string;
    /**
     * Technical analysis for novice users
     * @type {string}
     * @memberof AiReviewDto
     */
    technicalReviewNovice?: string;
    /**
     * Technical analysis for intermediate users
     * @type {string}
     * @memberof AiReviewDto
     */
    technicalReviewIntermediate?: string;
    /**
     * Technical analysis for advanced users
     * @type {string}
     * @memberof AiReviewDto
     */
    technicalReviewAdvanced?: string;
    /**
     * Short technical summary in 2-3 sentences
     * @type {string}
     * @memberof AiReviewDto
     */
    technicalShortReview?: string;
    /**
     * Ecological assessment derived from the available documentation (Legacy - equivalent to Intermediate)
     * @type {string}
     * @memberof AiReviewDto
     */
    ecologicalReview?: string;
    /**
     * Ecological assessment for novice users
     * @type {string}
     * @memberof AiReviewDto
     */
    ecologicalReviewNovice?: string;
    /**
     * Ecological assessment for intermediate users
     * @type {string}
     * @memberof AiReviewDto
     */
    ecologicalReviewIntermediate?: string;
    /**
     * Ecological assessment for advanced users
     * @type {string}
     * @memberof AiReviewDto
     */
    ecologicalReviewAdvanced?: string;
    /**
     * Community feedback summary for novice users
     * @type {string}
     * @memberof AiReviewDto
     */
    communityReviewNovice?: string;
    /**
     * Community feedback summary for intermediate users
     * @type {string}
     * @memberof AiReviewDto
     */
    communityReviewIntermediate?: string;
    /**
     * Community feedback summary for advanced users
     * @type {string}
     * @memberof AiReviewDto
     */
    communityReviewAdvanced?: string;
    /**
     * Concise summary mixing technical and ecological highlights
     * @type {string}
     * @memberof AiReviewDto
     */
    summary?: string;
    /**
     * List of pros emphasised by the AI review
     * @type {Array<string>}
     * @memberof AiReviewDto
     */
    pros?: Array<string>;
    /**
     * List of cons emphasised by the AI review
     * @type {Array<string>}
     * @memberof AiReviewDto
     */
    cons?: Array<string>;
    /**
     * Sources cited to support the AI review
     * @type {Array<AiReviewSourceDto>}
     * @memberof AiReviewDto
     */
    sources?: Array<AiReviewSourceDto>;
    /**
     * Attributes extracted from the sources and referenced inside the review
     * @type {Array<AiReviewAttributeDto>}
     * @memberof AiReviewDto
     */
    attributes?: Array<AiReviewAttributeDto>;
    /**
     * Assessment of the data quality available for the product
     * @type {string}
     * @memberof AiReviewDto
     */
    dataQuality?: string;
    /**
     * Short technical summary of the product (max 20 words)
     * @type {string}
     * @memberof AiReviewDto
     */
    technicalOneline?: string;
    /**
     * Short ecological summary of the product (max 20 words)
     * @type {string}
     * @memberof AiReviewDto
     */
    ecologicalOneline?: string;
    /**
     * Short community summary of the product (max 20 words)
     * @type {string}
     * @memberof AiReviewDto
     */
    communityOneline?: string;
}

/**
 * Check if a given object implements the AiReviewDto interface.
 */
export function instanceOfAiReviewDto(value: object): value is AiReviewDto {
    return true;
}

export function AiReviewDtoFromJSON(json: any): AiReviewDto {
    return AiReviewDtoFromJSONTyped(json, false);
}

export function AiReviewDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiReviewDto {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'shortDescription': json['shortDescription'] == null ? undefined : json['shortDescription'],
        'mediumTitle': json['mediumTitle'] == null ? undefined : json['mediumTitle'],
        'shortTitle': json['shortTitle'] == null ? undefined : json['shortTitle'],
        'technicalReview': json['technicalReview'] == null ? undefined : json['technicalReview'],
        'technicalReviewNovice': json['technicalReviewNovice'] == null ? undefined : json['technicalReviewNovice'],
        'technicalReviewIntermediate': json['technicalReviewIntermediate'] == null ? undefined : json['technicalReviewIntermediate'],
        'technicalReviewAdvanced': json['technicalReviewAdvanced'] == null ? undefined : json['technicalReviewAdvanced'],
        'technicalShortReview': json['technicalShortReview'] == null ? undefined : json['technicalShortReview'],
        'ecologicalReview': json['ecologicalReview'] == null ? undefined : json['ecologicalReview'],
        'ecologicalReviewNovice': json['ecologicalReviewNovice'] == null ? undefined : json['ecologicalReviewNovice'],
        'ecologicalReviewIntermediate': json['ecologicalReviewIntermediate'] == null ? undefined : json['ecologicalReviewIntermediate'],
        'ecologicalReviewAdvanced': json['ecologicalReviewAdvanced'] == null ? undefined : json['ecologicalReviewAdvanced'],
        'communityReviewNovice': json['communityReviewNovice'] == null ? undefined : json['communityReviewNovice'],
        'communityReviewIntermediate': json['communityReviewIntermediate'] == null ? undefined : json['communityReviewIntermediate'],
        'communityReviewAdvanced': json['communityReviewAdvanced'] == null ? undefined : json['communityReviewAdvanced'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'pros': json['pros'] == null ? undefined : json['pros'],
        'cons': json['cons'] == null ? undefined : json['cons'],
        'sources': json['sources'] == null ? undefined : ((json['sources'] as Array<any>).map(AiReviewSourceDtoFromJSON)),
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(AiReviewAttributeDtoFromJSON)),
        'dataQuality': json['dataQuality'] == null ? undefined : json['dataQuality'],
        'technicalOneline': json['technicalOneline'] == null ? undefined : json['technicalOneline'],
        'ecologicalOneline': json['ecologicalOneline'] == null ? undefined : json['ecologicalOneline'],
        'communityOneline': json['communityOneline'] == null ? undefined : json['communityOneline'],
    };
}

export function AiReviewDtoToJSON(json: any): AiReviewDto {
    return AiReviewDtoToJSONTyped(json, false);
}

export function AiReviewDtoToJSONTyped(value?: AiReviewDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'shortDescription': value['shortDescription'],
        'mediumTitle': value['mediumTitle'],
        'shortTitle': value['shortTitle'],
        'technicalReview': value['technicalReview'],
        'technicalReviewNovice': value['technicalReviewNovice'],
        'technicalReviewIntermediate': value['technicalReviewIntermediate'],
        'technicalReviewAdvanced': value['technicalReviewAdvanced'],
        'technicalShortReview': value['technicalShortReview'],
        'ecologicalReview': value['ecologicalReview'],
        'ecologicalReviewNovice': value['ecologicalReviewNovice'],
        'ecologicalReviewIntermediate': value['ecologicalReviewIntermediate'],
        'ecologicalReviewAdvanced': value['ecologicalReviewAdvanced'],
        'communityReviewNovice': value['communityReviewNovice'],
        'communityReviewIntermediate': value['communityReviewIntermediate'],
        'communityReviewAdvanced': value['communityReviewAdvanced'],
        'summary': value['summary'],
        'pros': value['pros'],
        'cons': value['cons'],
        'sources': value['sources'] == null ? undefined : ((value['sources'] as Array<any>).map(AiReviewSourceDtoToJSON)),
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(AiReviewAttributeDtoToJSON)),
        'dataQuality': value['dataQuality'],
        'technicalOneline': value['technicalOneline'],
        'ecologicalOneline': value['ecologicalOneline'],
        'communityOneline': value['communityOneline'],
    };
}

