/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeConfigUnit } from './AttributeConfigUnit';
import {
    AttributeConfigUnitFromJSON,
    AttributeConfigUnitFromJSONTyped,
    AttributeConfigUnitToJSON,
    AttributeConfigUnitToJSONTyped,
} from './AttributeConfigUnit';
import type { AttributeParserConfig } from './AttributeParserConfig';
import {
    AttributeParserConfigFromJSON,
    AttributeParserConfigFromJSONTyped,
    AttributeParserConfigToJSON,
    AttributeParserConfigToJSONTyped,
} from './AttributeParserConfig';

/**
 * 
 * @export
 * @interface AttributeConfig
 */
export interface AttributeConfig {
    /**
     * 
     * @type {string}
     * @memberof AttributeConfig
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeConfig
     */
    faIcon?: string;
    /**
     * 
     * @type {AttributeConfigUnit}
     * @memberof AttributeConfig
     */
    unit?: AttributeConfigUnit;
    /**
     * 
     * @type {AttributeConfigUnit}
     * @memberof AttributeConfig
     */
    name?: AttributeConfigUnit;
    /**
     * 
     * @type {string}
     * @memberof AttributeConfig
     */
    filteringType?: AttributeConfigFilteringTypeEnum;
    /**
     * 
     * @type {Set<string>}
     * @memberof AttributeConfig
     */
    icecatFeaturesIds?: Set<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AttributeConfig
     */
    asScore?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AttributeConfig
     */
    reverseScore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AttributeConfig
     */
    attributeValuesOrdering?: AttributeConfigAttributeValuesOrderingEnum;
    /**
     * 
     * @type {boolean}
     * @memberof AttributeConfig
     */
    attributeValuesReverseOrder?: boolean;
    /**
     * 
     * @type {{ [key: string]: Set<string>; }}
     * @memberof AttributeConfig
     */
    synonyms?: { [key: string]: Set<string>; };
    /**
     * 
     * @type {AttributeParserConfig}
     * @memberof AttributeConfig
     */
    parser?: AttributeParserConfig;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof AttributeConfig
     */
    numericMapping?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AttributeConfig
     */
    mappings?: { [key: string]: string; };
}


/**
 * @export
 */
export const AttributeConfigFilteringTypeEnum = {
    Boolean: 'BOOLEAN',
    Numeric: 'NUMERIC',
    Text: 'TEXT'
} as const;
export type AttributeConfigFilteringTypeEnum = typeof AttributeConfigFilteringTypeEnum[keyof typeof AttributeConfigFilteringTypeEnum];

/**
 * @export
 */
export const AttributeConfigAttributeValuesOrderingEnum = {
    Alpha: 'ALPHA',
    Count: 'COUNT',
    Mapped: 'MAPPED'
} as const;
export type AttributeConfigAttributeValuesOrderingEnum = typeof AttributeConfigAttributeValuesOrderingEnum[keyof typeof AttributeConfigAttributeValuesOrderingEnum];


/**
 * Check if a given object implements the AttributeConfig interface.
 */
export function instanceOfAttributeConfig(value: object): value is AttributeConfig {
    return true;
}

export function AttributeConfigFromJSON(json: any): AttributeConfig {
    return AttributeConfigFromJSONTyped(json, false);
}

export function AttributeConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'faIcon': json['faIcon'] == null ? undefined : json['faIcon'],
        'unit': json['unit'] == null ? undefined : AttributeConfigUnitFromJSON(json['unit']),
        'name': json['name'] == null ? undefined : AttributeConfigUnitFromJSON(json['name']),
        'filteringType': json['filteringType'] == null ? undefined : json['filteringType'],
        'icecatFeaturesIds': json['icecatFeaturesIds'] == null ? undefined : new Set(json['icecatFeaturesIds']),
        'asScore': json['asScore'] == null ? undefined : json['asScore'],
        'reverseScore': json['reverseScore'] == null ? undefined : json['reverseScore'],
        'attributeValuesOrdering': json['attributeValuesOrdering'] == null ? undefined : json['attributeValuesOrdering'],
        'attributeValuesReverseOrder': json['attributeValuesReverseOrder'] == null ? undefined : json['attributeValuesReverseOrder'],
        'synonyms': json['synonyms'] == null ? undefined : json['synonyms'],
        'parser': json['parser'] == null ? undefined : AttributeParserConfigFromJSON(json['parser']),
        'numericMapping': json['numericMapping'] == null ? undefined : json['numericMapping'],
        'mappings': json['mappings'] == null ? undefined : json['mappings'],
    };
}

export function AttributeConfigToJSON(json: any): AttributeConfig {
    return AttributeConfigToJSONTyped(json, false);
}

export function AttributeConfigToJSONTyped(value?: AttributeConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'faIcon': value['faIcon'],
        'unit': AttributeConfigUnitToJSON(value['unit']),
        'name': AttributeConfigUnitToJSON(value['name']),
        'filteringType': value['filteringType'],
        'icecatFeaturesIds': value['icecatFeaturesIds'] == null ? undefined : Array.from(value['icecatFeaturesIds'] as Set<any>),
        'asScore': value['asScore'],
        'reverseScore': value['reverseScore'],
        'attributeValuesOrdering': value['attributeValuesOrdering'],
        'attributeValuesReverseOrder': value['attributeValuesReverseOrder'],
        'synonyms': value['synonyms'],
        'parser': AttributeParserConfigToJSON(value['parser']),
        'numericMapping': value['numericMapping'],
        'mappings': value['mappings'],
    };
}

