/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AuthTokensDto
 */
export interface AuthTokensDto {
  /**
   * JWT access token minted for the requested domainLanguage (localisation pending).
   * @type {string}
   * @memberof AuthTokensDto
   */
  accessToken?: string
  /**
   * JWT refresh token minted for the requested domainLanguage (localisation pending).
   * @type {string}
   * @memberof AuthTokensDto
   */
  refreshToken?: string
}

/**
 * Check if a given object implements the AuthTokensDto interface.
 */
export function instanceOfAuthTokensDto(value: object): value is AuthTokensDto {
  return true
}

export function AuthTokensDtoFromJSON(json: any): AuthTokensDto {
  return AuthTokensDtoFromJSONTyped(json, false)
}

export function AuthTokensDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthTokensDto {
  if (json == null) {
    return json
  }
  return {
    accessToken: json['accessToken'] == null ? undefined : json['accessToken'],
    refreshToken:
      json['refreshToken'] == null ? undefined : json['refreshToken'],
  }
}

export function AuthTokensDtoToJSON(json: any): AuthTokensDto {
  return AuthTokensDtoToJSONTyped(json, false)
}

export function AuthTokensDtoToJSONTyped(
  value?: AuthTokensDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    accessToken: value['accessToken'],
    refreshToken: value['refreshToken'],
  }
}
