/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A generic sourced fact attached to a company.
 * @export
 * @interface BrandXMeta
 */
export interface BrandXMeta {
    /**
     * Stable key.
     * @type {string}
     * @memberof BrandXMeta
     */
    key?: string;
    /**
     * Fact type.
     * @type {string}
     * @memberof BrandXMeta
     */
    type?: string;
    /**
     * Concise factual value.
     * @type {string}
     * @memberof BrandXMeta
     */
    value?: string;
    /**
     * Source URL.
     * @type {string}
     * @memberof BrandXMeta
     */
    url?: string | null;
    /**
     * Retrieval date (ISO).
     * @type {string}
     * @memberof BrandXMeta
     */
    retrievedAt?: string | null;
    /**
     * Expiry date (ISO).
     * @type {string}
     * @memberof BrandXMeta
     */
    validUntil?: string | null;
    /**
     * Language tag.
     * @type {string}
     * @memberof BrandXMeta
     */
    lang?: string | null;
}

/**
 * Check if a given object implements the BrandXMeta interface.
 */
export function instanceOfBrandXMeta(value: object): value is BrandXMeta {
    return true;
}

export function BrandXMetaFromJSON(json: any): BrandXMeta {
    return BrandXMetaFromJSONTyped(json, false);
}

export function BrandXMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandXMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'url': json['url'] == null ? undefined : json['url'],
        'retrievedAt': json['retrievedAt'] == null ? undefined : json['retrievedAt'],
        'validUntil': json['validUntil'] == null ? undefined : json['validUntil'],
        'lang': json['lang'] == null ? undefined : json['lang'],
    };
}

export function BrandXMetaToJSON(json: any): BrandXMeta {
    return BrandXMetaToJSONTyped(json, false);
}

export function BrandXMetaToJSONTyped(value?: BrandXMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'type': value['type'],
        'value': value['value'],
        'url': value['url'],
        'retrievedAt': value['retrievedAt'],
        'validUntil': value['validUntil'],
        'lang': value['lang'],
    };
}

