/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoreCardinalityDto } from './ScoreCardinalityDto';
import {
    ScoreCardinalityDtoFromJSON,
    ScoreCardinalityDtoFromJSONTyped,
    ScoreCardinalityDtoToJSON,
    ScoreCardinalityDtoToJSONTyped,
} from './ScoreCardinalityDto';

/**
 * 
 * @export
 * @interface CategoryScoreCardinalitiesDto
 */
export interface CategoryScoreCardinalitiesDto {
    /**
     * Absolute cardinality statistics
     * @type {ScoreCardinalityDto}
     * @memberof CategoryScoreCardinalitiesDto
     */
    absolute?: ScoreCardinalityDto;
    /**
     * Relative cardinality statistics
     * @type {ScoreCardinalityDto}
     * @memberof CategoryScoreCardinalitiesDto
     */
    relativ?: ScoreCardinalityDto;
}

/**
 * Check if a given object implements the CategoryScoreCardinalitiesDto interface.
 */
export function instanceOfCategoryScoreCardinalitiesDto(value: object): value is CategoryScoreCardinalitiesDto {
    return true;
}

export function CategoryScoreCardinalitiesDtoFromJSON(json: any): CategoryScoreCardinalitiesDto {
    return CategoryScoreCardinalitiesDtoFromJSONTyped(json, false);
}

export function CategoryScoreCardinalitiesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryScoreCardinalitiesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'absolute': json['absolute'] == null ? undefined : ScoreCardinalityDtoFromJSON(json['absolute']),
        'relativ': json['relativ'] == null ? undefined : ScoreCardinalityDtoFromJSON(json['relativ']),
    };
}

export function CategoryScoreCardinalitiesDtoToJSON(json: any): CategoryScoreCardinalitiesDto {
    return CategoryScoreCardinalitiesDtoToJSONTyped(json, false);
}

export function CategoryScoreCardinalitiesDtoToJSONTyped(value?: CategoryScoreCardinalitiesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'absolute': ScoreCardinalityDtoToJSON(value['absolute']),
        'relativ': ScoreCardinalityDtoToJSON(value['relativ']),
    };
}

