/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoriesStatsDto
 */
export interface CategoriesStatsDto {
    /**
     * Total number of enabled vertical configurations (language agnostic but returned alongside domainLanguage).
     * @type {number}
     * @memberof CategoriesStatsDto
     */
    enabledVerticalConfigs?: number;
    /**
     * Number of affiliation partners available for price comparison.
     * @type {number}
     * @memberof CategoriesStatsDto
     */
    affiliationPartnersCount?: number;
    /**
     * Total number of GTIN items available in the OpenData exports.
     * @type {number}
     * @memberof CategoriesStatsDto
     */
    gtinOpenDataItemsCount?: number;
    /**
     * Total number of ISBN items available in the OpenData exports.
     * @type {number}
     * @memberof CategoriesStatsDto
     */
    isbnOpenDataItemsCount?: number;
    /**
     * Count of recent products with offers, a valid ImpactScore, and not excluded.
     * @type {number}
     * @memberof CategoriesStatsDto
     */
    impactScoreProductsCount?: number;
    /**
     * Count of recent products with offers that are not mapped to any vertical.
     * @type {number}
     * @memberof CategoriesStatsDto
     */
    productsWithoutVerticalCount?: number;
    /**
     * Per-category product counts for recent products with offers, keyed by vertical id.
     * @type {{ [key: string]: number; }}
     * @memberof CategoriesStatsDto
     */
    productsCountByCategory?: { [key: string]: number; };
    /**
     * Sum of product counts across enabled categories.
     * @type {number}
     * @memberof CategoriesStatsDto
     */
    productsCountSum?: number;
}

/**
 * Check if a given object implements the CategoriesStatsDto interface.
 */
export function instanceOfCategoriesStatsDto(value: object): value is CategoriesStatsDto {
    return true;
}

export function CategoriesStatsDtoFromJSON(json: any): CategoriesStatsDto {
    return CategoriesStatsDtoFromJSONTyped(json, false);
}

export function CategoriesStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriesStatsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'enabledVerticalConfigs': json['enabledVerticalConfigs'] == null ? undefined : json['enabledVerticalConfigs'],
        'affiliationPartnersCount': json['affiliationPartnersCount'] == null ? undefined : json['affiliationPartnersCount'],
        'gtinOpenDataItemsCount': json['gtinOpenDataItemsCount'] == null ? undefined : json['gtinOpenDataItemsCount'],
        'isbnOpenDataItemsCount': json['isbnOpenDataItemsCount'] == null ? undefined : json['isbnOpenDataItemsCount'],
        'impactScoreProductsCount': json['impactScoreProductsCount'] == null ? undefined : json['impactScoreProductsCount'],
        'productsWithoutVerticalCount': json['productsWithoutVerticalCount'] == null ? undefined : json['productsWithoutVerticalCount'],
        'productsCountByCategory': json['productsCountByCategory'] == null ? undefined : json['productsCountByCategory'],
        'productsCountSum': json['productsCountSum'] == null ? undefined : json['productsCountSum'],
    };
}

export function CategoriesStatsDtoToJSON(json: any): CategoriesStatsDto {
    return CategoriesStatsDtoToJSONTyped(json, false);
}

export function CategoriesStatsDtoToJSONTyped(value?: CategoriesStatsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabledVerticalConfigs': value['enabledVerticalConfigs'],
        'affiliationPartnersCount': value['affiliationPartnersCount'],
        'gtinOpenDataItemsCount': value['gtinOpenDataItemsCount'],
        'isbnOpenDataItemsCount': value['isbnOpenDataItemsCount'],
        'impactScoreProductsCount': value['impactScoreProductsCount'],
        'productsWithoutVerticalCount': value['productsWithoutVerticalCount'],
        'productsCountByCategory': value['productsCountByCategory'],
        'productsCountSum': value['productsCountSum'],
    };
}

