/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoogleCategoryDto } from './GoogleCategoryDto';
import {
    GoogleCategoryDtoFromJSON,
    GoogleCategoryDtoFromJSONTyped,
    GoogleCategoryDtoToJSON,
    GoogleCategoryDtoToJSONTyped,
} from './GoogleCategoryDto';
import type { CategoryBreadcrumbItemDto } from './CategoryBreadcrumbItemDto';
import {
    CategoryBreadcrumbItemDtoFromJSON,
    CategoryBreadcrumbItemDtoFromJSONTyped,
    CategoryBreadcrumbItemDtoToJSON,
    CategoryBreadcrumbItemDtoToJSONTyped,
} from './CategoryBreadcrumbItemDto';
import type { CategoryNavigationDtoChildCategoriesInner } from './CategoryNavigationDtoChildCategoriesInner';
import {
    CategoryNavigationDtoChildCategoriesInnerFromJSON,
    CategoryNavigationDtoChildCategoriesInnerFromJSONTyped,
    CategoryNavigationDtoChildCategoriesInnerToJSON,
    CategoryNavigationDtoChildCategoriesInnerToJSONTyped,
} from './CategoryNavigationDtoChildCategoriesInner';

/**
 * 
 * @export
 * @interface CategoryNavigationDto
 */
export interface CategoryNavigationDto {
    /**
     * Current taxonomy node selected by the caller.
     * @type {GoogleCategoryDto}
     * @memberof CategoryNavigationDto
     */
    category?: GoogleCategoryDto;
    /**
     * Breadcrumb entries starting from the catalog root.
     * @type {Array<CategoryBreadcrumbItemDto>}
     * @memberof CategoryNavigationDto
     */
    breadcrumbs?: Array<CategoryBreadcrumbItemDto>;
    /**
     * Immediate children of the selected node filtered by the presence of verticals downstream.
     * @type {Array<CategoryNavigationDtoChildCategoriesInner>}
     * @memberof CategoryNavigationDto
     */
    childCategories?: Array<CategoryNavigationDtoChildCategoriesInner>;
    /**
     * Descendant nodes exposing a vertical configuration but not already present in childCategories.
     * @type {Array<CategoryNavigationDtoChildCategoriesInner>}
     * @memberof CategoryNavigationDto
     */
    descendantVerticals?: Array<CategoryNavigationDtoChildCategoriesInner>;
}

/**
 * Check if a given object implements the CategoryNavigationDto interface.
 */
export function instanceOfCategoryNavigationDto(value: object): value is CategoryNavigationDto {
    return true;
}

export function CategoryNavigationDtoFromJSON(json: any): CategoryNavigationDto {
    return CategoryNavigationDtoFromJSONTyped(json, false);
}

export function CategoryNavigationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryNavigationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : GoogleCategoryDtoFromJSON(json['category']),
        'breadcrumbs': json['breadcrumbs'] == null ? undefined : ((json['breadcrumbs'] as Array<any>).map(CategoryBreadcrumbItemDtoFromJSON)),
        'childCategories': json['childCategories'] == null ? undefined : ((json['childCategories'] as Array<any>).map(CategoryNavigationDtoChildCategoriesInnerFromJSON)),
        'descendantVerticals': json['descendantVerticals'] == null ? undefined : ((json['descendantVerticals'] as Array<any>).map(CategoryNavigationDtoChildCategoriesInnerFromJSON)),
    };
}

export function CategoryNavigationDtoToJSON(json: any): CategoryNavigationDto {
    return CategoryNavigationDtoToJSONTyped(json, false);
}

export function CategoryNavigationDtoToJSONTyped(value?: CategoryNavigationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': GoogleCategoryDtoToJSON(value['category']),
        'breadcrumbs': value['breadcrumbs'] == null ? undefined : ((value['breadcrumbs'] as Array<any>).map(CategoryBreadcrumbItemDtoToJSON)),
        'childCategories': value['childCategories'] == null ? undefined : ((value['childCategories'] as Array<any>).map(CategoryNavigationDtoChildCategoriesInnerToJSON)),
        'descendantVerticals': value['descendantVerticals'] == null ? undefined : ((value['descendantVerticals'] as Array<any>).map(CategoryNavigationDtoChildCategoriesInnerToJSON)),
    };
}

