/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactRequestDto
 */
export interface ContactRequestDto {
    /**
     * Full name of the person submitting the form.
     * @type {string}
     * @memberof ContactRequestDto
     */
    name: string;
    /**
     * Email address of the sender.
     * @type {string}
     * @memberof ContactRequestDto
     */
    email: string;
    /**
     * Message written by the sender.
     * @type {string}
     * @memberof ContactRequestDto
     */
    message: string;
    /**
     * Token returned by the hCaptcha widget.
     * @type {string}
     * @memberof ContactRequestDto
     */
    hCaptchaResponse: string;
}

/**
 * Check if a given object implements the ContactRequestDto interface.
 */
export function instanceOfContactRequestDto(value: object): value is ContactRequestDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('hCaptchaResponse' in value) || value['hCaptchaResponse'] === undefined) return false;
    return true;
}

export function ContactRequestDtoFromJSON(json: any): ContactRequestDto {
    return ContactRequestDtoFromJSONTyped(json, false);
}

export function ContactRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'message': json['message'],
        'hCaptchaResponse': json['h-captcha-response'],
    };
}

export function ContactRequestDtoToJSON(json: any): ContactRequestDto {
    return ContactRequestDtoToJSONTyped(json, false);
}

export function ContactRequestDtoToJSONTyped(value?: ContactRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'message': value['message'],
        'h-captcha-response': value['hCaptchaResponse'],
    };
}

