/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DescriptionsAggregationConfig
 */
export interface DescriptionsAggregationConfig {
    /**
     * 
     * @type {number}
     * @memberof DescriptionsAggregationConfig
     */
    descriptionsTruncationLength?: number;
    /**
     * 
     * @type {string}
     * @memberof DescriptionsAggregationConfig
     */
    descriptionsTruncationSuffix?: string;
}

/**
 * Check if a given object implements the DescriptionsAggregationConfig interface.
 */
export function instanceOfDescriptionsAggregationConfig(value: object): value is DescriptionsAggregationConfig {
    return true;
}

export function DescriptionsAggregationConfigFromJSON(json: any): DescriptionsAggregationConfig {
    return DescriptionsAggregationConfigFromJSONTyped(json, false);
}

export function DescriptionsAggregationConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescriptionsAggregationConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'descriptionsTruncationLength': json['descriptionsTruncationLength'] == null ? undefined : json['descriptionsTruncationLength'],
        'descriptionsTruncationSuffix': json['descriptionsTruncationSuffix'] == null ? undefined : json['descriptionsTruncationSuffix'],
    };
}

export function DescriptionsAggregationConfigToJSON(json: any): DescriptionsAggregationConfig {
    return DescriptionsAggregationConfigToJSONTyped(json, false);
}

export function DescriptionsAggregationConfigToJSONTyped(value?: DescriptionsAggregationConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'descriptionsTruncationLength': value['descriptionsTruncationLength'],
        'descriptionsTruncationSuffix': value['descriptionsTruncationSuffix'],
    };
}

