/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeocodeResponse } from './GeocodeResponse';
import {
    GeocodeResponseFromJSON,
    GeocodeResponseFromJSONTyped,
    GeocodeResponseToJSON,
    GeocodeResponseToJSONTyped,
} from './GeocodeResponse';

/**
 * 
 * @export
 * @interface DistanceResponse
 */
export interface DistanceResponse {
    /**
     * 
     * @type {GeocodeResponse}
     * @memberof DistanceResponse
     */
    from?: GeocodeResponse;
    /**
     * 
     * @type {GeocodeResponse}
     * @memberof DistanceResponse
     */
    to?: GeocodeResponse;
    /**
     * 
     * @type {number}
     * @memberof DistanceResponse
     */
    distanceKm?: number;
    /**
     * 
     * @type {number}
     * @memberof DistanceResponse
     */
    distanceMeters?: number;
}

/**
 * Check if a given object implements the DistanceResponse interface.
 */
export function instanceOfDistanceResponse(value: object): value is DistanceResponse {
    return true;
}

export function DistanceResponseFromJSON(json: any): DistanceResponse {
    return DistanceResponseFromJSONTyped(json, false);
}

export function DistanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : GeocodeResponseFromJSON(json['from']),
        'to': json['to'] == null ? undefined : GeocodeResponseFromJSON(json['to']),
        'distanceKm': json['distanceKm'] == null ? undefined : json['distanceKm'],
        'distanceMeters': json['distanceMeters'] == null ? undefined : json['distanceMeters'],
    };
}

export function DistanceResponseToJSON(json: any): DistanceResponse {
    return DistanceResponseToJSONTyped(json, false);
}

export function DistanceResponseToJSONTyped(value?: DistanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': GeocodeResponseToJSON(value['from']),
        'to': GeocodeResponseToJSON(value['to']),
        'distanceKm': value['distanceKm'],
        'distanceMeters': value['distanceMeters'],
    };
}

