/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ExposedDocsTreeNodeDto
 */
export interface ExposedDocsTreeNodeDto {
  /**
   * Display name of the node
   * @type {string}
   * @memberof ExposedDocsTreeNodeDto
   */
  name?: string
  /**
   * Path relative to the category root
   * @type {string}
   * @memberof ExposedDocsTreeNodeDto
   */
  path?: string
  /**
   * True when the node represents a directory
   * @type {boolean}
   * @memberof ExposedDocsTreeNodeDto
   */
  directory?: boolean
  /**
   * Child nodes, empty for leaf nodes
   * @type {Array<ExposedDocsTreeNodeDto>}
   * @memberof ExposedDocsTreeNodeDto
   */
  children?: Array<ExposedDocsTreeNodeDto>
}

/**
 * Check if a given object implements the ExposedDocsTreeNodeDto interface.
 */
export function instanceOfExposedDocsTreeNodeDto(
  value: object
): value is ExposedDocsTreeNodeDto {
  return true
}

export function ExposedDocsTreeNodeDtoFromJSON(
  json: any
): ExposedDocsTreeNodeDto {
  return ExposedDocsTreeNodeDtoFromJSONTyped(json, false)
}

export function ExposedDocsTreeNodeDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ExposedDocsTreeNodeDto {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    path: json['path'] == null ? undefined : json['path'],
    directory: json['directory'] == null ? undefined : json['directory'],
    children:
      json['children'] == null
        ? undefined
        : (json['children'] as Array<any>).map(ExposedDocsTreeNodeDtoFromJSON),
  }
}

export function ExposedDocsTreeNodeDtoToJSON(
  json: any
): ExposedDocsTreeNodeDto {
  return ExposedDocsTreeNodeDtoToJSONTyped(json, false)
}

export function ExposedDocsTreeNodeDtoToJSONTyped(
  value?: ExposedDocsTreeNodeDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    path: value['path'],
    directory: value['directory'],
    children:
      value['children'] == null
        ? undefined
        : (value['children'] as Array<any>).map(ExposedDocsTreeNodeDtoToJSON),
  }
}
