/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalIds
 */
export interface ExternalIds {
    /**
     * 
     * @type {string}
     * @memberof ExternalIds
     */
    asin?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalIds
     */
    icecat?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ExternalIds
     */
    mpn?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ExternalIds
     */
    sku?: Set<string>;
}

/**
 * Check if a given object implements the ExternalIds interface.
 */
export function instanceOfExternalIds(value: object): value is ExternalIds {
    return true;
}

export function ExternalIdsFromJSON(json: any): ExternalIds {
    return ExternalIdsFromJSONTyped(json, false);
}

export function ExternalIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalIds {
    if (json == null) {
        return json;
    }
    return {
        
        'asin': json['asin'] == null ? undefined : json['asin'],
        'icecat': json['icecat'] == null ? undefined : json['icecat'],
        'mpn': json['mpn'] == null ? undefined : new Set(json['mpn']),
        'sku': json['sku'] == null ? undefined : new Set(json['sku']),
    };
}

export function ExternalIdsToJSON(json: any): ExternalIds {
    return ExternalIdsToJSONTyped(json, false);
}

export function ExternalIdsToJSONTyped(value?: ExternalIds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asin': value['asin'],
        'icecat': value['icecat'],
        'mpn': value['mpn'] == null ? undefined : Array.from(value['mpn'] as Set<any>),
        'sku': value['sku'] == null ? undefined : Array.from(value['sku'] as Set<any>),
    };
}

