/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeConfigUnit } from './AttributeConfigUnit';
import {
    AttributeConfigUnitFromJSON,
    AttributeConfigUnitFromJSONTyped,
    AttributeConfigUnitToJSON,
    AttributeConfigUnitToJSONTyped,
} from './AttributeConfigUnit';

/**
 * 
 * @export
 * @interface FeatureGroup
 */
export interface FeatureGroup {
    /**
     * 
     * @type {number}
     * @memberof FeatureGroup
     */
    icecatCategoryFeatureGroupId?: number;
    /**
     * 
     * @type {AttributeConfigUnit}
     * @memberof FeatureGroup
     */
    name?: AttributeConfigUnit;
    /**
     * 
     * @type {Array<number>}
     * @memberof FeatureGroup
     */
    featuresId?: Array<number>;
}

/**
 * Check if a given object implements the FeatureGroup interface.
 */
export function instanceOfFeatureGroup(value: object): value is FeatureGroup {
    return true;
}

export function FeatureGroupFromJSON(json: any): FeatureGroup {
    return FeatureGroupFromJSONTyped(json, false);
}

export function FeatureGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'icecatCategoryFeatureGroupId': json['icecatCategoryFeatureGroupId'] == null ? undefined : json['icecatCategoryFeatureGroupId'],
        'name': json['name'] == null ? undefined : AttributeConfigUnitFromJSON(json['name']),
        'featuresId': json['featuresId'] == null ? undefined : json['featuresId'],
    };
}

export function FeatureGroupToJSON(json: any): FeatureGroup {
    return FeatureGroupToJSONTyped(json, false);
}

export function FeatureGroupToJSONTyped(value?: FeatureGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icecatCategoryFeatureGroupId': value['icecatCategoryFeatureGroupId'],
        'name': AttributeConfigUnitToJSON(value['name']),
        'featuresId': value['featuresId'],
    };
}

