/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureGroupDto
 */
export interface FeatureGroupDto {
    /**
     * Identifier of the Icecat feature group mapped to this entry.
     * @type {number}
     * @memberof FeatureGroupDto
     */
    icecatCategoryFeatureGroupId?: number;
    /**
     * Localised display name of the feature group.
     * @type {string}
     * @memberof FeatureGroupDto
     */
    name?: string;
    /**
     * Identifiers of the Icecat features that belong to this group.
     * @type {Array<number>}
     * @memberof FeatureGroupDto
     */
    featuresId?: Array<number>;
}

/**
 * Check if a given object implements the FeatureGroupDto interface.
 */
export function instanceOfFeatureGroupDto(value: object): value is FeatureGroupDto {
    return true;
}

export function FeatureGroupDtoFromJSON(json: any): FeatureGroupDto {
    return FeatureGroupDtoFromJSONTyped(json, false);
}

export function FeatureGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'icecatCategoryFeatureGroupId': json['icecatCategoryFeatureGroupId'] == null ? undefined : json['icecatCategoryFeatureGroupId'],
        'name': json['name'] == null ? undefined : json['name'],
        'featuresId': json['featuresId'] == null ? undefined : json['featuresId'],
    };
}

export function FeatureGroupDtoToJSON(json: any): FeatureGroupDto {
    return FeatureGroupDtoToJSONTyped(json, false);
}

export function FeatureGroupDtoToJSONTyped(value?: FeatureGroupDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icecatCategoryFeatureGroupId': value['icecatCategoryFeatureGroupId'],
        'name': value['name'],
        'featuresId': value['featuresId'],
    };
}

