/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface FeedbackRemainingVotesDto
 */
export interface FeedbackRemainingVotesDto {
  /**
   * Nombre de votes restants pour aujourd'hui.
   * @type {number}
   * @memberof FeedbackRemainingVotesDto
   */
  remainingVotes?: number
}

/**
 * Check if a given object implements the FeedbackRemainingVotesDto interface.
 */
export function instanceOfFeedbackRemainingVotesDto(
  value: object
): value is FeedbackRemainingVotesDto {
  return true
}

export function FeedbackRemainingVotesDtoFromJSON(
  json: any
): FeedbackRemainingVotesDto {
  return FeedbackRemainingVotesDtoFromJSONTyped(json, false)
}

export function FeedbackRemainingVotesDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FeedbackRemainingVotesDto {
  if (json == null) {
    return json
  }
  return {
    remainingVotes:
      json['remainingVotes'] == null ? undefined : json['remainingVotes'],
  }
}

export function FeedbackRemainingVotesDtoToJSON(
  json: any
): FeedbackRemainingVotesDto {
  return FeedbackRemainingVotesDtoToJSONTyped(json, false)
}

export function FeedbackRemainingVotesDtoToJSONTyped(
  value?: FeedbackRemainingVotesDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    remainingVotes: value['remainingVotes'],
  }
}
