/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackVoteResponseDto
 */
export interface FeedbackVoteResponseDto {
    /**
     * Nombre de votes restants pour l'adresse IP courante.
     * @type {number}
     * @memberof FeedbackVoteResponseDto
     */
    remainingVotes?: number;
    /**
     * Nombre total de votes enregistrés pour l'issue.
     * @type {number}
     * @memberof FeedbackVoteResponseDto
     */
    totalVotes?: number;
}

/**
 * Check if a given object implements the FeedbackVoteResponseDto interface.
 */
export function instanceOfFeedbackVoteResponseDto(value: object): value is FeedbackVoteResponseDto {
    return true;
}

export function FeedbackVoteResponseDtoFromJSON(json: any): FeedbackVoteResponseDto {
    return FeedbackVoteResponseDtoFromJSONTyped(json, false);
}

export function FeedbackVoteResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackVoteResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'remainingVotes': json['remainingVotes'] == null ? undefined : json['remainingVotes'],
        'totalVotes': json['totalVotes'] == null ? undefined : json['totalVotes'],
    };
}

export function FeedbackVoteResponseDtoToJSON(json: any): FeedbackVoteResponseDto {
    return FeedbackVoteResponseDtoToJSONTyped(json, false);
}

export function FeedbackVoteResponseDtoToJSONTyped(value?: FeedbackVoteResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'remainingVotes': value['remainingVotes'],
        'totalVotes': value['totalVotes'],
    };
}

