/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Filter } from './Filter';
import {
    FilterFromJSON,
    FilterFromJSONTyped,
    FilterToJSON,
    FilterToJSONTyped,
} from './Filter';

/**
 * 
 * @export
 * @interface FilterRequestDto
 */
export interface FilterRequestDto {
    /**
     * Collection of filter clauses. When omitted no additional filtering is applied.
     * @type {Array<Filter>}
     * @memberof FilterRequestDto
     */
    filters?: Array<Filter>;
}

/**
 * Check if a given object implements the FilterRequestDto interface.
 */
export function instanceOfFilterRequestDto(value: object): value is FilterRequestDto {
    return true;
}

export function FilterRequestDtoFromJSON(json: any): FilterRequestDto {
    return FilterRequestDtoFromJSONTyped(json, false);
}

export function FilterRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(FilterFromJSON)),
    };
}

export function FilterRequestDtoToJSON(json: any): FilterRequestDto {
    return FilterRequestDtoToJSONTyped(json, false);
}

export function FilterRequestDtoToJSONTyped(value?: FilterRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(FilterToJSON)),
    };
}

