/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Filter } from './Filter';
import {
    FilterFromJSON,
    FilterFromJSONTyped,
    FilterToJSON,
    FilterToJSONTyped,
} from './Filter';
import type { FilterGroup } from './FilterGroup';
import {
    FilterGroupFromJSON,
    FilterGroupFromJSONTyped,
    FilterGroupToJSON,
    FilterGroupToJSONTyped,
} from './FilterGroup';

/**
 * 
 * @export
 * @interface FilterRequestDto
 */
export interface FilterRequestDto {
    /**
     * Collection of filter clauses. When omitted no additional filtering is applied.
     * @type {Array<Filter>}
     * @memberof FilterRequestDto
     */
    filters?: Array<Filter>;
    /**
     * Collection of filter groups combined with OR. Each group can mix mandatory (must) and optional (should) clauses.
     * @type {Array<FilterGroup>}
     * @memberof FilterRequestDto
     */
    filterGroups?: Array<FilterGroup>;
}

/**
 * Check if a given object implements the FilterRequestDto interface.
 */
export function instanceOfFilterRequestDto(value: object): value is FilterRequestDto {
    return true;
}

export function FilterRequestDtoFromJSON(json: any): FilterRequestDto {
    return FilterRequestDtoFromJSONTyped(json, false);
}

export function FilterRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterRequestDto {
    if (json == null) {
        return json;
    }
    return {

        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(FilterFromJSON)),
        'filterGroups': json['filterGroups'] == null ? undefined : ((json['filterGroups'] as Array<any>).map(FilterGroupFromJSON)),
    };
}

export function FilterRequestDtoToJSON(json: any): FilterRequestDto {
    return FilterRequestDtoToJSONTyped(json, false);
}

export function FilterRequestDtoToJSONTyped(value?: FilterRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(FilterToJSON)),
        'filterGroups': value['filterGroups'] == null ? undefined : ((value['filterGroups'] as Array<any>).map(FilterGroupToJSON)),
    };
}

