/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeocodeResponse
 */
export interface GeocodeResponse {
    /**
     * 
     * @type {string}
     * @memberof GeocodeResponse
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof GeocodeResponse
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof GeocodeResponse
     */
    matchedName?: string;
    /**
     * 
     * @type {number}
     * @memberof GeocodeResponse
     */
    geonameId?: number;
    /**
     * 
     * @type {number}
     * @memberof GeocodeResponse
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GeocodeResponse
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GeocodeResponse
     */
    population?: number;
    /**
     * 
     * @type {string}
     * @memberof GeocodeResponse
     */
    matchType?: GeocodeResponseMatchTypeEnum;
}


/**
 * @export
 */
export const GeocodeResponseMatchTypeEnum = {
    Primary: 'PRIMARY',
    Ascii: 'ASCII',
    Alternate: 'ALTERNATE'
} as const;
export type GeocodeResponseMatchTypeEnum = typeof GeocodeResponseMatchTypeEnum[keyof typeof GeocodeResponseMatchTypeEnum];


/**
 * Check if a given object implements the GeocodeResponse interface.
 */
export function instanceOfGeocodeResponse(value: object): value is GeocodeResponse {
    return true;
}

export function GeocodeResponseFromJSON(json: any): GeocodeResponse {
    return GeocodeResponseFromJSONTyped(json, false);
}

export function GeocodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeocodeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'matchedName': json['matchedName'] == null ? undefined : json['matchedName'],
        'geonameId': json['geonameId'] == null ? undefined : json['geonameId'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'population': json['population'] == null ? undefined : json['population'],
        'matchType': json['matchType'] == null ? undefined : json['matchType'],
    };
}

export function GeocodeResponseToJSON(json: any): GeocodeResponse {
    return GeocodeResponseToJSONTyped(json, false);
}

export function GeocodeResponseToJSONTyped(value?: GeocodeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'country': value['country'],
        'matchedName': value['matchedName'],
        'geonameId': value['geonameId'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'population': value['population'],
        'matchType': value['matchType'],
    };
}

