/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GlobalSearchResultDto } from './GlobalSearchResultDto';
import {
    GlobalSearchResultDtoFromJSON,
    GlobalSearchResultDtoFromJSONTyped,
    GlobalSearchResultDtoToJSON,
    GlobalSearchResultDtoToJSONTyped,
} from './GlobalSearchResultDto';
import type { SearchMode } from './SearchMode';

/**
 * 
 * @export
 * @interface GlobalSearchVerticalGroupDto
 */
export interface GlobalSearchVerticalGroupDto {
    /**
     * Identifier of the vertical associated with the group
     * @type {string}
     * @memberof GlobalSearchVerticalGroupDto
     */
    verticalId?: string;
    /**
     * Effective search mode that produced the group
     * @type {SearchMode}
     * @memberof GlobalSearchVerticalGroupDto
     */
    searchMode?: SearchMode;
    /**
     * Ordered results belonging to the vertical
     * @type {Array<GlobalSearchResultDto>}
     * @memberof GlobalSearchVerticalGroupDto
     */
    results?: Array<GlobalSearchResultDto>;
}

/**
 * Check if a given object implements the GlobalSearchVerticalGroupDto interface.
 */
export function instanceOfGlobalSearchVerticalGroupDto(value: object): value is GlobalSearchVerticalGroupDto {
    return true;
}

export function GlobalSearchVerticalGroupDtoFromJSON(json: any): GlobalSearchVerticalGroupDto {
    return GlobalSearchVerticalGroupDtoFromJSONTyped(json, false);
}

export function GlobalSearchVerticalGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalSearchVerticalGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'verticalId': json['verticalId'] == null ? undefined : json['verticalId'],
        'searchMode': json['searchMode'] == null ? undefined : json['searchMode'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(GlobalSearchResultDtoFromJSON)),
    };
}

export function GlobalSearchVerticalGroupDtoToJSON(json: any): GlobalSearchVerticalGroupDto {
    return GlobalSearchVerticalGroupDtoToJSONTyped(json, false);
}

export function GlobalSearchVerticalGroupDtoToJSONTyped(value?: GlobalSearchVerticalGroupDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verticalId': value['verticalId'],
        'searchMode': value['searchMode'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(GlobalSearchResultDtoToJSON)),
    };
}
