/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleIndexationMetricsDto
 */
export interface GoogleIndexationMetricsDto {
    /**
     * Whether Google indexation dispatch is enabled
     * @type {boolean}
     * @memberof GoogleIndexationMetricsDto
     */
    enabled?: boolean;
    /**
     * Number of URLs currently stored in the queue
     * @type {number}
     * @memberof GoogleIndexationMetricsDto
     */
    queuedCount?: number;
    /**
     * Number of URLs pending processing
     * @type {number}
     * @memberof GoogleIndexationMetricsDto
     */
    pendingCount?: number;
    /**
     * Number of URLs that failed during the last attempts
     * @type {number}
     * @memberof GoogleIndexationMetricsDto
     */
    failedCount?: number;
    /**
     * Timestamp of the last successful dispatch
     * @type {Date}
     * @memberof GoogleIndexationMetricsDto
     */
    lastSuccessAt?: Date;
    /**
     * Timestamp of the last failed dispatch
     * @type {Date}
     * @memberof GoogleIndexationMetricsDto
     */
    lastFailureAt?: Date;
    /**
     * Last failure message, if any
     * @type {string}
     * @memberof GoogleIndexationMetricsDto
     */
    lastFailureMessage?: string;
}

/**
 * Check if a given object implements the GoogleIndexationMetricsDto interface.
 */
export function instanceOfGoogleIndexationMetricsDto(value: object): value is GoogleIndexationMetricsDto {
    return true;
}

export function GoogleIndexationMetricsDtoFromJSON(json: any): GoogleIndexationMetricsDto {
    return GoogleIndexationMetricsDtoFromJSONTyped(json, false);
}

export function GoogleIndexationMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleIndexationMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'queuedCount': json['queuedCount'] == null ? undefined : json['queuedCount'],
        'pendingCount': json['pendingCount'] == null ? undefined : json['pendingCount'],
        'failedCount': json['failedCount'] == null ? undefined : json['failedCount'],
        'lastSuccessAt': json['lastSuccessAt'] == null ? undefined : (new Date(json['lastSuccessAt'])),
        'lastFailureAt': json['lastFailureAt'] == null ? undefined : (new Date(json['lastFailureAt'])),
        'lastFailureMessage': json['lastFailureMessage'] == null ? undefined : json['lastFailureMessage'],
    };
}

export function GoogleIndexationMetricsDtoToJSON(json: any): GoogleIndexationMetricsDto {
    return GoogleIndexationMetricsDtoToJSONTyped(json, false);
}

export function GoogleIndexationMetricsDtoToJSONTyped(value?: GoogleIndexationMetricsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'queuedCount': value['queuedCount'],
        'pendingCount': value['pendingCount'],
        'failedCount': value['failedCount'],
        'lastSuccessAt': value['lastSuccessAt'] == null ? value['lastSuccessAt'] : value['lastSuccessAt'].toISOString(),
        'lastFailureAt': value['lastFailureAt'] == null ? value['lastFailureAt'] : value['lastFailureAt'].toISOString(),
        'lastFailureMessage': value['lastFailureMessage'],
    };
}

