/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface IcecatFeatureReferential
 */
export interface IcecatFeatureReferential {
  /**
   *
   * @type {number}
   * @memberof IcecatFeatureReferential
   */
  featureId?: number
  /**
   *
   * @type {string}
   * @memberof IcecatFeatureReferential
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof IcecatFeatureReferential
   */
  unit?: string
}

/**
 * Check if a given object implements the IcecatFeatureReferential interface.
 */
export function instanceOfIcecatFeatureReferential(
  value: object
): value is IcecatFeatureReferential {
  return true
}

export function IcecatFeatureReferentialFromJSON(
  json: any
): IcecatFeatureReferential {
  return IcecatFeatureReferentialFromJSONTyped(json, false)
}

export function IcecatFeatureReferentialFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IcecatFeatureReferential {
  if (json == null) {
    return json
  }
  return {
    featureId: json['featureId'] == null ? undefined : json['featureId'],
    name: json['name'] == null ? undefined : json['name'],
    unit: json['unit'] == null ? undefined : json['unit'],
  }
}

export function IcecatFeatureReferentialToJSON(
  json: any
): IcecatFeatureReferential {
  return IcecatFeatureReferentialToJSONTyped(json, false)
}

export function IcecatFeatureReferentialToJSONTyped(
  value?: IcecatFeatureReferential | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    featureId: value['featureId'],
    name: value['name'],
    unit: value['unit'],
  }
}
