/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImpactScoreTexts } from './ImpactScoreTexts';
import {
    ImpactScoreTextsFromJSON,
    ImpactScoreTextsFromJSONTyped,
    ImpactScoreTextsToJSON,
    ImpactScoreTextsToJSONTyped,
} from './ImpactScoreTexts';

/**
 * 
 * @export
 * @interface ImpactScoreConfigTexts
 */
export interface ImpactScoreConfigTexts {
    [key: string]: ImpactScoreTexts | any;
    /**
     * 
     * @type {boolean}
     * @memberof ImpactScoreConfigTexts
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the ImpactScoreConfigTexts interface.
 */
export function instanceOfImpactScoreConfigTexts(value: object): value is ImpactScoreConfigTexts {
    return true;
}

export function ImpactScoreConfigTextsFromJSON(json: any): ImpactScoreConfigTexts {
    return ImpactScoreConfigTextsFromJSONTyped(json, false);
}

export function ImpactScoreConfigTextsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactScoreConfigTexts {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function ImpactScoreConfigTextsToJSON(json: any): ImpactScoreConfigTexts {
    return ImpactScoreConfigTextsToJSONTyped(json, false);
}

export function ImpactScoreConfigTextsToJSONTyped(value?: ImpactScoreConfigTexts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'empty': value['empty'],
    };
}

