/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImpactScoreConfigTexts } from './ImpactScoreConfigTexts';
import {
    ImpactScoreConfigTextsFromJSON,
    ImpactScoreConfigTextsFromJSONTyped,
    ImpactScoreConfigTextsToJSON,
    ImpactScoreConfigTextsToJSONTyped,
} from './ImpactScoreConfigTexts';

/**
 * 
 * @export
 * @interface ImpactScoreConfig
 */
export interface ImpactScoreConfig {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ImpactScoreConfig
     */
    criteriasPonderation?: { [key: string]: number; };
    /**
     * 
     * @type {ImpactScoreConfigTexts}
     * @memberof ImpactScoreConfig
     */
    texts?: ImpactScoreConfigTexts;
    /**
     * 
     * @type {string}
     * @memberof ImpactScoreConfig
     */
    yamlPrompt?: string;
    /**
     * 
     * @type {string}
     * @memberof ImpactScoreConfig
     */
    aiJsonResponse?: string;
}

/**
 * Check if a given object implements the ImpactScoreConfig interface.
 */
export function instanceOfImpactScoreConfig(value: object): value is ImpactScoreConfig {
    return true;
}

export function ImpactScoreConfigFromJSON(json: any): ImpactScoreConfig {
    return ImpactScoreConfigFromJSONTyped(json, false);
}

export function ImpactScoreConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactScoreConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'criteriasPonderation': json['criteriasPonderation'] == null ? undefined : json['criteriasPonderation'],
        'texts': json['texts'] == null ? undefined : ImpactScoreConfigTextsFromJSON(json['texts']),
        'yamlPrompt': json['yamlPrompt'] == null ? undefined : json['yamlPrompt'],
        'aiJsonResponse': json['aiJsonResponse'] == null ? undefined : json['aiJsonResponse'],
    };
}

export function ImpactScoreConfigToJSON(json: any): ImpactScoreConfig {
    return ImpactScoreConfigToJSONTyped(json, false);
}

export function ImpactScoreConfigToJSONTyped(value?: ImpactScoreConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'criteriasPonderation': value['criteriasPonderation'],
        'texts': ImpactScoreConfigTextsToJSON(value['texts']),
        'yamlPrompt': value['yamlPrompt'],
        'aiJsonResponse': value['aiJsonResponse'],
    };
}

