/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IpQuotaCategory } from './IpQuotaCategory';

/**
 *
 * @export
 * @interface IpQuotaStatusDto
 */
export interface IpQuotaStatusDto {
    /**
     * Category associated with the quota.
     * @type {IpQuotaCategory}
     * @memberof IpQuotaStatusDto
     */
    category: IpQuotaCategory;
    /**
     * Maximum number of actions allowed per quota window.
     * @type {number}
     * @memberof IpQuotaStatusDto
     */
    limit: number;
    /**
     * Number of actions already performed within the window.
     * @type {number}
     * @memberof IpQuotaStatusDto
     */
    used: number;
    /**
     * Number of actions remaining within the window.
     * @type {number}
     * @memberof IpQuotaStatusDto
     */
    remaining: number;
    /**
     * Quota window duration in seconds.
     * @type {number}
     * @memberof IpQuotaStatusDto
     */
    windowSeconds?: number;
}

/**
 * Check if a given object implements the IpQuotaStatusDto interface.
 */
export function instanceOfIpQuotaStatusDto(value: object): value is IpQuotaStatusDto {
    return true;
}

export function IpQuotaStatusDtoFromJSON(json: any): IpQuotaStatusDto {
    return IpQuotaStatusDtoFromJSONTyped(json, false);
}

export function IpQuotaStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpQuotaStatusDto {
    if (json == null) {
        return json;
    }
    return {

        'category': json['category'],
        'limit': json['limit'],
        'used': json['used'],
        'remaining': json['remaining'],
        'windowSeconds': json['windowSeconds'] == null ? undefined : json['windowSeconds'],
    };
}

export function IpQuotaStatusDtoToJSON(json: any): IpQuotaStatusDto {
    return IpQuotaStatusDtoToJSONTyped(json, false);
}

export function IpQuotaStatusDtoToJSONTyped(value?: IpQuotaStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'category': value['category'],
        'limit': value['limit'],
        'used': value['used'],
        'remaining': value['remaining'],
        'windowSeconds': value['windowSeconds'],
    };
}
