/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ManufacturingSiteDistance } from './ManufacturingSiteDistance';
import {
    ManufacturingSiteDistanceFromJSON,
    ManufacturingSiteDistanceFromJSONTyped,
    ManufacturingSiteDistanceToJSON,
    ManufacturingSiteDistanceToJSONTyped,
} from './ManufacturingSiteDistance';

/**
 * Distance from the requesting user to the product's manufacturing sites.
 * @export
 * @interface ManufacturingDistance
 */
export interface ManufacturingDistance {
    /**
     * Resolved user country code.
     * @type {string}
     * @memberof ManufacturingDistance
     */
    userCountry?: string | null;
    /**
     * Resolved user city.
     * @type {string}
     * @memberof ManufacturingDistance
     */
    userCity?: string | null;
    /**
     * Resolved user latitude.
     * @type {number}
     * @memberof ManufacturingDistance
     */
    latitude?: number | null;
    /**
     * Resolved user longitude.
     * @type {number}
     * @memberof ManufacturingDistance
     */
    longitude?: number | null;
    /**
     * Per-site distances, nearest first.
     * @type {Array<ManufacturingSiteDistance>}
     * @memberof ManufacturingDistance
     */
    sites?: Array<ManufacturingSiteDistance>;
}

/**
 * Check if a given object implements the ManufacturingDistance interface.
 */
export function instanceOfManufacturingDistance(value: object): value is ManufacturingDistance {
    return true;
}

export function ManufacturingDistanceFromJSON(json: any): ManufacturingDistance {
    return ManufacturingDistanceFromJSONTyped(json, false);
}

export function ManufacturingDistanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManufacturingDistance {
    if (json == null) {
        return json;
    }
    return {
        
        'userCountry': json['userCountry'] == null ? undefined : json['userCountry'],
        'userCity': json['userCity'] == null ? undefined : json['userCity'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'sites': json['sites'] == null ? undefined : ((json['sites'] as Array<any>).map(ManufacturingSiteDistanceFromJSON)),
    };
}

export function ManufacturingDistanceToJSON(json: any): ManufacturingDistance {
    return ManufacturingDistanceToJSONTyped(json, false);
}

export function ManufacturingDistanceToJSONTyped(value?: ManufacturingDistance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userCountry': value['userCountry'],
        'userCity': value['userCity'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'sites': value['sites'] == null ? undefined : ((value['sites'] as Array<any>).map(ManufacturingSiteDistanceToJSON)),
    };
}

