/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface MetriksReportValueDto
 */
export interface MetriksReportValueDto {
    /**
     * Date key
     * @type {string}
     * @memberof MetriksReportValueDto
     */
    dateKey?: string;
    /**
     * Metric value
     * @type {number}
     * @memberof MetriksReportValueDto
     */
    value?: number;
    /**
     * Absolute variation
     * @type {number}
     * @memberof MetriksReportValueDto
     */
    variationAbs?: number;
    /**
     * Percentage variation
     * @type {number}
     * @memberof MetriksReportValueDto
     */
    variationPct?: number;
    /**
     * Raw metriks payload
     * @type {any}
     * @memberof MetriksReportValueDto
     */
    payload?: any;
}

/**
 * Check if a given object implements the MetriksReportValueDto interface.
 */
export function instanceOfMetriksReportValueDto(value: object): value is MetriksReportValueDto {
    return true;
}

export function MetriksReportValueDtoFromJSON(json: any): MetriksReportValueDto {
    return MetriksReportValueDtoFromJSONTyped(json, false);
}

export function MetriksReportValueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetriksReportValueDto {
    if (json == null) {
        return json;
    }
    return {
        'dateKey': json['dateKey'] == null ? undefined : json['dateKey'],
        'value': json['value'] == null ? undefined : json['value'],
        'variationAbs': json['variationAbs'] == null ? undefined : json['variationAbs'],
        'variationPct': json['variationPct'] == null ? undefined : json['variationPct'],
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function MetriksReportValueDtoToJSON(json: any): MetriksReportValueDto {
    return MetriksReportValueDtoToJSONTyped(json, false);
}

export function MetriksReportValueDtoToJSONTyped(value?: MetriksReportValueDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'dateKey': value['dateKey'],
        'value': value['value'],
        'variationAbs': value['variationAbs'],
        'variationPct': value['variationPct'],
        'payload': value['payload'],
    };
}
