/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NudgeToolScoreDto
 */
export interface NudgeToolScoreDto {
    /**
     * Identifier of the score used by the nudge tool.
     * @type {string}
     * @memberof NudgeToolScoreDto
     */
    scoreName?: string;
    /**
     * Minimum value required to feature the score.
     * @type {number}
     * @memberof NudgeToolScoreDto
     */
    scoreMinValue?: number;
    /**
     * Material Design icon representing the score.
     * @type {string}
     * @memberof NudgeToolScoreDto
     */
    mdiIcon?: string;
    /**
     * Localised title of the nudge.
     * @type {string}
     * @memberof NudgeToolScoreDto
     */
    title?: string;
    /**
     * Localised description for the nudge.
     * @type {string}
     * @memberof NudgeToolScoreDto
     */
    description?: string;
}

/**
 * Check if a given object implements the NudgeToolScoreDto interface.
 */
export function instanceOfNudgeToolScoreDto(value: object): value is NudgeToolScoreDto {
    return true;
}

export function NudgeToolScoreDtoFromJSON(json: any): NudgeToolScoreDto {
    return NudgeToolScoreDtoFromJSONTyped(json, false);
}

export function NudgeToolScoreDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NudgeToolScoreDto {
    if (json == null) {
        return json;
    }
    return {
        
        'scoreName': json['scoreName'] == null ? undefined : json['scoreName'],
        'scoreMinValue': json['scoreMinValue'] == null ? undefined : json['scoreMinValue'],
        'mdiIcon': json['mdiIcon'] == null ? undefined : json['mdiIcon'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function NudgeToolScoreDtoToJSON(json: any): NudgeToolScoreDto {
    return NudgeToolScoreDtoToJSONTyped(json, false);
}

export function NudgeToolScoreDtoToJSONTyped(value?: NudgeToolScoreDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scoreName': value['scoreName'],
        'scoreMinValue': value['scoreMinValue'],
        'mdiIcon': value['mdiIcon'],
        'title': value['title'],
        'description': value['description'],
    };
}

