/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface ObjectSummary
 */
export interface ObjectSummary {
    /**
     * 
     * @type {Array<Link>}
     * @memberof ObjectSummary
     */
    links?: Array<Link>;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    guid?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    pageId?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    pageVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    wiki?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    space?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    pageName?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    pageAuthor?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    pageAuthorName?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    className?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjectSummary
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectSummary
     */
    headline?: string;
}

/**
 * Check if a given object implements the ObjectSummary interface.
 */
export function instanceOfObjectSummary(value: object): value is ObjectSummary {
    return true;
}

export function ObjectSummaryFromJSON(json: any): ObjectSummary {
    return ObjectSummaryFromJSONTyped(json, false);
}

export function ObjectSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(LinkFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'guid': json['guid'] == null ? undefined : json['guid'],
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'pageVersion': json['pageVersion'] == null ? undefined : json['pageVersion'],
        'wiki': json['wiki'] == null ? undefined : json['wiki'],
        'space': json['space'] == null ? undefined : json['space'],
        'pageName': json['pageName'] == null ? undefined : json['pageName'],
        'pageAuthor': json['pageAuthor'] == null ? undefined : json['pageAuthor'],
        'pageAuthorName': json['pageAuthorName'] == null ? undefined : json['pageAuthorName'],
        'className': json['className'] == null ? undefined : json['className'],
        'number': json['number'] == null ? undefined : json['number'],
        'headline': json['headline'] == null ? undefined : json['headline'],
    };
}

export function ObjectSummaryToJSON(json: any): ObjectSummary {
    return ObjectSummaryToJSONTyped(json, false);
}

export function ObjectSummaryToJSONTyped(value?: ObjectSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(LinkToJSON)),
        'id': value['id'],
        'guid': value['guid'],
        'pageId': value['pageId'],
        'pageVersion': value['pageVersion'],
        'wiki': value['wiki'],
        'space': value['space'],
        'pageName': value['pageName'],
        'pageAuthor': value['pageAuthor'],
        'pageAuthorName': value['pageAuthorName'],
        'className': value['className'],
        'number': value['number'],
        'headline': value['headline'],
    };
}

