/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Download limits applied to OpenData dataset transfers.
 * @export
 * @interface OpenDataDownloadLimitsDto
 */
export interface OpenDataDownloadLimitsDto {
  /**
   * Maximum download speed per client expressed in kilobytes per second.
   * @type {number}
   * @memberof OpenDataDownloadLimitsDto
   */
  downloadSpeedKb?: number
  /**
   * Human readable download speed formatted according to the requested locale.
   * @type {string}
   * @memberof OpenDataDownloadLimitsDto
   */
  downloadSpeed?: string
  /**
   * Maximum number of concurrent downloads accepted by the platform.
   * @type {number}
   * @memberof OpenDataDownloadLimitsDto
   */
  concurrentDownloads?: number
}

/**
 * Check if a given object implements the OpenDataDownloadLimitsDto interface.
 */
export function instanceOfOpenDataDownloadLimitsDto(
  value: object
): value is OpenDataDownloadLimitsDto {
  return true
}

export function OpenDataDownloadLimitsDtoFromJSON(
  json: any
): OpenDataDownloadLimitsDto {
  return OpenDataDownloadLimitsDtoFromJSONTyped(json, false)
}

export function OpenDataDownloadLimitsDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OpenDataDownloadLimitsDto {
  if (json == null) {
    return json
  }
  return {
    downloadSpeedKb:
      json['downloadSpeedKb'] == null ? undefined : json['downloadSpeedKb'],
    downloadSpeed:
      json['downloadSpeed'] == null ? undefined : json['downloadSpeed'],
    concurrentDownloads:
      json['concurrentDownloads'] == null
        ? undefined
        : json['concurrentDownloads'],
  }
}

export function OpenDataDownloadLimitsDtoToJSON(
  json: any
): OpenDataDownloadLimitsDto {
  return OpenDataDownloadLimitsDtoToJSONTyped(json, false)
}

export function OpenDataDownloadLimitsDtoToJSONTyped(
  value?: OpenDataDownloadLimitsDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    downloadSpeedKb: value['downloadSpeedKb'],
    downloadSpeed: value['downloadSpeed'],
    concurrentDownloads: value['concurrentDownloads'],
  }
}
