/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageMetaDto
 */
export interface PageMetaDto {
    /**
     * Zero-based page index
     * @type {number}
     * @memberof PageMetaDto
     */
    number?: number;
    /**
     * Requested page size
     * @type {number}
     * @memberof PageMetaDto
     */
    size?: number;
    /**
     * Total number of elements
     * @type {number}
     * @memberof PageMetaDto
     */
    totalElements?: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PageMetaDto
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageMetaDto interface.
 */
export function instanceOfPageMetaDto(value: object): value is PageMetaDto {
    return true;
}

export function PageMetaDtoFromJSON(json: any): PageMetaDto {
    return PageMetaDtoFromJSONTyped(json, false);
}

export function PageMetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMetaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageMetaDtoToJSON(json: any): PageMetaDto {
    return PageMetaDtoToJSONTyped(json, false);
}

export function PageMetaDtoToJSONTyped(value?: PageMetaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

