/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';
import type { ProductDto } from './ProductDto';
import {
    ProductDtoFromJSON,
    ProductDtoFromJSONTyped,
    ProductDtoToJSON,
    ProductDtoToJSONTyped,
} from './ProductDto';

/**
 * 
 * @export
 * @interface PageProductDto
 */
export interface PageProductDto {
    /**
     * 
     * @type {number}
     * @memberof PageProductDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageProductDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageProductDto
     */
    size?: number;
    /**
     * 
     * @type {Array<ProductDto>}
     * @memberof PageProductDto
     */
    content?: Array<ProductDto>;
    /**
     * 
     * @type {number}
     * @memberof PageProductDto
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageProductDto
     */
    sort?: SortObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageProductDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageProductDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageProductDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageProductDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageProductDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageProductDto interface.
 */
export function instanceOfPageProductDto(value: object): value is PageProductDto {
    return true;
}

export function PageProductDtoFromJSON(json: any): PageProductDto {
    return PageProductDtoFromJSONTyped(json, false);
}

export function PageProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ProductDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageProductDtoToJSON(json: any): PageProductDto {
    return PageProductDtoToJSONTyped(json, false);
}

export function PageProductDtoToJSONTyped(value?: PageProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ProductDtoToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

