/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ProblemDetail
 */
export interface ProblemDetail {
  /**
   *
   * @type {string}
   * @memberof ProblemDetail
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof ProblemDetail
   */
  title?: string
  /**
   *
   * @type {number}
   * @memberof ProblemDetail
   */
  status?: number
  /**
   *
   * @type {string}
   * @memberof ProblemDetail
   */
  detail?: string
  /**
   *
   * @type {string}
   * @memberof ProblemDetail
   */
  instance?: string
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof ProblemDetail
   */
  properties?: { [key: string]: any }
}

/**
 * Check if a given object implements the ProblemDetail interface.
 */
export function instanceOfProblemDetail(value: object): value is ProblemDetail {
  return true
}

export function ProblemDetailFromJSON(json: any): ProblemDetail {
  return ProblemDetailFromJSONTyped(json, false)
}

export function ProblemDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProblemDetail {
  if (json == null) {
    return json
  }
  return {
    type: json['type'] == null ? undefined : json['type'],
    title: json['title'] == null ? undefined : json['title'],
    status: json['status'] == null ? undefined : json['status'],
    detail: json['detail'] == null ? undefined : json['detail'],
    instance: json['instance'] == null ? undefined : json['instance'],
    properties: json['properties'] == null ? undefined : json['properties'],
  }
}

export function ProblemDetailToJSON(json: any): ProblemDetail {
  return ProblemDetailToJSONTyped(json, false)
}

export function ProblemDetailToJSONTyped(
  value?: ProblemDetail | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    type: value['type'],
    title: value['title'],
    status: value['status'],
    detail: value['detail'],
    instance: value['instance'],
    properties: value['properties'],
  }
}
