/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdditionalDetails } from './AdditionalDetails';
import {
    AdditionalDetailsFromJSON,
    AdditionalDetailsFromJSONTyped,
    AdditionalDetailsToJSON,
    AdditionalDetailsToJSONTyped,
} from './AdditionalDetails';
import type { UploadedLabel } from './UploadedLabel';
import {
    UploadedLabelFromJSON,
    UploadedLabelFromJSONTyped,
    UploadedLabelToJSON,
    UploadedLabelToJSONTyped,
} from './UploadedLabel';
import type { ContactDetails } from './ContactDetails';
import {
    ContactDetailsFromJSON,
    ContactDetailsFromJSONTyped,
    ContactDetailsToJSON,
    ContactDetailsToJSONTyped,
} from './ContactDetails';
import type { Organisation } from './Organisation';
import {
    OrganisationFromJSON,
    OrganisationFromJSONTyped,
    OrganisationToJSON,
    OrganisationToJSONTyped,
} from './Organisation';
import type { PlacementCountry } from './PlacementCountry';
import {
    PlacementCountryFromJSON,
    PlacementCountryFromJSONTyped,
    PlacementCountryToJSON,
    PlacementCountryToJSONTyped,
} from './PlacementCountry';

/**
 * EPREL product metadata without category specific attributes
 * @export
 * @interface ProductEprelDto
 */
export interface ProductEprelDto {
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    eprelRegistrationNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    productGroup?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    implementingAct?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    trademarkId?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    supplierOrTrademark?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    modelIdentifier?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    versionId?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    versionNumber?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductEprelDto
     */
    lastVersion?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductEprelDto
     */
    allowEprelLabelGeneration?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    productModelCoreId?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    registrantNature?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    constructedEUID?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    energyLabelId?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    status?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductEprelDto
     */
    skipScaleValidation?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    energyClass?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    energyClassImage?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    formType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductEprelDto
     */
    visibleToUkMsa?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    exportDateTs?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    importedOn?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    orgVerificationStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    trademarkVerificationStatus?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductEprelDto
     */
    blocked?: boolean;
    /**
     * 
     * @type {Array<UploadedLabel>}
     * @memberof ProductEprelDto
     */
    uploadedLabels?: Array<UploadedLabel>;
    /**
     * 
     * @type {ContactDetails}
     * @memberof ProductEprelDto
     */
    contactDetails?: ContactDetails;
    /**
     * 
     * @type {Array<PlacementCountry>}
     * @memberof ProductEprelDto
     */
    placementCountries?: Array<PlacementCountry>;
    /**
     * 
     * @type {Organisation}
     * @memberof ProductEprelDto
     */
    organisation?: Organisation;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    numericGtin?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProductEprelDto
     */
    categorySpecificAttributes?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    onMarketStartDate?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    onMarketStartDateTS?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    onMarketEndDate?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    onMarketEndDateTS?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    onMarketFirstStartDate?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    onMarketFirstStartDateTS?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    firstPublicationDate?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    firstPublicationDateTS?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    publishedOnDate?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductEprelDto
     */
    publishedOnDateTS?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    gtinIdentifier?: string;
    /**
     * 
     * @type {AdditionalDetails}
     * @memberof ProductEprelDto
     */
    additionalDetails?: AdditionalDetails;
    /**
     * 
     * @type {string}
     * @memberof ProductEprelDto
     */
    category?: string;
}

/**
 * Check if a given object implements the ProductEprelDto interface.
 */
export function instanceOfProductEprelDto(value: object): value is ProductEprelDto {
    return true;
}

export function ProductEprelDtoFromJSON(json: any): ProductEprelDto {
    return ProductEprelDtoFromJSONTyped(json, false);
}

export function ProductEprelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductEprelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'eprelRegistrationNumber': json['eprelRegistrationNumber'] == null ? undefined : json['eprelRegistrationNumber'],
        'productGroup': json['productGroup'] == null ? undefined : json['productGroup'],
        'implementingAct': json['implementingAct'] == null ? undefined : json['implementingAct'],
        'trademarkId': json['trademarkId'] == null ? undefined : json['trademarkId'],
        'supplierOrTrademark': json['supplierOrTrademark'] == null ? undefined : json['supplierOrTrademark'],
        'modelIdentifier': json['modelIdentifier'] == null ? undefined : json['modelIdentifier'],
        'versionId': json['versionId'] == null ? undefined : json['versionId'],
        'versionNumber': json['versionNumber'] == null ? undefined : json['versionNumber'],
        'lastVersion': json['lastVersion'] == null ? undefined : json['lastVersion'],
        'allowEprelLabelGeneration': json['allowEprelLabelGeneration'] == null ? undefined : json['allowEprelLabelGeneration'],
        'productModelCoreId': json['productModelCoreId'] == null ? undefined : json['productModelCoreId'],
        'registrantNature': json['registrantNature'] == null ? undefined : json['registrantNature'],
        'constructedEUID': json['constructedEUID'] == null ? undefined : json['constructedEUID'],
        'energyLabelId': json['energyLabelId'] == null ? undefined : json['energyLabelId'],
        'status': json['status'] == null ? undefined : json['status'],
        'skipScaleValidation': json['skipScaleValidation'] == null ? undefined : json['skipScaleValidation'],
        'energyClass': json['energyClass'] == null ? undefined : json['energyClass'],
        'energyClassImage': json['energyClassImage'] == null ? undefined : json['energyClassImage'],
        'formType': json['formType'] == null ? undefined : json['formType'],
        'visibleToUkMsa': json['visibleToUkMsa'] == null ? undefined : json['visibleToUkMsa'],
        'exportDateTs': json['exportDateTs'] == null ? undefined : json['exportDateTs'],
        'importedOn': json['importedOn'] == null ? undefined : json['importedOn'],
        'orgVerificationStatus': json['orgVerificationStatus'] == null ? undefined : json['orgVerificationStatus'],
        'trademarkVerificationStatus': json['trademarkVerificationStatus'] == null ? undefined : json['trademarkVerificationStatus'],
        'blocked': json['blocked'] == null ? undefined : json['blocked'],
        'uploadedLabels': json['uploadedLabels'] == null ? undefined : ((json['uploadedLabels'] as Array<any>).map(UploadedLabelFromJSON)),
        'contactDetails': json['contactDetails'] == null ? undefined : ContactDetailsFromJSON(json['contactDetails']),
        'placementCountries': json['placementCountries'] == null ? undefined : ((json['placementCountries'] as Array<any>).map(PlacementCountryFromJSON)),
        'organisation': json['organisation'] == null ? undefined : OrganisationFromJSON(json['organisation']),
        'numericGtin': json['numericGtin'] == null ? undefined : json['numericGtin'],
        'categorySpecificAttributes': json['categorySpecificAttributes'] == null ? undefined : json['categorySpecificAttributes'],
        'onMarketStartDate': json['onMarketStartDate'] == null ? undefined : json['onMarketStartDate'],
        'onMarketStartDateTS': json['onMarketStartDateTS'] == null ? undefined : json['onMarketStartDateTS'],
        'onMarketEndDate': json['onMarketEndDate'] == null ? undefined : json['onMarketEndDate'],
        'onMarketEndDateTS': json['onMarketEndDateTS'] == null ? undefined : json['onMarketEndDateTS'],
        'onMarketFirstStartDate': json['onMarketFirstStartDate'] == null ? undefined : json['onMarketFirstStartDate'],
        'onMarketFirstStartDateTS': json['onMarketFirstStartDateTS'] == null ? undefined : json['onMarketFirstStartDateTS'],
        'firstPublicationDate': json['firstPublicationDate'] == null ? undefined : json['firstPublicationDate'],
        'firstPublicationDateTS': json['firstPublicationDateTS'] == null ? undefined : json['firstPublicationDateTS'],
        'publishedOnDate': json['publishedOnDate'] == null ? undefined : json['publishedOnDate'],
        'publishedOnDateTS': json['publishedOnDateTS'] == null ? undefined : json['publishedOnDateTS'],
        'gtinIdentifier': json['gtinIdentifier'] == null ? undefined : json['gtinIdentifier'],
        'additionalDetails': json['additionalDetails'] == null ? undefined : AdditionalDetailsFromJSON(json['additionalDetails']),
        'category': json['category'] == null ? undefined : json['category'],
    };
}

export function ProductEprelDtoToJSON(json: any): ProductEprelDto {
    return ProductEprelDtoToJSONTyped(json, false);
}

export function ProductEprelDtoToJSONTyped(value?: ProductEprelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eprelRegistrationNumber': value['eprelRegistrationNumber'],
        'productGroup': value['productGroup'],
        'implementingAct': value['implementingAct'],
        'trademarkId': value['trademarkId'],
        'supplierOrTrademark': value['supplierOrTrademark'],
        'modelIdentifier': value['modelIdentifier'],
        'versionId': value['versionId'],
        'versionNumber': value['versionNumber'],
        'lastVersion': value['lastVersion'],
        'allowEprelLabelGeneration': value['allowEprelLabelGeneration'],
        'productModelCoreId': value['productModelCoreId'],
        'registrantNature': value['registrantNature'],
        'constructedEUID': value['constructedEUID'],
        'energyLabelId': value['energyLabelId'],
        'status': value['status'],
        'skipScaleValidation': value['skipScaleValidation'],
        'energyClass': value['energyClass'],
        'energyClassImage': value['energyClassImage'],
        'formType': value['formType'],
        'visibleToUkMsa': value['visibleToUkMsa'],
        'exportDateTs': value['exportDateTs'],
        'importedOn': value['importedOn'],
        'orgVerificationStatus': value['orgVerificationStatus'],
        'trademarkVerificationStatus': value['trademarkVerificationStatus'],
        'blocked': value['blocked'],
        'uploadedLabels': value['uploadedLabels'] == null ? undefined : ((value['uploadedLabels'] as Array<any>).map(UploadedLabelToJSON)),
        'contactDetails': ContactDetailsToJSON(value['contactDetails']),
        'placementCountries': value['placementCountries'] == null ? undefined : ((value['placementCountries'] as Array<any>).map(PlacementCountryToJSON)),
        'organisation': OrganisationToJSON(value['organisation']),
        'numericGtin': value['numericGtin'],
        'categorySpecificAttributes': value['categorySpecificAttributes'],
        'onMarketStartDate': value['onMarketStartDate'],
        'onMarketStartDateTS': value['onMarketStartDateTS'],
        'onMarketEndDate': value['onMarketEndDate'],
        'onMarketEndDateTS': value['onMarketEndDateTS'],
        'onMarketFirstStartDate': value['onMarketFirstStartDate'],
        'onMarketFirstStartDateTS': value['onMarketFirstStartDateTS'],
        'firstPublicationDate': value['firstPublicationDate'],
        'firstPublicationDateTS': value['firstPublicationDateTS'],
        'publishedOnDate': value['publishedOnDate'],
        'publishedOnDateTS': value['publishedOnDateTS'],
        'gtinIdentifier': value['gtinIdentifier'],
        'additionalDetails': AdditionalDetailsToJSON(value['additionalDetails']),
        'category': value['category'],
    };
}

