/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductNamesDto
 */
export interface ProductNamesDto {
    /**
     * H1 title for the requested language
     * @type {string}
     * @memberof ProductNamesDto
     */
    h1Title?: string;
    /**
     * Pretty name for the requested language
     * @type {string}
     * @memberof ProductNamesDto
     */
    prettyName?: string;
    /**
     * Singular product name for the requested language
     * @type {string}
     * @memberof ProductNamesDto
     */
    singular?: string;
    /**
     * Singular designation for the requested language
     * @type {string}
     * @memberof ProductNamesDto
     */
    singularDesignation?: string;
    /**
     * Generated designation variants for the requested language
     * @type {Array<string>}
     * @memberof ProductNamesDto
     */
    designation?: Array<string>;
    /**
     * Meta description aligned with the requested language
     * @type {string}
     * @memberof ProductNamesDto
     */
    metaDescription?: string;
    /**
     * OpenGraph title for social sharing
     * @type {string}
     * @memberof ProductNamesDto
     */
    ogTitle?: string;
    /**
     * OpenGraph description for social sharing
     * @type {string}
     * @memberof ProductNamesDto
     */
    ogDescription?: string;
    /**
     * Title for product card
     * @type {string}
     * @memberof ProductNamesDto
     */
    cardTitle?: string;
    /**
     * Short name
     * @type {string}
     * @memberof ProductNamesDto
     */
    shortName?: string;
    /**
     * Long name
     * @type {string}
     * @memberof ProductNamesDto
     */
    longName?: string;
    /**
     * Offer names aggregated across datasources
     * @type {Set<string>}
     * @memberof ProductNamesDto
     */
    offerNames?: Set<string>;
    /**
     * Longest detected offer name
     * @type {string}
     * @memberof ProductNamesDto
     */
    longestOfferName?: string;
    /**
     * Shortest detected offer name
     * @type {string}
     * @memberof ProductNamesDto
     */
    shortestOfferName?: string;
}

/**
 * Check if a given object implements the ProductNamesDto interface.
 */
export function instanceOfProductNamesDto(value: object): value is ProductNamesDto {
    return true;
}

export function ProductNamesDtoFromJSON(json: any): ProductNamesDto {
    return ProductNamesDtoFromJSONTyped(json, false);
}

export function ProductNamesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductNamesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'h1Title': json['h1Title'] == null ? undefined : json['h1Title'],
        'prettyName': json['prettyName'] == null ? undefined : json['prettyName'],
        'singular': json['singular'] == null ? undefined : json['singular'],
        'singularDesignation': json['singularDesignation'] == null ? undefined : json['singularDesignation'],
        'designation': json['designation'] == null ? undefined : json['designation'],
        'metaDescription': json['metaDescription'] == null ? undefined : json['metaDescription'],
        'ogTitle': json['ogTitle'] == null ? undefined : json['ogTitle'],
        'ogDescription': json['ogDescription'] == null ? undefined : json['ogDescription'],
        'cardTitle': json['cardTitle'] == null ? undefined : json['cardTitle'],
        'shortName': json['shortName'] == null ? undefined : json['shortName'],
        'longName': json['longName'] == null ? undefined : json['longName'],
        'offerNames': json['offerNames'] == null ? undefined : new Set(json['offerNames']),
        'longestOfferName': json['longestOfferName'] == null ? undefined : json['longestOfferName'],
        'shortestOfferName': json['shortestOfferName'] == null ? undefined : json['shortestOfferName'],
    };
}

export function ProductNamesDtoToJSON(json: any): ProductNamesDto {
    return ProductNamesDtoToJSONTyped(json, false);
}

export function ProductNamesDtoToJSONTyped(value?: ProductNamesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'h1Title': value['h1Title'],
        'prettyName': value['prettyName'],
        'singular': value['singular'],
        'singularDesignation': value['singularDesignation'],
        'designation': value['designation'],
        'metaDescription': value['metaDescription'],
        'ogTitle': value['ogTitle'],
        'ogDescription': value['ogDescription'],
        'cardTitle': value['cardTitle'],
        'shortName': value['shortName'],
        'longName': value['longName'],
        'offerNames': value['offerNames'] == null ? undefined : Array.from(value['offerNames'] as Set<any>),
        'longestOfferName': value['longestOfferName'],
        'shortestOfferName': value['shortestOfferName'],
    };
}

