/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ProductAiTextsDto
 */
export interface ProductAiTextsDto {
  /**
   * AI description aligned with the requested domainLanguage once localisation is available.
   * @type {string}
   * @memberof ProductAiTextsDto
   */
  description?: string
}

/**
 * Check if a given object implements the ProductAiTextsDto interface.
 */
export function instanceOfProductAiTextsDto(
  value: object
): value is ProductAiTextsDto {
  return true
}

export function ProductAiTextsDtoFromJSON(json: any): ProductAiTextsDto {
  return ProductAiTextsDtoFromJSONTyped(json, false)
}

export function ProductAiTextsDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProductAiTextsDto {
  if (json == null) {
    return json
  }
  return {
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function ProductAiTextsDtoToJSON(json: any): ProductAiTextsDto {
  return ProductAiTextsDtoToJSONTyped(json, false)
}

export function ProductAiTextsDtoToJSONTyped(
  value?: ProductAiTextsDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    description: value['description'],
  }
}
