/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Origin datasource that produced the timeline event
 * @export
 */
export const ProductTimelineEventSource = {
    PriceHistory: 'PRICE_HISTORY',
    Eprel: 'EPREL'
} as const;
export type ProductTimelineEventSource = typeof ProductTimelineEventSource[keyof typeof ProductTimelineEventSource];


export function instanceOfProductTimelineEventSource(value: any): boolean {
    for (const key in ProductTimelineEventSource) {
        if (Object.prototype.hasOwnProperty.call(ProductTimelineEventSource, key)) {
            if (ProductTimelineEventSource[key as keyof typeof ProductTimelineEventSource] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProductTimelineEventSourceFromJSON(json: any): ProductTimelineEventSource {
    return ProductTimelineEventSourceFromJSONTyped(json, false);
}

export function ProductTimelineEventSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTimelineEventSource {
    return json as ProductTimelineEventSource;
}

export function ProductTimelineEventSourceToJSON(value?: ProductTimelineEventSource | null): any {
    return value as any;
}

export function ProductTimelineEventSourceToJSONTyped(value: any, ignoreDiscriminator: boolean): ProductTimelineEventSource {
    return value as ProductTimelineEventSource;
}

