/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductNamesDto
 */
export interface ProductNamesDto {
    /**
     * H1 title expected to align with the requested domainLanguage when localisation is available.
     * @type {string}
     * @memberof ProductNamesDto
     */
    h1Title?: string;
    /**
     * Meta description aligned to the requested domainLanguage once localisation is wired.
     * @type {string}
     * @memberof ProductNamesDto
     */
    metaDescription?: string;
    /**
     * OpenGraph title prepared for domainLanguage-driven localisation.
     * @type {string}
     * @memberof ProductNamesDto
     */
    ogTitle?: string;
    /**
     * OpenGraph description prepared for domainLanguage-driven localisation.
     * @type {string}
     * @memberof ProductNamesDto
     */
    ogDescription?: string;
    /**
     * Twitter title mirroring the requested domainLanguage in the future.
     * @type {string}
     * @memberof ProductNamesDto
     */
    twitterTitle?: string;
    /**
     * Twitter description mirroring the requested domainLanguage in the future.
     * @type {string}
     * @memberof ProductNamesDto
     */
    twitterDescription?: string;
}

/**
 * Check if a given object implements the ProductNamesDto interface.
 */
export function instanceOfProductNamesDto(value: object): value is ProductNamesDto {
    return true;
}

export function ProductNamesDtoFromJSON(json: any): ProductNamesDto {
    return ProductNamesDtoFromJSONTyped(json, false);
}

export function ProductNamesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductNamesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'h1Title': json['h1Title'] == null ? undefined : json['h1Title'],
        'metaDescription': json['metaDescription'] == null ? undefined : json['metaDescription'],
        'ogTitle': json['ogTitle'] == null ? undefined : json['ogTitle'],
        'ogDescription': json['ogDescription'] == null ? undefined : json['ogDescription'],
        'twitterTitle': json['twitterTitle'] == null ? undefined : json['twitterTitle'],
        'twitterDescription': json['twitterDescription'] == null ? undefined : json['twitterDescription'],
    };
}

export function ProductNamesDtoToJSON(json: any): ProductNamesDto {
    return ProductNamesDtoToJSONTyped(json, false);
}

export function ProductNamesDtoToJSONTyped(value?: ProductNamesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'h1Title': value['h1Title'],
        'metaDescription': value['metaDescription'],
        'ogTitle': value['ogTitle'],
        'ogDescription': value['ogDescription'],
        'twitterTitle': value['twitterTitle'],
        'twitterDescription': value['twitterDescription'],
    };
}

