/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldMetadataDto } from './FieldMetadataDto';
import {
    FieldMetadataDtoFromJSON,
    FieldMetadataDtoFromJSONTyped,
    FieldMetadataDtoToJSON,
    FieldMetadataDtoToJSONTyped,
} from './FieldMetadataDto';

/**
 * 
 * @export
 * @interface ProductFieldOptionsResponse
 */
export interface ProductFieldOptionsResponse {
    /**
     * Fields that are always available regardless of the vertical.
     * @type {FieldMetadataDto}
     * @memberof ProductFieldOptionsResponse
     */
    global?: FieldMetadataDto;
    /**
     * Fields relating to ecological impact scores only.
     * @type {FieldMetadataDto}
     * @memberof ProductFieldOptionsResponse
     */
    impact?: FieldMetadataDto;
    /**
     * Fields exposing technical attributes available for the vertical.
     * @type {FieldMetadataDto}
     * @memberof ProductFieldOptionsResponse
     */
    technical?: FieldMetadataDto;
}

/**
 * Check if a given object implements the ProductFieldOptionsResponse interface.
 */
export function instanceOfProductFieldOptionsResponse(value: object): value is ProductFieldOptionsResponse {
    return true;
}

export function ProductFieldOptionsResponseFromJSON(json: any): ProductFieldOptionsResponse {
    return ProductFieldOptionsResponseFromJSONTyped(json, false);
}

export function ProductFieldOptionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductFieldOptionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'global': json['global'] == null ? undefined : FieldMetadataDtoFromJSON(json['global']),
        'impact': json['impact'] == null ? undefined : FieldMetadataDtoFromJSON(json['impact']),
        'technical': json['technical'] == null ? undefined : FieldMetadataDtoFromJSON(json['technical']),
    };
}

export function ProductFieldOptionsResponseToJSON(json: any): ProductFieldOptionsResponse {
    return ProductFieldOptionsResponseToJSONTyped(json, false);
}

export function ProductFieldOptionsResponseToJSONTyped(value?: ProductFieldOptionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'global': FieldMetadataDtoToJSON(value['global']),
        'impact': FieldMetadataDtoToJSON(value['impact']),
        'technical': FieldMetadataDtoToJSON(value['technical']),
    };
}

