/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductReferenceDto } from './ProductReferenceDto';
import {
    ProductReferenceDtoFromJSON,
    ProductReferenceDtoFromJSONTyped,
    ProductReferenceDtoToJSON,
    ProductReferenceDtoToJSONTyped,
} from './ProductReferenceDto';

/**
 * 
 * @export
 * @interface ProductRankingDto
 */
export interface ProductRankingDto {
    /**
     * Global ranking position
     * @type {number}
     * @memberof ProductRankingDto
     */
    globalPosition?: number;
    /**
     * Number of items considered in the global ranking
     * @type {number}
     * @memberof ProductRankingDto
     */
    globalCount?: number;
    /**
     * Details about the best ranked product
     * @type {ProductReferenceDto}
     * @memberof ProductRankingDto
     */
    globalBest?: ProductReferenceDto;
    /**
     * Details about the product ranked immediately above
     * @type {ProductReferenceDto}
     * @memberof ProductRankingDto
     */
    globalBetter?: ProductReferenceDto;
    /**
     * Specialised ranking position
     * @type {number}
     * @memberof ProductRankingDto
     */
    specializedPosition?: number;
    /**
     * Number of items considered in the specialised ranking
     * @type {number}
     * @memberof ProductRankingDto
     */
    specializedCount?: number;
    /**
     * Identifier of the best product in the specialised ranking
     * @type {string}
     * @memberof ProductRankingDto
     */
    specializedBest?: string;
    /**
     * Identifier of the product ranked immediately above in the specialised ranking
     * @type {string}
     * @memberof ProductRankingDto
     */
    specializedBetter?: string;
}

/**
 * Check if a given object implements the ProductRankingDto interface.
 */
export function instanceOfProductRankingDto(value: object): value is ProductRankingDto {
    return true;
}

export function ProductRankingDtoFromJSON(json: any): ProductRankingDto {
    return ProductRankingDtoFromJSONTyped(json, false);
}

export function ProductRankingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductRankingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'globalPosition': json['globalPosition'] == null ? undefined : json['globalPosition'],
        'globalCount': json['globalCount'] == null ? undefined : json['globalCount'],
        'globalBest': json['globalBest'] == null ? undefined : ProductReferenceDtoFromJSON(json['globalBest']),
        'globalBetter': json['globalBetter'] == null ? undefined : ProductReferenceDtoFromJSON(json['globalBetter']),
        'specializedPosition': json['specializedPosition'] == null ? undefined : json['specializedPosition'],
        'specializedCount': json['specializedCount'] == null ? undefined : json['specializedCount'],
        'specializedBest': json['specializedBest'] == null ? undefined : json['specializedBest'],
        'specializedBetter': json['specializedBetter'] == null ? undefined : json['specializedBetter'],
    };
}

export function ProductRankingDtoToJSON(json: any): ProductRankingDto {
    return ProductRankingDtoToJSONTyped(json, false);
}

export function ProductRankingDtoToJSONTyped(value?: ProductRankingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'globalPosition': value['globalPosition'],
        'globalCount': value['globalCount'],
        'globalBest': ProductReferenceDtoToJSON(value['globalBest']),
        'globalBetter': ProductReferenceDtoToJSON(value['globalBetter']),
        'specializedPosition': value['specializedPosition'],
        'specializedCount': value['specializedCount'],
        'specializedBest': value['specializedBest'],
        'specializedBetter': value['specializedBetter'],
    };
}

