/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiReview } from './AiReview';
import {
    AiReviewFromJSON,
    AiReviewFromJSONTyped,
    AiReviewToJSON,
    AiReviewToJSONTyped,
} from './AiReview';

/**
 * 
 * @export
 * @interface ProductAiReviewDto
 */
export interface ProductAiReviewDto {
    /**
     * AI-generated review that will be aligned with the requested domainLanguage once localisation is active.
     * @type {AiReview}
     * @memberof ProductAiReviewDto
     */
    review?: AiReview;
    /**
     * Source weighting for the review content
     * @type {{ [key: string]: number; }}
     * @memberof ProductAiReviewDto
     */
    sources?: { [key: string]: number; };
    /**
     * Whether enough data was available to generate the review
     * @type {boolean}
     * @memberof ProductAiReviewDto
     */
    enoughData?: boolean;
    /**
     * Total tokens consumed by the AI generation
     * @type {number}
     * @memberof ProductAiReviewDto
     */
    totalTokens?: number;
    /**
     * Creation timestamp ms
     * @type {number}
     * @memberof ProductAiReviewDto
     */
    createdMs?: number;
}

/**
 * Check if a given object implements the ProductAiReviewDto interface.
 */
export function instanceOfProductAiReviewDto(value: object): value is ProductAiReviewDto {
    return true;
}

export function ProductAiReviewDtoFromJSON(json: any): ProductAiReviewDto {
    return ProductAiReviewDtoFromJSONTyped(json, false);
}

export function ProductAiReviewDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductAiReviewDto {
    if (json == null) {
        return json;
    }
    return {
        
        'review': json['review'] == null ? undefined : AiReviewFromJSON(json['review']),
        'sources': json['sources'] == null ? undefined : json['sources'],
        'enoughData': json['enoughData'] == null ? undefined : json['enoughData'],
        'totalTokens': json['totalTokens'] == null ? undefined : json['totalTokens'],
        'createdMs': json['createdMs'] == null ? undefined : json['createdMs'],
    };
}

export function ProductAiReviewDtoToJSON(json: any): ProductAiReviewDto {
    return ProductAiReviewDtoToJSONTyped(json, false);
}

export function ProductAiReviewDtoToJSONTyped(value?: ProductAiReviewDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'review': AiReviewToJSON(value['review']),
        'sources': value['sources'],
        'enoughData': value['enoughData'],
        'totalTokens': value['totalTokens'],
        'createdMs': value['createdMs'],
    };
}

