/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductExternalIdsDto
 */
export interface ProductExternalIdsDto {
    /**
     * Amazon Standard Identification Number
     * @type {string}
     * @memberof ProductExternalIdsDto
     */
    asin?: string;
    /**
     * Icecat identifier
     * @type {string}
     * @memberof ProductExternalIdsDto
     */
    icecat?: string;
    /**
     * Known manufacturer part numbers
     * @type {Set<string>}
     * @memberof ProductExternalIdsDto
     */
    mpn?: Set<string>;
    /**
     * Known stock keeping units
     * @type {Set<string>}
     * @memberof ProductExternalIdsDto
     */
    sku?: Set<string>;
}

/**
 * Check if a given object implements the ProductExternalIdsDto interface.
 */
export function instanceOfProductExternalIdsDto(value: object): value is ProductExternalIdsDto {
    return true;
}

export function ProductExternalIdsDtoFromJSON(json: any): ProductExternalIdsDto {
    return ProductExternalIdsDtoFromJSONTyped(json, false);
}

export function ProductExternalIdsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductExternalIdsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'asin': json['asin'] == null ? undefined : json['asin'],
        'icecat': json['icecat'] == null ? undefined : json['icecat'],
        'mpn': json['mpn'] == null ? undefined : new Set(json['mpn']),
        'sku': json['sku'] == null ? undefined : new Set(json['sku']),
    };
}

export function ProductExternalIdsDtoToJSON(json: any): ProductExternalIdsDto {
    return ProductExternalIdsDtoToJSONTyped(json, false);
}

export function ProductExternalIdsDtoToJSONTyped(value?: ProductExternalIdsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asin': value['asin'],
        'icecat': value['icecat'],
        'mpn': value['mpn'] == null ? undefined : Array.from(value['mpn'] as Set<any>),
        'sku': value['sku'] == null ? undefined : Array.from(value['sku'] as Set<any>),
    };
}

