/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductAttributeDto } from './ProductAttributeDto';
import {
    ProductAttributeDtoFromJSON,
    ProductAttributeDtoFromJSONTyped,
    ProductAttributeDtoToJSON,
    ProductAttributeDtoToJSONTyped,
} from './ProductAttributeDto';
import type { ProductIndexedAttributeDto } from './ProductIndexedAttributeDto';
import {
    ProductIndexedAttributeDtoFromJSON,
    ProductIndexedAttributeDtoFromJSONTyped,
    ProductIndexedAttributeDtoToJSON,
    ProductIndexedAttributeDtoToJSONTyped,
} from './ProductIndexedAttributeDto';

/**
 * 
 * @export
 * @interface ProductAttributesDto
 */
export interface ProductAttributesDto {
    /**
     * Referential attributes keyed by the official attribute key
     * @type {{ [key: string]: string; }}
     * @memberof ProductAttributesDto
     */
    referentialAttributes?: { [key: string]: string; };
    /**
     * Indexed attributes keyed by their identifier
     * @type {{ [key: string]: ProductIndexedAttributeDto; }}
     * @memberof ProductAttributesDto
     */
    indexedAttributes?: { [key: string]: ProductIndexedAttributeDto; };
    /**
     * All attributes keyed by their identifier
     * @type {{ [key: string]: ProductAttributeDto; }}
     * @memberof ProductAttributesDto
     */
    allAttributes?: { [key: string]: ProductAttributeDto; };
    /**
     * Concatenated human readable characteristics
     * @type {string}
     * @memberof ProductAttributesDto
     */
    characteristics?: string;
}

/**
 * Check if a given object implements the ProductAttributesDto interface.
 */
export function instanceOfProductAttributesDto(value: object): value is ProductAttributesDto {
    return true;
}

export function ProductAttributesDtoFromJSON(json: any): ProductAttributesDto {
    return ProductAttributesDtoFromJSONTyped(json, false);
}

export function ProductAttributesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductAttributesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'referentialAttributes': json['referentialAttributes'] == null ? undefined : json['referentialAttributes'],
        'indexedAttributes': json['indexedAttributes'] == null ? undefined : (mapValues(json['indexedAttributes'], ProductIndexedAttributeDtoFromJSON)),
        'allAttributes': json['allAttributes'] == null ? undefined : (mapValues(json['allAttributes'], ProductAttributeDtoFromJSON)),
        'characteristics': json['characteristics'] == null ? undefined : json['characteristics'],
    };
}

export function ProductAttributesDtoToJSON(json: any): ProductAttributesDto {
    return ProductAttributesDtoToJSONTyped(json, false);
}

export function ProductAttributesDtoToJSONTyped(value?: ProductAttributesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referentialAttributes': value['referentialAttributes'],
        'indexedAttributes': value['indexedAttributes'] == null ? undefined : (mapValues(value['indexedAttributes'], ProductIndexedAttributeDtoToJSON)),
        'allAttributes': value['allAttributes'] == null ? undefined : (mapValues(value['allAttributes'], ProductAttributeDtoToJSON)),
        'characteristics': value['characteristics'],
    };
}

