/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface ProductTimelineEventDto
 */
export interface ProductTimelineEventDto {
    /**
     * Epoch milliseconds describing when the event occurred
     * @type {number}
     * @memberof ProductTimelineEventDto
     */
    timestamp?: number;
    /**
     * Type of lifecycle event
     * @type {string}
     * @memberof ProductTimelineEventDto
     */
    type?: ProductTimelineEventDtoTypeEnum;
    /**
     * Source system where the event originates
     * @type {string}
     * @memberof ProductTimelineEventDto
     */
    source?: ProductTimelineEventDtoSourceEnum;
    /**
     * Product condition associated with the event when relevant
     * @type {string}
     * @memberof ProductTimelineEventDto
     */
    condition?: ProductTimelineEventDtoConditionEnum;
    /**
     * Recorded price when the event originates from price history
     * @type {number}
     * @memberof ProductTimelineEventDto
     */
    price?: number;
}

/**
 * @export
 */
export const ProductTimelineEventDtoTypeEnum = {
    PriceFirstSeenNew: 'PRICE_FIRST_SEEN_NEW',
    PriceFirstSeenOccasion: 'PRICE_FIRST_SEEN_OCCASION',
    PriceLastSeenNew: 'PRICE_LAST_SEEN_NEW',
    PriceLastSeenOccasion: 'PRICE_LAST_SEEN_OCCASION',
    EprelOnMarketStart: 'EPREL_ON_MARKET_START',
    EprelOnMarketEnd: 'EPREL_ON_MARKET_END',
    EprelOnMarketFirstStart: 'EPREL_ON_MARKET_FIRST_START',
    EprelFirstPublication: 'EPREL_FIRST_PUBLICATION',
    EprelLastPublication: 'EPREL_LAST_PUBLICATION',
    EprelExport: 'EPREL_EXPORT',
    EprelImported: 'EPREL_IMPORTED',
    EprelOrganisationClosed: 'EPREL_ORGANISATION_CLOSED'
} as const;
export type ProductTimelineEventDtoTypeEnum = typeof ProductTimelineEventDtoTypeEnum[keyof typeof ProductTimelineEventDtoTypeEnum];

/**
 * @export
 */
export const ProductTimelineEventDtoSourceEnum = {
    PriceHistory: 'PRICE_HISTORY',
    Eprel: 'EPREL'
} as const;
export type ProductTimelineEventDtoSourceEnum = typeof ProductTimelineEventDtoSourceEnum[keyof typeof ProductTimelineEventDtoSourceEnum];

/**
 * @export
 */
export const ProductTimelineEventDtoConditionEnum = {
    Occasion: 'OCCASION',
    New: 'NEW'
} as const;
export type ProductTimelineEventDtoConditionEnum = typeof ProductTimelineEventDtoConditionEnum[keyof typeof ProductTimelineEventDtoConditionEnum];

/**
 * Check if a given object implements the ProductTimelineEventDto interface.
 */
export function instanceOfProductTimelineEventDto(value: object): value is ProductTimelineEventDto {
    return true;
}

export function ProductTimelineEventDtoFromJSON(json: any): ProductTimelineEventDto {
    return ProductTimelineEventDtoFromJSONTyped(json, false);
}

export function ProductTimelineEventDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTimelineEventDto {
    if (json == null) {
        return json;
    }
    return {

        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'type': json['type'] == null ? undefined : json['type'],
        'source': json['source'] == null ? undefined : json['source'],
        'condition': json['condition'] == null ? undefined : json['condition'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function ProductTimelineEventDtoToJSON(json: any): ProductTimelineEventDto {
    return ProductTimelineEventDtoToJSONTyped(json, false);
}

export function ProductTimelineEventDtoToJSONTyped(value?: ProductTimelineEventDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'timestamp': value['timestamp'],
        'type': value['type'],
        'source': value['source'],
        'condition': value['condition'],
        'price': value['price'],
    };
}

