/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductAttributeDto } from './ProductAttributeDto';
import {
    ProductAttributeDtoFromJSON,
    ProductAttributeDtoFromJSONTyped,
    ProductAttributeDtoToJSON,
    ProductAttributeDtoToJSONTyped,
} from './ProductAttributeDto';

/**
 * 
 * @export
 * @interface ProductClassifiedAttributeGroupDto
 */
export interface ProductClassifiedAttributeGroupDto {
    /**
     * Localized display name of the feature group
     * @type {string}
     * @memberof ProductClassifiedAttributeGroupDto
     */
    name?: string;
    /**
     * All attributes associated with the feature group
     * @type {Array<ProductAttributeDto>}
     * @memberof ProductClassifiedAttributeGroupDto
     */
    attributes?: Array<ProductAttributeDto>;
    /**
     * Attributes flagged as features in the Icecat taxonomy
     * @type {Array<ProductAttributeDto>}
     * @memberof ProductClassifiedAttributeGroupDto
     */
    features?: Array<ProductAttributeDto>;
    /**
     * Attributes flagged as unfeatures in the Icecat taxonomy
     * @type {Array<ProductAttributeDto>}
     * @memberof ProductClassifiedAttributeGroupDto
     */
    unFeatures?: Array<ProductAttributeDto>;
}

/**
 * Check if a given object implements the ProductClassifiedAttributeGroupDto interface.
 */
export function instanceOfProductClassifiedAttributeGroupDto(value: object): value is ProductClassifiedAttributeGroupDto {
    return true;
}

export function ProductClassifiedAttributeGroupDtoFromJSON(json: any): ProductClassifiedAttributeGroupDto {
    return ProductClassifiedAttributeGroupDtoFromJSONTyped(json, false);
}

export function ProductClassifiedAttributeGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductClassifiedAttributeGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(ProductAttributeDtoFromJSON)),
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(ProductAttributeDtoFromJSON)),
        'unFeatures': json['unFeatures'] == null ? undefined : ((json['unFeatures'] as Array<any>).map(ProductAttributeDtoFromJSON)),
    };
}

export function ProductClassifiedAttributeGroupDtoToJSON(json: any): ProductClassifiedAttributeGroupDto {
    return ProductClassifiedAttributeGroupDtoToJSONTyped(json, false);
}

export function ProductClassifiedAttributeGroupDtoToJSONTyped(value?: ProductClassifiedAttributeGroupDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(ProductAttributeDtoToJSON)),
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(ProductAttributeDtoToJSON)),
        'unFeatures': value['unFeatures'] == null ? undefined : ((value['unFeatures'] as Array<any>).map(ProductAttributeDtoToJSON)),
    };
}

