/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductVideoDto
 */
export interface ProductVideoDto {
    /**
     * Resource URL
     * @type {string}
     * @memberof ProductVideoDto
     */
    url?: string;
    /**
     * Detected MIME type
     * @type {string}
     * @memberof ProductVideoDto
     */
    mimeType?: string;
    /**
     * Last update timestamp in epoch milliseconds
     * @type {number}
     * @memberof ProductVideoDto
     */
    timeStamp?: number;
    /**
     * Cache key used by the media pipeline
     * @type {string}
     * @memberof ProductVideoDto
     */
    cacheKey?: string;
    /**
     * Whether the resource has been evicted from the catalogue
     * @type {boolean}
     * @memberof ProductVideoDto
     */
    evicted?: boolean;
    /**
     * Whether the resource has been processed
     * @type {boolean}
     * @memberof ProductVideoDto
     */
    processed?: boolean;
    /**
     * Status assigned by the ingestion pipeline
     * @type {string}
     * @memberof ProductVideoDto
     */
    status?: ProductVideoDtoStatusEnum;
    /**
     * Size in bytes when known
     * @type {number}
     * @memberof ProductVideoDto
     */
    fileSize?: number;
    /**
     * File name extracted from the URL
     * @type {string}
     * @memberof ProductVideoDto
     */
    fileName?: string;
    /**
     * File extension
     * @type {string}
     * @memberof ProductVideoDto
     */
    extension?: string;
    /**
     * MD5 checksum when available
     * @type {string}
     * @memberof ProductVideoDto
     */
    md5?: string;
    /**
     * Resource type
     * @type {string}
     * @memberof ProductVideoDto
     */
    resourceType?: ProductVideoDtoResourceTypeEnum;
    /**
     * Group identifier used to cluster similar resources
     * @type {number}
     * @memberof ProductVideoDto
     */
    group?: number;
    /**
     * Datasource providing the resource
     * @type {string}
     * @memberof ProductVideoDto
     */
    datasourceName?: string;
    /**
     * Tags describing the resource
     * @type {Set<string>}
     * @memberof ProductVideoDto
     */
    tags?: Set<string>;
    /**
     * Hard tags describing the resource nature
     * @type {Set<string>}
     * @memberof ProductVideoDto
     */
    hardTags?: Set<ProductVideoDtoHardTagsEnum>;
}


/**
 * @export
 */
export const ProductVideoDtoStatusEnum = {
    Md5ChecksumFail: 'MD5_CHECKSUM_FAIL',
    ProtocolException: 'PROTOCOL_EXCEPTION',
    IoException: 'IO_EXCEPTION',
    NoMimeType: 'NO_MIME_TYPE',
    Md5Exclusion: 'MD5_EXCLUSION',
    Md5Duplicate: 'MD5_DUPLICATE',
    TooSmall: 'TOO_SMALL',
    CannotAnalyse: 'CANNOT_ANALYSE',
    PerceptivHashFail: 'PERCEPTIV_HASH_FAIL',
    PdfParsingError: 'PDF_PARSING_ERROR'
} as const;
export type ProductVideoDtoStatusEnum = typeof ProductVideoDtoStatusEnum[keyof typeof ProductVideoDtoStatusEnum];

/**
 * @export
 */
export const ProductVideoDtoResourceTypeEnum = {
    Image: 'IMAGE',
    Pdf: 'PDF',
    Unknown: 'UNKNOWN',
    Video: 'VIDEO'
} as const;
export type ProductVideoDtoResourceTypeEnum = typeof ProductVideoDtoResourceTypeEnum[keyof typeof ProductVideoDtoResourceTypeEnum];

/**
 * @export
 */
export const ProductVideoDtoHardTagsEnum = {
    AmazonPrimaryTag: 'AMAZON_PRIMARY_TAG',
    AmazonVariantTag: 'AMAZON_VARIANT_TAG',
    Primary: 'PRIMARY',
    RepairabilitySheet: 'REPAIRABILITY_SHEET',
    ProductSheet: 'PRODUCT_SHEET',
    Manual: 'MANUAL',
    InformationSheet: 'INFORMATION_SHEET',
    EnergyLabel: 'ENERGY_LABEL',
    Leaflet: 'LEAFLET'
} as const;
export type ProductVideoDtoHardTagsEnum = typeof ProductVideoDtoHardTagsEnum[keyof typeof ProductVideoDtoHardTagsEnum];


/**
 * Check if a given object implements the ProductVideoDto interface.
 */
export function instanceOfProductVideoDto(value: object): value is ProductVideoDto {
    return true;
}

export function ProductVideoDtoFromJSON(json: any): ProductVideoDto {
    return ProductVideoDtoFromJSONTyped(json, false);
}

export function ProductVideoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVideoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'timeStamp': json['timeStamp'] == null ? undefined : json['timeStamp'],
        'cacheKey': json['cacheKey'] == null ? undefined : json['cacheKey'],
        'evicted': json['evicted'] == null ? undefined : json['evicted'],
        'processed': json['processed'] == null ? undefined : json['processed'],
        'status': json['status'] == null ? undefined : json['status'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'extension': json['extension'] == null ? undefined : json['extension'],
        'md5': json['md5'] == null ? undefined : json['md5'],
        'resourceType': json['resourceType'] == null ? undefined : json['resourceType'],
        'group': json['group'] == null ? undefined : json['group'],
        'datasourceName': json['datasourceName'] == null ? undefined : json['datasourceName'],
        'tags': json['tags'] == null ? undefined : new Set(json['tags']),
        'hardTags': json['hardTags'] == null ? undefined : new Set(json['hardTags']),
    };
}

export function ProductVideoDtoToJSON(json: any): ProductVideoDto {
    return ProductVideoDtoToJSONTyped(json, false);
}

export function ProductVideoDtoToJSONTyped(value?: ProductVideoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'mimeType': value['mimeType'],
        'timeStamp': value['timeStamp'],
        'cacheKey': value['cacheKey'],
        'evicted': value['evicted'],
        'processed': value['processed'],
        'status': value['status'],
        'fileSize': value['fileSize'],
        'fileName': value['fileName'],
        'extension': value['extension'],
        'md5': value['md5'],
        'resourceType': value['resourceType'],
        'group': value['group'],
        'datasourceName': value['datasourceName'],
        'tags': value['tags'] == null ? undefined : Array.from(value['tags'] as Set<any>),
        'hardTags': value['hardTags'] == null ? undefined : Array.from(value['hardTags'] as Set<any>),
    };
}

