/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface RecommandationChoice
 */
export interface RecommandationChoice {
  /**
   *
   * @type {string}
   * @memberof RecommandationChoice
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof RecommandationChoice
   */
  queryFragment?: string
  /**
   *
   * @type {boolean}
   * @memberof RecommandationChoice
   */
  defaultChoice?: boolean
  /**
   *
   * @type {number}
   * @memberof RecommandationChoice
   */
  divid?: number
}

/**
 * Check if a given object implements the RecommandationChoice interface.
 */
export function instanceOfRecommandationChoice(
  value: object
): value is RecommandationChoice {
  return true
}

export function RecommandationChoiceFromJSON(json: any): RecommandationChoice {
  return RecommandationChoiceFromJSONTyped(json, false)
}

export function RecommandationChoiceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RecommandationChoice {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    queryFragment:
      json['queryFragment'] == null ? undefined : json['queryFragment'],
    defaultChoice:
      json['defaultChoice'] == null ? undefined : json['defaultChoice'],
    divid: json['divid'] == null ? undefined : json['divid'],
  }
}

export function RecommandationChoiceToJSON(json: any): RecommandationChoice {
  return RecommandationChoiceToJSONTyped(json, false)
}

export function RecommandationChoiceToJSONTyped(
  value?: RecommandationChoice | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    queryFragment: value['queryFragment'],
    defaultChoice: value['defaultChoice'],
    divid: value['divid'],
  }
}
