/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoreNormalizationParamsDto } from './ScoreNormalizationParamsDto';
import {
    ScoreNormalizationParamsDtoFromJSON,
    ScoreNormalizationParamsDtoFromJSONTyped,
    ScoreNormalizationParamsDtoToJSON,
    ScoreNormalizationParamsDtoToJSONTyped,
} from './ScoreNormalizationParamsDto';

/**
 * 
 * @export
 * @interface ScoreNormalizationConfigDto
 */
export interface ScoreNormalizationConfigDto {
    /**
     * Normalization method used for this score.
     * @type {string}
     * @memberof ScoreNormalizationConfigDto
     */
    method?: ScoreNormalizationConfigDtoMethodEnum;
    /**
     * Parameters used by the normalization method.
     * @type {ScoreNormalizationParamsDto}
     * @memberof ScoreNormalizationConfigDto
     */
    params?: ScoreNormalizationParamsDto;
}


/**
 * @export
 */
export const ScoreNormalizationConfigDtoMethodEnum = {
    Sigma: 'SIGMA',
    Percentile: 'PERCENTILE',
    MinmaxFixed: 'MINMAX_FIXED',
    MinmaxObserved: 'MINMAX_OBSERVED',
    MinmaxQuantile: 'MINMAX_QUANTILE',
    FixedMapping: 'FIXED_MAPPING',
    Binary: 'BINARY',
    Constant: 'CONSTANT'
} as const;
export type ScoreNormalizationConfigDtoMethodEnum = typeof ScoreNormalizationConfigDtoMethodEnum[keyof typeof ScoreNormalizationConfigDtoMethodEnum];


/**
 * Check if a given object implements the ScoreNormalizationConfigDto interface.
 */
export function instanceOfScoreNormalizationConfigDto(value: object): value is ScoreNormalizationConfigDto {
    return true;
}

export function ScoreNormalizationConfigDtoFromJSON(json: any): ScoreNormalizationConfigDto {
    return ScoreNormalizationConfigDtoFromJSONTyped(json, false);
}

export function ScoreNormalizationConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreNormalizationConfigDto {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : ScoreNormalizationParamsDtoFromJSON(json['params']),
    };
}

export function ScoreNormalizationConfigDtoToJSON(json: any): ScoreNormalizationConfigDto {
    return ScoreNormalizationConfigDtoToJSONTyped(json, false);
}

export function ScoreNormalizationConfigDtoToJSONTyped(value?: ScoreNormalizationConfigDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'params': ScoreNormalizationParamsDtoToJSON(value['params']),
    };
}

