/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoreCardinalityDto
 */
export interface ScoreCardinalityDto {
    /**
     * Minimal value encountered
     * @type {number}
     * @memberof ScoreCardinalityDto
     */
    min?: number;
    /**
     * Maximal value encountered
     * @type {number}
     * @memberof ScoreCardinalityDto
     */
    max?: number;
    /**
     * Average value across the population
     * @type {number}
     * @memberof ScoreCardinalityDto
     */
    avg?: number;
    /**
     * Number of elements composing the population
     * @type {number}
     * @memberof ScoreCardinalityDto
     */
    count?: number;
    /**
     * Sum of the values
     * @type {number}
     * @memberof ScoreCardinalityDto
     */
    sum?: number;
    /**
     * Standard deviation σ of the distribution (variance = σ²)
     * @type {number}
     * @memberof ScoreCardinalityDto
     */
    stdDev?: number;
}

/**
 * Check if a given object implements the ScoreCardinalityDto interface.
 */
export function instanceOfScoreCardinalityDto(value: object): value is ScoreCardinalityDto {
    return true;
}

export function ScoreCardinalityDtoFromJSON(json: any): ScoreCardinalityDto {
    return ScoreCardinalityDtoFromJSONTyped(json, false);
}

export function ScoreCardinalityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreCardinalityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
        'avg': json['avg'] == null ? undefined : json['avg'],
        'count': json['count'] == null ? undefined : json['count'],
        'sum': json['sum'] == null ? undefined : json['sum'],
        'stdDev': json['stdDev'] == null ? undefined : json['stdDev'],
    };
}

export function ScoreCardinalityDtoToJSON(json: any): ScoreCardinalityDto {
    return ScoreCardinalityDtoToJSONTyped(json, false);
}

export function ScoreCardinalityDtoToJSONTyped(value?: ScoreCardinalityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'],
        'max': value['max'],
        'avg': value['avg'],
        'count': value['count'],
        'sum': value['sum'],
        'stdDev': value['stdDev'],
    };
}

