/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoreNormalizationParamsDto
 */
export interface ScoreNormalizationParamsDto {
    /**
     * Sigma factor used by SIGMA normalization.
     * @type {number}
     * @memberof ScoreNormalizationParamsDto
     */
    sigmaK?: number;
    /**
     * Fixed minimum bound used by MINMAX_FIXED normalization.
     * @type {number}
     * @memberof ScoreNormalizationParamsDto
     */
    fixedMin?: number;
    /**
     * Fixed maximum bound used by MINMAX_FIXED normalization.
     * @type {number}
     * @memberof ScoreNormalizationParamsDto
     */
    fixedMax?: number;
    /**
     * Lower quantile used by MINMAX_QUANTILE normalization.
     * @type {number}
     * @memberof ScoreNormalizationParamsDto
     */
    quantileLow?: number;
    /**
     * Upper quantile used by MINMAX_QUANTILE normalization.
     * @type {number}
     * @memberof ScoreNormalizationParamsDto
     */
    quantileHigh?: number;
    /**
     * Mapping table used by FIXED_MAPPING normalization.
     * @type {{ [key: string]: number; }}
     * @memberof ScoreNormalizationParamsDto
     */
    mapping?: { [key: string]: number; };
    /**
     * Constant value used by CONSTANT normalization.
     * @type {number}
     * @memberof ScoreNormalizationParamsDto
     */
    constantValue?: number;
    /**
     * Threshold used by BINARY normalization.
     * @type {number}
     * @memberof ScoreNormalizationParamsDto
     */
    threshold?: number;
    /**
     * When true, BINARY normalization passes when value >= threshold.
     * @type {boolean}
     * @memberof ScoreNormalizationParamsDto
     */
    greaterIsPass?: boolean;
}

/**
 * Check if a given object implements the ScoreNormalizationParamsDto interface.
 */
export function instanceOfScoreNormalizationParamsDto(value: object): value is ScoreNormalizationParamsDto {
    return true;
}

export function ScoreNormalizationParamsDtoFromJSON(json: any): ScoreNormalizationParamsDto {
    return ScoreNormalizationParamsDtoFromJSONTyped(json, false);
}

export function ScoreNormalizationParamsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreNormalizationParamsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sigmaK': json['sigmaK'] == null ? undefined : json['sigmaK'],
        'fixedMin': json['fixedMin'] == null ? undefined : json['fixedMin'],
        'fixedMax': json['fixedMax'] == null ? undefined : json['fixedMax'],
        'quantileLow': json['quantileLow'] == null ? undefined : json['quantileLow'],
        'quantileHigh': json['quantileHigh'] == null ? undefined : json['quantileHigh'],
        'mapping': json['mapping'] == null ? undefined : json['mapping'],
        'constantValue': json['constantValue'] == null ? undefined : json['constantValue'],
        'threshold': json['threshold'] == null ? undefined : json['threshold'],
        'greaterIsPass': json['greaterIsPass'] == null ? undefined : json['greaterIsPass'],
    };
}

export function ScoreNormalizationParamsDtoToJSON(json: any): ScoreNormalizationParamsDto {
    return ScoreNormalizationParamsDtoToJSONTyped(json, false);
}

export function ScoreNormalizationParamsDtoToJSONTyped(value?: ScoreNormalizationParamsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sigmaK': value['sigmaK'],
        'fixedMin': value['fixedMin'],
        'fixedMax': value['fixedMax'],
        'quantileLow': value['quantileLow'],
        'quantileHigh': value['quantileHigh'],
        'mapping': value['mapping'],
        'constantValue': value['constantValue'],
        'threshold': value['threshold'],
        'greaterIsPass': value['greaterIsPass'],
    };
}

