/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ScoreNormalizationConfigDto } from './ScoreNormalizationConfigDto';
import {
    ScoreNormalizationConfigDtoFromJSON,
    ScoreNormalizationConfigDtoFromJSONTyped,
    ScoreNormalizationConfigDtoToJSON,
    ScoreNormalizationConfigDtoToJSONTyped,
} from './ScoreNormalizationConfigDto';
import type { ScoreScaleDto } from './ScoreScaleDto';
import {
    ScoreScaleDtoFromJSON,
    ScoreScaleDtoFromJSONTyped,
    ScoreScaleDtoToJSON,
    ScoreScaleDtoToJSONTyped,
} from './ScoreScaleDto';

/**
 *
 * @export
 * @interface ScoreScoringConfigDto
 */
export interface ScoreScoringConfigDto {
    /**
     * Scale configuration for this score.
     * @type {ScoreScaleDto}
     * @memberof ScoreScoringConfigDto
     */
    scale?: ScoreScaleDto;
    /**
     * Normalization configuration for this score.
     * @type {ScoreNormalizationConfigDto}
     * @memberof ScoreScoringConfigDto
     */
    normalization?: ScoreNormalizationConfigDto;
    /**
     * Value transform applied before normalization.
     * @type {string}
     * @memberof ScoreScoringConfigDto
     */
    transform?: ScoreScoringConfigDtoTransformEnum;
    /**
     * Policy used when a value is missing.
     * @type {string}
     * @memberof ScoreScoringConfigDto
     */
    missingValuePolicy?: ScoreScoringConfigDtoMissingValuePolicyEnum;
    /**
     * Policy used when distribution is degenerate.
     * @type {string}
     * @memberof ScoreScoringConfigDto
     */
    degenerateDistributionPolicy?: ScoreScoringConfigDtoDegenerateDistributionPolicyEnum;
    /**
     * Population scope used to compute stats.
     * @type {string}
     * @memberof ScoreScoringConfigDto
     */
    statsScope?: ScoreScoringConfigDtoStatsScopeEnum;
}

/**
 * @export
 */
export const ScoreScoringConfigDtoTransformEnum = {
    None: 'NONE',
    Log: 'LOG',
    Sqrt: 'SQRT'
} as const;
export type ScoreScoringConfigDtoTransformEnum = typeof ScoreScoringConfigDtoTransformEnum[keyof typeof ScoreScoringConfigDtoTransformEnum];

/**
 * @export
 */
export const ScoreScoringConfigDtoMissingValuePolicyEnum = {
    Neutral: 'NEUTRAL',
    Worst: 'WORST',
    Exclude: 'EXCLUDE'
} as const;
export type ScoreScoringConfigDtoMissingValuePolicyEnum = typeof ScoreScoringConfigDtoMissingValuePolicyEnum[keyof typeof ScoreScoringConfigDtoMissingValuePolicyEnum];

/**
 * @export
 */
export const ScoreScoringConfigDtoDegenerateDistributionPolicyEnum = {
    Neutral: 'NEUTRAL',
    Error: 'ERROR',
    Fallback: 'FALLBACK'
} as const;
export type ScoreScoringConfigDtoDegenerateDistributionPolicyEnum = typeof ScoreScoringConfigDtoDegenerateDistributionPolicyEnum[keyof typeof ScoreScoringConfigDtoDegenerateDistributionPolicyEnum];

/**
 * @export
 */
export const ScoreScoringConfigDtoStatsScopeEnum = {
    Vertical: 'VERTICAL',
    Category: 'CATEGORY'
} as const;
export type ScoreScoringConfigDtoStatsScopeEnum = typeof ScoreScoringConfigDtoStatsScopeEnum[keyof typeof ScoreScoringConfigDtoStatsScopeEnum];

/**
 * Check if a given object implements the ScoreScoringConfigDto interface.
 */
export function instanceOfScoreScoringConfigDto(value: object): value is ScoreScoringConfigDto {
    return true;
}

export function ScoreScoringConfigDtoFromJSON(json: any): ScoreScoringConfigDto {
    return ScoreScoringConfigDtoFromJSONTyped(json, false);
}

export function ScoreScoringConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreScoringConfigDto {
    if (json == null) {
        return json;
    }
    return {
        'scale': json['scale'] == null ? undefined : ScoreScaleDtoFromJSON(json['scale']),
        'normalization': json['normalization'] == null ? undefined : ScoreNormalizationConfigDtoFromJSON(json['normalization']),
        'transform': json['transform'] == null ? undefined : json['transform'],
        'missingValuePolicy': json['missingValuePolicy'] == null ? undefined : json['missingValuePolicy'],
        'degenerateDistributionPolicy': json['degenerateDistributionPolicy'] == null ? undefined : json['degenerateDistributionPolicy'],
        'statsScope': json['statsScope'] == null ? undefined : json['statsScope'],
    };
}

export function ScoreScoringConfigDtoToJSON(json: any): ScoreScoringConfigDto {
    return ScoreScoringConfigDtoToJSONTyped(json, false);
}

export function ScoreScoringConfigDtoToJSONTyped(value?: ScoreScoringConfigDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'scale': ScoreScaleDtoToJSON(value['scale']),
        'normalization': ScoreNormalizationConfigDtoToJSON(value['normalization']),
        'transform': value['transform'],
        'missingValuePolicy': value['missingValuePolicy'],
        'degenerateDistributionPolicy': value['degenerateDistributionPolicy'],
        'statsScope': value['statsScope'],
    };
}
