/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchSuggestCategoryDto } from './SearchSuggestCategoryDto';
import {
    SearchSuggestCategoryDtoFromJSON,
    SearchSuggestCategoryDtoFromJSONTyped,
    SearchSuggestCategoryDtoToJSON,
    SearchSuggestCategoryDtoToJSONTyped,
} from './SearchSuggestCategoryDto';
import type { SearchSuggestProductDto } from './SearchSuggestProductDto';
import {
    SearchSuggestProductDtoFromJSON,
    SearchSuggestProductDtoFromJSONTyped,
    SearchSuggestProductDtoToJSON,
    SearchSuggestProductDtoToJSONTyped,
} from './SearchSuggestProductDto';

/**
 * 
 * @export
 * @interface SearchSuggestResponseDto
 */
export interface SearchSuggestResponseDto {
    /**
     * Category matches resolved from the in-memory vertical index.
     * @type {Array<SearchSuggestCategoryDto>}
     * @memberof SearchSuggestResponseDto
     */
    categoryMatches?: Array<SearchSuggestCategoryDto>;
    /**
     * Product matches obtained from the classical Elasticsearch search.
     * @type {Array<SearchSuggestProductDto>}
     * @memberof SearchSuggestResponseDto
     */
    productMatches?: Array<SearchSuggestProductDto>;
}

/**
 * Check if a given object implements the SearchSuggestResponseDto interface.
 */
export function instanceOfSearchSuggestResponseDto(value: object): value is SearchSuggestResponseDto {
    return true;
}

export function SearchSuggestResponseDtoFromJSON(json: any): SearchSuggestResponseDto {
    return SearchSuggestResponseDtoFromJSONTyped(json, false);
}

export function SearchSuggestResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSuggestResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryMatches': json['categoryMatches'] == null ? undefined : ((json['categoryMatches'] as Array<any>).map(SearchSuggestCategoryDtoFromJSON)),
        'productMatches': json['productMatches'] == null ? undefined : ((json['productMatches'] as Array<any>).map(SearchSuggestProductDtoFromJSON)),
    };
}

export function SearchSuggestResponseDtoToJSON(json: any): SearchSuggestResponseDto {
    return SearchSuggestResponseDtoToJSONTyped(json, false);
}

export function SearchSuggestResponseDtoToJSONTyped(value?: SearchSuggestResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryMatches': value['categoryMatches'] == null ? undefined : ((value['categoryMatches'] as Array<any>).map(SearchSuggestCategoryDtoToJSON)),
        'productMatches': value['productMatches'] == null ? undefined : ((value['productMatches'] as Array<any>).map(SearchSuggestProductDtoToJSON)),
    };
}

