/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface SearchSuggestCategoryMatchDto
 */
export interface SearchSuggestCategoryMatchDto {
    /**
     * Identifier of the matched vertical
     * @type {string}
     * @memberof SearchSuggestCategoryMatchDto
     */
    verticalId?: string;
    /**
     * URL of the category thumbnail
     * @type {string}
     * @memberof SearchSuggestCategoryMatchDto
     */
    imageSmall?: string;
    /**
     * Display name of the category
     * @type {string}
     * @memberof SearchSuggestCategoryMatchDto
     */
    verticalHomeTitle?: string;
    /**
     * Link to the category landing page
     * @type {string}
     * @memberof SearchSuggestCategoryMatchDto
     */
    verticalHomeUrl?: string;
}

/**
 * Check if a given object implements the SearchSuggestCategoryMatchDto interface.
 */
export function instanceOfSearchSuggestCategoryMatchDto(value: object): value is SearchSuggestCategoryMatchDto {
    return true;
}

export function SearchSuggestCategoryMatchDtoFromJSON(json: any): SearchSuggestCategoryMatchDto {
    return SearchSuggestCategoryMatchDtoFromJSONTyped(json, false);
}

export function SearchSuggestCategoryMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSuggestCategoryMatchDto {
    if (json == null) {
        return json;
    }
    return {

        'verticalId': json['verticalId'] == null ? undefined : json['verticalId'],
        'imageSmall': json['imageSmall'] == null ? undefined : json['imageSmall'],
        'verticalHomeTitle': json['verticalHomeTitle'] == null ? undefined : json['verticalHomeTitle'],
        'verticalHomeUrl': json['verticalHomeUrl'] == null ? undefined : json['verticalHomeUrl'],
    };
}

export function SearchSuggestCategoryMatchDtoToJSON(json: any): SearchSuggestCategoryMatchDto {
    return SearchSuggestCategoryMatchDtoToJSONTyped(json, false);
}

export function SearchSuggestCategoryMatchDtoToJSONTyped(value?: SearchSuggestCategoryMatchDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'verticalId': value['verticalId'],
        'imageSmall': value['imageSmall'],
        'verticalHomeTitle': value['verticalHomeTitle'],
        'verticalHomeUrl': value['verticalHomeUrl'],
    };
}

/**
 *
 * @export
 * @interface SearchSuggestProductMatchDto
 */
export interface SearchSuggestProductMatchDto {
    /**
     * Product model name
     * @type {string}
     * @memberof SearchSuggestProductMatchDto
     */
    model?: string;
    /**
     * Brand associated with the product
     * @type {string}
     * @memberof SearchSuggestProductMatchDto
     */
    brand?: string;
    /**
     * GTIN identifier
     * @type {string}
     * @memberof SearchSuggestProductMatchDto
     */
    gtin?: string;
    /**
     * Cover image path of the product
     * @type {string}
     * @memberof SearchSuggestProductMatchDto
     */
    coverImagePath?: string;
    /**
     * Identifier of the vertical the product belongs to
     * @type {string}
     * @memberof SearchSuggestProductMatchDto
     */
    verticalId?: string;
    /**
     * Ecoscore value of the product
     * @type {number}
     * @memberof SearchSuggestProductMatchDto
     */
    ecoscoreValue?: number;
    /**
     * Relevance score assigned by the search engine
     * @type {number}
     * @memberof SearchSuggestProductMatchDto
     */
    score?: number;
}

/**
 * Check if a given object implements the SearchSuggestProductMatchDto interface.
 */
export function instanceOfSearchSuggestProductMatchDto(value: object): value is SearchSuggestProductMatchDto {
    return true;
}

export function SearchSuggestProductMatchDtoFromJSON(json: any): SearchSuggestProductMatchDto {
    return SearchSuggestProductMatchDtoFromJSONTyped(json, false);
}

export function SearchSuggestProductMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSuggestProductMatchDto {
    if (json == null) {
        return json;
    }
    return {

        'model': json['model'] == null ? undefined : json['model'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'gtin': json['gtin'] == null ? undefined : json['gtin'],
        'coverImagePath': json['coverImagePath'] == null ? undefined : json['coverImagePath'],
        'verticalId': json['verticalId'] == null ? undefined : json['verticalId'],
        'ecoscoreValue': json['ecoscoreValue'] == null ? undefined : json['ecoscoreValue'],
        'score': json['score'] == null ? undefined : json['score'],
    };
}

export function SearchSuggestProductMatchDtoToJSON(json: any): SearchSuggestProductMatchDto {
    return SearchSuggestProductMatchDtoToJSONTyped(json, false);
}

export function SearchSuggestProductMatchDtoToJSONTyped(value?: SearchSuggestProductMatchDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'model': value['model'],
        'brand': value['brand'],
        'gtin': value['gtin'],
        'coverImagePath': value['coverImagePath'],
        'verticalId': value['verticalId'],
        'ecoscoreValue': value['ecoscoreValue'],
        'score': value['score'],
    };
}

/**
 *
 * @export
 * @interface SearchSuggestResponseDto
 */
export interface SearchSuggestResponseDto {
    /**
     * List of matching categories for the suggestion query
     * @type {Array<SearchSuggestCategoryMatchDto>}
     * @memberof SearchSuggestResponseDto
     */
    categoryMatches?: Array<SearchSuggestCategoryMatchDto>;
    /**
     * List of matching products for the suggestion query
     * @type {Array<SearchSuggestProductMatchDto>}
     * @memberof SearchSuggestResponseDto
     */
    productMatches?: Array<SearchSuggestProductMatchDto>;
}

/**
 * Check if a given object implements the SearchSuggestResponseDto interface.
 */
export function instanceOfSearchSuggestResponseDto(value: object): value is SearchSuggestResponseDto {
    return true;
}

export function SearchSuggestResponseDtoFromJSON(json: any): SearchSuggestResponseDto {
    return SearchSuggestResponseDtoFromJSONTyped(json, false);
}

export function SearchSuggestResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSuggestResponseDto {
    if (json == null) {
        return json;
    }
    return {

        'categoryMatches': json['categoryMatches'] == null ? undefined : ((json['categoryMatches'] as Array<any>).map(SearchSuggestCategoryMatchDtoFromJSON)),
        'productMatches': json['productMatches'] == null ? undefined : ((json['productMatches'] as Array<any>).map(SearchSuggestProductMatchDtoFromJSON)),
    };
}

export function SearchSuggestResponseDtoToJSON(json: any): SearchSuggestResponseDto {
    return SearchSuggestResponseDtoToJSONTyped(json, false);
}

export function SearchSuggestResponseDtoToJSONTyped(value?: SearchSuggestResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'categoryMatches': value['categoryMatches'] == null ? undefined : ((value['categoryMatches'] as Array<any>).map(SearchSuggestCategoryMatchDtoToJSON)),
        'productMatches': value['productMatches'] == null ? undefined : ((value['productMatches'] as Array<any>).map(SearchSuggestProductMatchDtoToJSON)),
    };
}

