/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SemanticScoreDiagnosticsDto
 */
export interface SemanticScoreDiagnosticsDto {
    /**
     * Number of semantic hits considered for diagnostics
     * @type {number}
     * @memberof SemanticScoreDiagnosticsDto
     */
    resultCount?: number;
    /**
     * Highest semantic score observed
     * @type {number}
     * @memberof SemanticScoreDiagnosticsDto
     */
    topScore?: number;
    /**
     * Lowest semantic score observed
     * @type {number}
     * @memberof SemanticScoreDiagnosticsDto
     */
    minScore?: number;
    /**
     * Average semantic score observed
     * @type {number}
     * @memberof SemanticScoreDiagnosticsDto
     */
    avgScore?: number;
    /**
     * Standard deviation of semantic scores
     * @type {number}
     * @memberof SemanticScoreDiagnosticsDto
     */
    scoreStdDev?: number;
}

/**
 * Check if a given object implements the SemanticScoreDiagnosticsDto interface.
 */
export function instanceOfSemanticScoreDiagnosticsDto(value: object): value is SemanticScoreDiagnosticsDto {
    return true;
}

export function SemanticScoreDiagnosticsDtoFromJSON(json: any): SemanticScoreDiagnosticsDto {
    return SemanticScoreDiagnosticsDtoFromJSONTyped(json, false);
}

export function SemanticScoreDiagnosticsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SemanticScoreDiagnosticsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'resultCount': json['resultCount'] == null ? undefined : json['resultCount'],
        'topScore': json['topScore'] == null ? undefined : json['topScore'],
        'minScore': json['minScore'] == null ? undefined : json['minScore'],
        'avgScore': json['avgScore'] == null ? undefined : json['avgScore'],
        'scoreStdDev': json['scoreStdDev'] == null ? undefined : json['scoreStdDev'],
    };
}

export function SemanticScoreDiagnosticsDtoToJSON(json: any): SemanticScoreDiagnosticsDto {
    return SemanticScoreDiagnosticsDtoToJSONTyped(json, false);
}

export function SemanticScoreDiagnosticsDtoToJSONTyped(value?: SemanticScoreDiagnosticsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resultCount': value['resultCount'],
        'topScore': value['topScore'],
        'minScore': value['minScore'],
        'avgScore': value['avgScore'],
        'scoreStdDev': value['scoreStdDev'],
    };
}

