/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { ProductAggregatedPriceDto } from './ProductAggregatedPriceDto'
import {
  ProductAggregatedPriceDtoFromJSON,
  ProductAggregatedPriceDtoFromJSONTyped,
  ProductAggregatedPriceDtoToJSON,
  ProductAggregatedPriceDtoToJSONTyped,
} from './ProductAggregatedPriceDto'

/**
 *
 * @export
 * @interface ShareCandidateDto
 */
export interface ShareCandidateDto {
  /**
   * Identifier of the product (GTIN or slug)
   * @type {string}
   * @memberof ShareCandidateDto
   */
  productId?: string
  /**
   * Candidate display name
   * @type {string}
   * @memberof ShareCandidateDto
   */
  name?: string
  /**
   * Preferred image for the candidate
   * @type {string}
   * @memberof ShareCandidateDto
   */
  image?: string
  /**
   * Eco score when available
   * @type {number}
   * @memberof ShareCandidateDto
   */
  ecoScore?: number
  /**
   * Environmental impact score when available
   * @type {number}
   * @memberof ShareCandidateDto
   */
  impactScore?: number
  /**
   * Best indexed price without triggering live scraping
   * @type {ProductAggregatedPriceDto}
   * @memberof ShareCandidateDto
   */
  bestPrice?: ProductAggregatedPriceDto
  /**
   * Confidence score associated to the match
   * @type {number}
   * @memberof ShareCandidateDto
   */
  confidence?: number
}

/**
 * Check if a given object implements the ShareCandidateDto interface.
 */
export function instanceOfShareCandidateDto(
  value: object
): value is ShareCandidateDto {
  return true
}

export function ShareCandidateDtoFromJSON(json: any): ShareCandidateDto {
  return ShareCandidateDtoFromJSONTyped(json, false)
}

export function ShareCandidateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ShareCandidateDto {
  if (json == null) {
    return json
  }
  return {
    productId: json['productId'] == null ? undefined : json['productId'],
    name: json['name'] == null ? undefined : json['name'],
    image: json['image'] == null ? undefined : json['image'],
    ecoScore: json['ecoScore'] == null ? undefined : json['ecoScore'],
    impactScore: json['impactScore'] == null ? undefined : json['impactScore'],
    bestPrice:
      json['bestPrice'] == null
        ? undefined
        : ProductAggregatedPriceDtoFromJSON(json['bestPrice']),
    confidence: json['confidence'] == null ? undefined : json['confidence'],
  }
}

export function ShareCandidateDtoToJSON(json: any): ShareCandidateDto {
  return ShareCandidateDtoToJSONTyped(json, false)
}

export function ShareCandidateDtoToJSONTyped(
  value?: ShareCandidateDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    productId: value['productId'],
    name: value['name'],
    image: value['image'],
    ecoScore: value['ecoScore'],
    impactScore: value['impactScore'],
    bestPrice: ProductAggregatedPriceDtoToJSON(value['bestPrice']),
    confidence: value['confidence'],
  }
}
