/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareExtractionDto
 */
export interface ShareExtractionDto {
    /**
     * Extracted GTIN when resolvable
     * @type {string}
     * @memberof ShareExtractionDto
     */
    gtin?: string;
    /**
     * Query derived from the URL or shared content
     * @type {string}
     * @memberof ShareExtractionDto
     */
    query?: string;
}

/**
 * Check if a given object implements the ShareExtractionDto interface.
 */
export function instanceOfShareExtractionDto(value: object): value is ShareExtractionDto {
    return true;
}

export function ShareExtractionDtoFromJSON(json: any): ShareExtractionDto {
    return ShareExtractionDtoFromJSONTyped(json, false);
}

export function ShareExtractionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareExtractionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'gtin': json['gtin'] == null ? undefined : json['gtin'],
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function ShareExtractionDtoToJSON(json: any): ShareExtractionDto {
    return ShareExtractionDtoToJSONTyped(json, false);
}

export function ShareExtractionDtoToJSONTyped(value?: ShareExtractionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gtin': value['gtin'],
        'query': value['query'],
    };
}

