/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SortOption
 */
export interface SortOption {
  /**
   * Field mapping used for sorting
   * @type {string}
   * @memberof SortOption
   */
  field?: string
  /**
   * Sort order
   * @type {string}
   * @memberof SortOption
   */
  order?: SortOptionOrderEnum
}

/**
 * @export
 */
export const SortOptionOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type SortOptionOrderEnum =
  (typeof SortOptionOrderEnum)[keyof typeof SortOptionOrderEnum]

/**
 * Check if a given object implements the SortOption interface.
 */
export function instanceOfSortOption(value: object): value is SortOption {
  return true
}

export function SortOptionFromJSON(json: any): SortOption {
  return SortOptionFromJSONTyped(json, false)
}

export function SortOptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SortOption {
  if (json == null) {
    return json
  }
  return {
    field: json['field'] == null ? undefined : json['field'],
    order: json['order'] == null ? undefined : json['order'],
  }
}

export function SortOptionToJSON(json: any): SortOption {
  return SortOptionToJSONTyped(json, false)
}

export function SortOptionToJSONTyped(
  value?: SortOption | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    field: value['field'],
    order: value['order'],
  }
}
