/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SortOption } from './SortOption';
import {
    SortOptionFromJSON,
    SortOptionFromJSONTyped,
    SortOptionToJSON,
    SortOptionToJSONTyped,
} from './SortOption';

/**
 * 
 * @export
 * @interface SortRequestDto
 */
export interface SortRequestDto {
    /**
     * Sort options applied in order of appearance
     * @type {Array<SortOption>}
     * @memberof SortRequestDto
     */
    sorts?: Array<SortOption>;
}

/**
 * Check if a given object implements the SortRequestDto interface.
 */
export function instanceOfSortRequestDto(value: object): value is SortRequestDto {
    return true;
}

export function SortRequestDtoFromJSON(json: any): SortRequestDto {
    return SortRequestDtoFromJSONTyped(json, false);
}

export function SortRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sorts': json['sorts'] == null ? undefined : ((json['sorts'] as Array<any>).map(SortOptionFromJSON)),
    };
}

export function SortRequestDtoToJSON(json: any): SortRequestDto {
    return SortRequestDtoToJSONTyped(json, false);
}

export function SortRequestDtoToJSONTyped(value?: SortRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sorts': value['sorts'] == null ? undefined : ((value['sorts'] as Array<any>).map(SortOptionToJSON)),
    };
}

