/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatavizChartPresetDto } from './DatavizChartPresetDto';
import {
    DatavizChartPresetDtoFromJSON,
    DatavizChartPresetDtoFromJSONTyped,
    DatavizChartPresetDtoToJSON,
    DatavizChartPresetDtoToJSONTyped,
} from './DatavizChartPresetDto';
import type { DatavizDefaultFilterDto } from './DatavizDefaultFilterDto';
import {
    DatavizDefaultFilterDtoFromJSON,
    DatavizDefaultFilterDtoFromJSONTyped,
    DatavizDefaultFilterDtoToJSON,
    DatavizDefaultFilterDtoToJSONTyped,
} from './DatavizDefaultFilterDto';

/**
 * Dataviz dashboard plan resolved for a vertical.
 * @export
 * @interface VerticalDatavizPlanDto
 */
export interface VerticalDatavizPlanDto {
    /**
     * Vertical identifier.
     * @type {string}
     * @memberof VerticalDatavizPlanDto
     */
    verticalId?: string;
    /**
     * Default filters injected by the backend.
     * @type {Array<DatavizDefaultFilterDto>}
     * @memberof VerticalDatavizPlanDto
     */
    defaultFilters?: Array<DatavizDefaultFilterDto>;
    /**
     * Chart presets available for the current vertical.
     * @type {Array<DatavizChartPresetDto>}
     * @memberof VerticalDatavizPlanDto
     */
    charts?: Array<DatavizChartPresetDto>;
}

/**
 * Check if a given object implements the VerticalDatavizPlanDto interface.
 */
export function instanceOfVerticalDatavizPlanDto(value: object): value is VerticalDatavizPlanDto {
    return true;
}

export function VerticalDatavizPlanDtoFromJSON(json: any): VerticalDatavizPlanDto {
    return VerticalDatavizPlanDtoFromJSONTyped(json, false);
}

export function VerticalDatavizPlanDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerticalDatavizPlanDto {
    if (json == null) {
        return json;
    }
    return {
        
        'verticalId': json['verticalId'] == null ? undefined : json['verticalId'],
        'defaultFilters': json['defaultFilters'] == null ? undefined : ((json['defaultFilters'] as Array<any>).map(DatavizDefaultFilterDtoFromJSON)),
        'charts': json['charts'] == null ? undefined : ((json['charts'] as Array<any>).map(DatavizChartPresetDtoFromJSON)),
    };
}

export function VerticalDatavizPlanDtoToJSON(json: any): VerticalDatavizPlanDto {
    return VerticalDatavizPlanDtoToJSONTyped(json, false);
}

export function VerticalDatavizPlanDtoToJSONTyped(value?: VerticalDatavizPlanDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verticalId': value['verticalId'],
        'defaultFilters': value['defaultFilters'] == null ? undefined : ((value['defaultFilters'] as Array<any>).map(DatavizDefaultFilterDtoToJSON)),
        'charts': value['charts'] == null ? undefined : ((value['charts'] as Array<any>).map(DatavizChartPresetDtoToJSON)),
    };
}

