/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubsetCriteria } from './SubsetCriteria';
import {
    SubsetCriteriaFromJSON,
    SubsetCriteriaFromJSONTyped,
    SubsetCriteriaToJSON,
    SubsetCriteriaToJSONTyped,
} from './SubsetCriteria';

/**
 * 
 * @export
 * @interface VerticalSubCategoryDto
 */
export interface VerticalSubCategoryDto {
    /**
     * Stable identifier of the sub-category.
     * @type {string}
     * @memberof VerticalSubCategoryDto
     */
    id?: string;
    /**
     * Localised URL segment below the parent category.
     * @type {string}
     * @memberof VerticalSubCategoryDto
     */
    slug?: string;
    /**
     * Localised H1 title displayed on the sub-category page.
     * @type {string}
     * @memberof VerticalSubCategoryDto
     */
    h1Title?: string;
    /**
     * Localised description displayed on the sub-category page.
     * @type {string}
     * @memberof VerticalSubCategoryDto
     */
    description?: string;
    /**
     * Optional image overriding the parent category image.
     * @type {string}
     * @memberof VerticalSubCategoryDto
     */
    image?: string;
    /**
     * Criteria always applied to the product listing on this sub-category page.
     * @type {Array<SubsetCriteria>}
     * @memberof VerticalSubCategoryDto
     */
    activatedFilters?: Array<SubsetCriteria>;
}

/**
 * Check if a given object implements the VerticalSubCategoryDto interface.
 */
export function instanceOfVerticalSubCategoryDto(value: object): value is VerticalSubCategoryDto {
    return true;
}

export function VerticalSubCategoryDtoFromJSON(json: any): VerticalSubCategoryDto {
    return VerticalSubCategoryDtoFromJSONTyped(json, false);
}

export function VerticalSubCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerticalSubCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'h1Title': json['h1Title'] == null ? undefined : json['h1Title'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'] == null ? undefined : json['image'],
        'activatedFilters': json['activatedFilters'] == null ? undefined : ((json['activatedFilters'] as Array<any>).map(SubsetCriteriaFromJSON)),
    };
}

export function VerticalSubCategoryDtoToJSON(json: any): VerticalSubCategoryDto {
    return VerticalSubCategoryDtoToJSONTyped(json, false);
}

export function VerticalSubCategoryDtoToJSONTyped(value?: VerticalSubCategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'h1Title': value['h1Title'],
        'description': value['description'],
        'image': value['image'],
        'activatedFilters': value['activatedFilters'] == null ? undefined : ((value['activatedFilters'] as Array<any>).map(SubsetCriteriaToJSON)),
    };
}

