/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerticalStatsDto
 */
export interface VerticalStatsDto {
    /**
     * Total number of products in this vertical (including excluded).
     * @type {number}
     * @memberof VerticalStatsDto
     */
    totalProducts?: number;
    /**
     * Number of excluded products in this vertical.
     * @type {number}
     * @memberof VerticalStatsDto
     */
    excludedProducts?: number;
    /**
     * Number of valid products (active, with offers) in this vertical.
     * @type {number}
     * @memberof VerticalStatsDto
     */
    validProducts?: number;
    /**
     * Number of rated products (having an impact score) in this vertical.
     * @type {number}
     * @memberof VerticalStatsDto
     */
    ratedProducts?: number;
    /**
     * Number of reviewed products (having an AI description) in this vertical.
     * @type {number}
     * @memberof VerticalStatsDto
     */
    reviewedProducts?: number;
}

/**
 * Check if a given object implements the VerticalStatsDto interface.
 */
export function instanceOfVerticalStatsDto(value: object): value is VerticalStatsDto {
    return true;
}

export function VerticalStatsDtoFromJSON(json: any): VerticalStatsDto {
    return VerticalStatsDtoFromJSONTyped(json, false);
}

export function VerticalStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerticalStatsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalProducts': json['totalProducts'] == null ? undefined : json['totalProducts'],
        'excludedProducts': json['excludedProducts'] == null ? undefined : json['excludedProducts'],
        'validProducts': json['validProducts'] == null ? undefined : json['validProducts'],
        'ratedProducts': json['ratedProducts'] == null ? undefined : json['ratedProducts'],
        'reviewedProducts': json['reviewedProducts'] == null ? undefined : json['reviewedProducts'],
    };
}

export function VerticalStatsDtoToJSON(json: any): VerticalStatsDto {
    return VerticalStatsDtoToJSONTyped(json, false);
}

export function VerticalStatsDtoToJSONTyped(value?: VerticalStatsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalProducts': value['totalProducts'],
        'excludedProducts': value['excludedProducts'],
        'validProducts': value['validProducts'],
        'ratedProducts': value['ratedProducts'],
        'reviewedProducts': value['reviewedProducts'],
    };
}

