/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface WikidataPropertyReferential
 */
export interface WikidataPropertyReferential {
  /**
   *
   * @type {string}
   * @memberof WikidataPropertyReferential
   */
  pid?: string
  /**
   *
   * @type {string}
   * @memberof WikidataPropertyReferential
   */
  name?: string
}

/**
 * Check if a given object implements the WikidataPropertyReferential interface.
 */
export function instanceOfWikidataPropertyReferential(
  value: object
): value is WikidataPropertyReferential {
  return true
}

export function WikidataPropertyReferentialFromJSON(
  json: any
): WikidataPropertyReferential {
  return WikidataPropertyReferentialFromJSONTyped(json, false)
}

export function WikidataPropertyReferentialFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WikidataPropertyReferential {
  if (json == null) {
    return json
  }
  return {
    pid: json['pid'] == null ? undefined : json['pid'],
    name: json['name'] == null ? undefined : json['name'],
  }
}

export function WikidataPropertyReferentialToJSON(
  json: any
): WikidataPropertyReferential {
  return WikidataPropertyReferentialToJSONTyped(json, false)
}

export function WikidataPropertyReferentialToJSONTyped(
  value?: WikidataPropertyReferential | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    pid: value['pid'],
    name: value['name'],
  }
}
