/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WikiPageConfig
 */
export interface WikiPageConfig {
    /**
     * 
     * @type {string}
     * @memberof WikiPageConfig
     */
    wikiUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPageConfig
     */
    verticalUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPageConfig
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPageConfig
     */
    faIcon?: string;
}

/**
 * Check if a given object implements the WikiPageConfig interface.
 */
export function instanceOfWikiPageConfig(value: object): value is WikiPageConfig {
    return true;
}

export function WikiPageConfigFromJSON(json: any): WikiPageConfig {
    return WikiPageConfigFromJSONTyped(json, false);
}

export function WikiPageConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WikiPageConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'wikiUrl': json['wikiUrl'] == null ? undefined : json['wikiUrl'],
        'verticalUrl': json['verticalUrl'] == null ? undefined : json['verticalUrl'],
        'title': json['title'] == null ? undefined : json['title'],
        'faIcon': json['faIcon'] == null ? undefined : json['faIcon'],
    };
}

export function WikiPageConfigToJSON(json: any): WikiPageConfig {
    return WikiPageConfigToJSONTyped(json, false);
}

export function WikiPageConfigToJSONTyped(value?: WikiPageConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wikiUrl': value['wikiUrl'],
        'verticalUrl': value['verticalUrl'],
        'title': value['title'],
        'faIcon': value['faIcon'],
    };
}

