// Export service factories and singletons
export { useBlogService } from './blog.services'
export { useCategoriesService } from './categories.services'
export { useAssistantConfigsService } from './assistant-configs.services'
export { useContentService } from './content.services'
export { authService } from './auth.services'
export { useTeamService } from './team.services'
export { useContactService } from './contact.services'
export { usePagesService } from './pages.services'
export { useOpenDataService } from './opendata.services'
export { useAffiliationService } from './affiliation.services'
export { usePartnerService } from './partners.services'
export { useProductService } from './products.services'
export { useAdministrationService } from './administration.services'
export { useCommercialEventsService } from './commercial-events.services'
export { useStatsService } from './stats.services'
export { useQuotaService } from './quota.services'
export * from './share-resolution.services'
