# This workflow will build and push a latest artefacts to the server

on: push
    
name: Build and deploy artefacts 

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install
        
      - name: Deploy API to server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "/api/target/api-0.0.1-SNAPSHOT.jar"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: "/opt/open4goods/bin/latest/api-latest.jar"     
            
      - name: Deploy UI to server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "/ui/target/ui-0.0.1-SNAPSHOT.jar"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: "/opt/open4goods/bin/latest/ui-latest.jar"   

                      

                                    
