# This workflow will build, test and push the latest version on the beta environment.

on: 
  pull_request:
    branches: [ master ]
    
name: 🔘 Check pull request

jobs:
  deploy:
    name: beta-test-build-publish
    runs-on: self-hosted

    steps:

      ############################################
      # Checkout the repository
      ###########################################   
          
      - uses: actions/checkout@v4

      ############################################
      # Install Java
      ###########################################      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      ############################################
      # Maven build and testing
      ###########################################    
                
      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots install
                