name: Deploy static frontend to GitHub Pages

on:
  push:
    paths:
      - 'frontend/**'    
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend

      - name: Build Nuxt (GitHub Pages)
        run: NITRO_PRESET=github_pages pnpm generate
        working-directory: frontend

      - name: Prepare dist/
        run: |
            rm -rf dist
            mkdir -p dist
            cp -r .output/public/* dist/
            echo 'static.nudger.fr' > dist/CNAME
        working-directory: frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist

