name: Front API Contract

on:
  push:
    paths:
      - 'front-api/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'front-api/**'

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build front-api
        run: mvn -pl front-api -am package -DskipTests

      - name: Start front-api
        run: |
          java -jar front-api/target/front-api-0.0.1-SNAPSHOT.jar &
          echo "PID=$!" >> $GITHUB_ENV

      - name: Wait for API docs
        run: npx wait-on http://localhost:8082/v3/api-docs/front

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
        working-directory: frontend

      - name: Generate client from local API
        run: pnpm exec openapi-generator-cli generate -i http://localhost:8082/v3/api-docs/front -g typescript-fetch -o tmp-client --skip-validate-spec
        working-directory: frontend

      - name: Check for unknown parameters
        run: |
          if grep -R "UNKNOWN_PARAMETER_NAME" -n tmp-client; then
            echo 'Unknown parameters found';
            exit 1;
          fi
        working-directory: frontend

      - name: Stop front-api
        if: always()
        run: |
          kill $PID

