name: Weekly KPI Report

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date (YYYY-MM-DD)"
        required: false
      end_date:
        description: "End date (YYYY-MM-DD)"
        required: false
      create_PR:
        description: "Create Pull Request (true/false)"
        required: false
        default: "true"

jobs:
  fetch_kpi:
    runs-on: ubuntu-latest
    outputs:
      json_file: ${{ steps.fetch.outputs.json_file }}
      start_date: ${{ steps.dates.outputs.START_DATE }}
      end_date: ${{ steps.dates.outputs.END_DATE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Set default dates & validate
        id: dates
        run: |
          # calcul des dates par défaut
          if [ -z "${{ github.event.inputs.start_date }}" ]; then
            START_DATE=$(date -d '7 days ago' +%F)
          else
            START_DATE="${{ github.event.inputs.start_date }}"
          fi
          if [ -z "${{ github.event.inputs.end_date }}" ]; then
            END_DATE=$(date +%F)
          else
            END_DATE="${{ github.event.inputs.end_date }}"
          fi

          # validation des dates
          if [ "$(date -d "$START_DATE" +%s)" -gt "$(date -d "$END_DATE" +%s)" ]; then
            echo "Erreur : start_date ($START_DATE) est postérieure à end_date ($END_DATE)" >&2
            exit 1
          fi

          echo "START_DATE=$START_DATE" >> $GITHUB_ENV
          echo "END_DATE=$END_DATE"   >> $GITHUB_ENV
          echo "START_DATE=$START_DATE" >> $GITHUB_OUTPUT
          echo "END_DATE=$END_DATE"     >> $GITHUB_OUTPUT

      - name: Fetch KPI data
        id: fetch
        env:
          PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_KEY }}
          XWIKI_API_TOKEN:  ${{ secrets.XWIKI_API_TOKEN }}
          GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_API_TOKEN: ${{ secrets.CUSTOM_API_TOKEN }}
        run: |
          pip install requests
          mkdir -p docs/json
          python scripts/fetch_kpi.py \
            $START_DATE $END_DATE docs/json/weekly_${END_DATE}.json
          echo "json_file=docs/json/weekly_${END_DATE}.json" >> $GITHUB_OUTPUT

      - name: Upload KPI JSON
        uses: actions/upload-artifact@v4
        with:
          name: kpi-json
          path: ${{ steps.fetch.outputs.json_file }}

      - name: Commit JSON file & create branch
        if: ${{ github.event.inputs.create_PR == 'true' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin weekly-report-${END_DATE} || true
          git checkout -B weekly-report-${END_DATE}
          git add ${{ steps.fetch.outputs.json_file }}
          git commit -m "KPI JSON report (${END_DATE})"
          git push -u origin weekly-report-${END_DATE} --force-with-lease

  generate_report:
    needs: fetch_kpi
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_PR == 'true' }}
    outputs:
      end_date: ${{ needs.fetch_kpi.outputs.end_date }}
    steps:
      - name: Checkout report branch
        uses: actions/checkout@v5
        with:
          ref: weekly-report-${{ needs.fetch_kpi.outputs.end_date }}
          fetch-depth: 0
  
      - name: Download KPI JSON
        uses: actions/download-artifact@v5
        with:
          name: kpi-json
          path: .
  
      - name: Generate Markdown & CSV
        run: |
          pip install pandas jinja2 matplotlib
          python scripts/generate_markdown.py \
            "${{ needs.fetch_kpi.outputs.json_file }}" \
            docs/templates/weekly_report_template.md \
            docs/weekly_${{ needs.fetch_kpi.outputs.end_date }}.md \
            docs/_kpi_tracking.csv
  
      - name: Commit Markdown & CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
  
          if ! git diff --quiet docs/; then
            git add docs/
            git commit -m "Weekly KPI Markdown & CSV (${{ needs.fetch_kpi.outputs.end_date }})"
            git push
          else
            echo "Rien à committer."
          fi

  create_issue_pr:
    needs: generate_report
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_PR == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: weekly-report-${{ needs.generate_report.outputs.end_date }}
          fetch-depth: 0

      - name: Create issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_URL=$(gh issue create \
            --title "Weekly KPI Follow-up - ${{ needs.generate_report.outputs.end_date }}" \
            --body "- [ ] Vérification des KPI\n- [ ] Discussion des alertes\n- [ ] Actions à prévoir\n")
          echo "ISSUE_URL=$ISSUE_URL" >> $GITHUB_ENV

      - name: Create PR linking issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --head weekly-report-${{ needs.generate_report.outputs.end_date }} \
            --base main \
            --title "Weekly KPI report - ${{ needs.generate_report.outputs.end_date }}" \
            --body "Automated weekly KPI report. Linked Issue: ${{ env.ISSUE_URL }}"
