# This workflow will trigger the remote ssh script to 
# restart application with the latest artefacts version
on: workflow_dispatch
    
name: Publish latest apps

jobs:
  deploy:
    name: publish-jars
    runs-on: self-hosted

    steps:
      - name: Publish via ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          command: sh /opt/open4goods/bin/publish-jars.sh

          
          

                      

                                    
