# This workflow will trigger the remote ssh script to 
# restart infrastructure with the latest artefacts version
on: workflow_dispatch
    
name: Publish latest infrastructure on production environment

jobs:
  deploy:
    name: publish-infra-prod
    runs-on: self-hosted

    steps:
      - name: Publish via ssh
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: sh /opt/open4goods/bin/publish-infra.sh
        
                
          
          

                      

                                    
