name: TEST2
on:
  push:
    tags:
      - '*'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
  
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: test-github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    name: prod-release-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      ############################################
      # Create the release with changelog
      ###########################################  
            
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          configurationJson: |
            {
              "template": "#{{steps.tag.outputs.tag}} #{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }     

          files: |
            LICENSE

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release




          
          