name: Validate YAML/JSON/XML files

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.json'
      - '**/*.xml'
  push:
    branches: [ main ]
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.json'
      - '**/*.xml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.14"

      - name: Run pre-commit (syntax-only)
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
